### ISSUE TITLE
Magento 2.0

### ISSUE THREAD

**Issue by kaumac** [pagarme/pagarme-magento#1]
Vocês pretendem lançar uma versão pra Magento 2.0? O Um RC para developers será lançado esse mês, para vendedores no meio do ano e até o fim do ano a versão final.
Tenho uma loja que hoje esta no Shopify, que não tem integração com o pagar.me. Vou migrar para o magento, em parte para poder usar o pagar.me, mas não vale a pena migrar pro 1.7 sendo que o 2.0 ja esta sendo lançado.

**Comment by deivisonarthur** [comment]
Opa Kaue, brother o Magento está na versão 1.9.1.1. A versão 2.0 esta para lançar, porém ela só deve ser usada aqui no Brasil pelo menos daqui um a dois anos no mínimo. 

Venho acompanhando a evolução do 2.0 e posso te colocar que ele será top e irá separar o joio do trigo rs. Ou seja, somente quem sabe muito de Magento saberá desenvolver para ele. Mas é como estou te falando vai demorar muito ainda para termos o primeiro case brasileiro usando ele, além de todas as ferramentas existentes para o 1.9 para ele. 

O que posso te ratificar é que estamos no calcanhar dele é assim como fomos o primeiro case brasileiro a usar o HHVM + Varnish + Nginx + Redis + Sphinx creio se Deus quiser que também seremos o primeiro case a usar o Magento 2.0. Mas vai demorar... Então se for lançar o seu shop até final de 2016 recomendo usar a versão 1.9.1.1 ;)

Sobre o módulo para a versão 2.0 não sei se teremos, pois dependerá da pagar.me se vai ser interessante investir. Mas com certeza teremos conhecimentos técnicos para criá-lo. 

;)

Enviado do meu iPhone

**Comment by infrasoftbox** [comment]
Olá tudo bem? Foi lançada alguma versão para o magento 2.0?

**Comment by wandersonpereira** [comment]
Olá tudo bem?
Foi lançada alguma versão para o Magento 2.0?

**Comment by devdrops** [comment]
Olá @wandersonpereira!

No presente momento ainda não oferecemos suporte para Magento 2.* , sendo este módulo somente para as versões 1.7.* , 1.8.* e 1.9.*.

**Comment by Jonatasmz** [comment]
nada ainda da versão para magento 2.0?

**Comment by andreregino** [comment]
Alguma previsão do módulo para o Magento 2?

**Comment by leonampd** [comment]
Oi @Jonatasmz e @andreregino tudo bem?

Sou Leonam, aqui do time de dev do Pagar.me. O time já está trabalhando em um módulo para Magento 2 mas ainda não temos previsão para o lançamento.

**Comment by brunoconstantino** [comment]
Olá,

Alguma previsão do módulo para Magento 2?
Atualmente temos duas lojas em Magento 1.9 utilizando Pagar.me e gostaríamos de migrar para Magento 2.

@leonampd O módulo do Pagar.me para Magento 2 está no github para podermos ajudar?

**Comment by leonampd** [comment]
Oi @brunoconstantino tudo bem? Ainda não temos previsão para ter o módulo. Por questões estratégicas de negócio ele foi despriorizado.

**Comment by gumnet** [comment]
Estou trabalhando no desenvolvimento, me escreve no email gustavo@gum.net.br
