### ISSUE TITLE
Adicionar Valor de parcela mínima e Quantidade de Parcelas sem juros

### ISSUE THREAD

**Issue by thiagoprado88** [pagarme/pagarme-magento#10]
Para o módulo de checkout ficar perfeito falta adicionar um valor de parcela mínima e um campo para configurar quantas parcelas poderiam ser sem juros. Obrigado

**Comment by davirs** [comment]
isso já tem no módulo transparente fera... no checkout pagarme realmente não tem essa configuração pelo painel do magento.

lembrando apenas que parcela mínima é considerado ilegal e abusivo.. muito cuidado...

![screenshot_4](https://cloud.githubusercontent.com/assets/4355062/10081085/ac39f49e-62c9-11e5-820d-364ad2d16c4c.png)

**Comment by thiagoprado88** [comment]
Boa Tarde, mas eu não estou usando mais esse módulo porque ele estava dando problema na minha loja, inclusive os erros

Foram reproduzidos pelo João do pagar.me.

 

Por isso queria saber se tem como colocar isso no checkout pagarme pelo painel do magento.

 

 

Obrigado, mas se eu não me engano o abusivo é definir um valor mínimo para o cartão mas nas parcelas lembro que pode, mas de qualquer maneira vou consultar o

CDC.

 

Obrigado

 

De: davirs [mailto:notifications@github.com] 
Enviada em: quinta-feira, 24 de setembro de 2015 14:38
Para: pagarme/pagarme-magento
Cc: thiagoprado88
Assunto: Re: [pagarme-magento] Adicionar Valor de parcela mínima e Quantidade de Parcelas sem juros (#10)

 

isso já tem no módulo transparente fera... no checkout pagarme realmente não tem essa configuração pelo painel do magento.

lembrando apenas que parcela mínima é considerado ilegal e abusivo.. muito cuidado...

 <https://cloud.githubusercontent.com/assets/4355062/10081085/ac39f49e-62c9-11e5-820d-364ad2d16c4c.png> screenshot_4

**Comment by davirs** [comment]
ao definir um valor mínimo da parcela você já está definindo um valor mínimo no cartão...
o que você pode fazer como regra do negócio é setar número máximo de parcelas, juros etc...

nada te impede de colocar a parcela mínima... mas vai contra a lei....

**Comment by thiagoprado88** [comment]
Sim agora eu entendi o que eu queria fazer então é o seguinte, definir o valor máximo de parcelas sem juros e o restante deixar com

Juros, isso dá para fazer?

 

6 parcelas máximas, sendo 3 sem juros.

De: davirs [mailto:notifications@github.com] 
Enviada em: quinta-feira, 24 de setembro de 2015 15:59
Para: pagarme/pagarme-magento
Cc: thiagoprado88
Assunto: Re: [pagarme-magento] Adicionar Valor de parcela mínima e Quantidade de Parcelas sem juros (#10)

 

ao definir um valor mínimo da parcela você já está definindo um valor mínimo no cartão...
o que você pode fazer como regra do negócio é setar número máximo de parcelas, juros etc...

nada te impede de colocar a parcela mínima... mas vai contra a lei....

**Comment by davirs** [comment]
as opção que tem são essas... não sei se isso pode ser configurado pelo lado da pagarme.. 

![screenshot_5](https://cloud.githubusercontent.com/assets/4355062/10086001/68839db8-62e2-11e5-958c-05c6e63b2a5d.png)

**Comment by thiagoprado88** [comment]
Entendi é o que eu estou tentando falar com o joão do pagarme, pq no outro modulo tinha essas opções e funcionava( foi inclusive a primeira imagem que vc mandou).

Mas eu não uso mais ele. Pelos erros que lhe falei antes também.

 

Atualmente nem esse campo de juros a.m funciona, todos clientes compram sem juros. Ai tá complicado mas não posso desabilitar.

E ninguém me ajuda com isso.

 

 

 

De: davirs [mailto:notifications@github.com] 
Enviada em: quinta-feira, 24 de setembro de 2015 17:34
Para: pagarme/pagarme-magento
Cc: thiagoprado88
Assunto: Re: [pagarme-magento] Adicionar Valor de parcela mínima e Quantidade de Parcelas sem juros (#10)

 

as opção que tem são essas... não sei se isso pode ser configurado pelo lado da pagarme.. 

 <https://cloud.githubusercontent.com/assets/4355062/10086001/68839db8-62e2-11e5-958c-05c6e63b2a5d.png> screenshot_5
