### ISSUE TITLE
Manter num Padrão o Uso das Releases do SDK PHP do Pagar.me

### ISSUE THREAD

**Issue by devdrops** [pagarme/pagarme-magento#109]
## Contexto

Para não ter que editar o `composer.json` a cada vez que lançamos uma nova release do pagarme-php, podemos manter o composer.json, fazendo que sempre usemos as mais recentes versões.

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me 0.1.6
* PHP >= 5.4
* pagarme-php <= 3

## Passos para reproduzir

1. Executar `composer update`.
2. Ver que a última release de V3 está instalada com sucesso.

## Resultado esperado

A versão de pagarme-php sempre se mantém como a mais recente.

## Resultado atual

Ainda usamos a versão 3.1.*

## Posssível correção

Manter o arquivo `composer.json` com o padrão que aborde sempre as releases mais recentes.

**Comment by ricardotulio** [comment]
@devdrops fui instalar as dependências hoje e me veio a versão 3.0.3. Precisamos rever a forma de declarar essa dependência.
