### ISSUE TITLE
Dados de cartão perdem referência ao digitar CEP

### ISSUE THREAD

**Issue by filipedeschamps** [pagarme/pagarme-magento#11]
Parece que ao digitar um CEP, o DOM é renderizado novamente e isto faz perder a referência para os campos do cartão.

**Como reproduzir**

## 1) Carregar a página de checkout
Esta parte do DOM é impressa, até ai tudo bem.
![image](https://cloud.githubusercontent.com/assets/4248081/10047269/c8450d04-61e3-11e5-9440-8cec36142dbb.png)

## 2) Digitar o CEP
![image](https://cloud.githubusercontent.com/assets/4248081/10047306/ee0f77fe-61e3-11e5-9ac5-8bac8b41e305.png)

## 3) Após digitar o CEP
Esta parte do DOM é recarregado (e ai que o problema acontece)
![image](https://cloud.githubusercontent.com/assets/4248081/10047341/1e0c5bca-61e4-11e5-94bc-d0c82e6b7407.png)

## 4) Resultado final é não encontrar mais as informações do cartão
![image](https://cloud.githubusercontent.com/assets/4248081/10047363/3167beee-61e4-11e5-9092-a7ae1c28f16f.png)

## Detalhe importante
Se você sair da página, voltar (utilizando o endereço anterior já preenchido e sem forçar aquele refresh no DOM) e completar diretamente as informações do cartão, funciona corretamente.

Como está sendo feita a busca no client-side por estes itens? Ele busca uma única vez no carregamento inicial da página?

**Comment by eneiasramos** [comment]
Olá @filipedeschamps ! Tudo bem?

O seu módulo pagarme está atualizado?

Qual a versão do OSC que você está utilizando?
Ela contém os patches que sugerimos?

https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro/commit/de0fe40439960b621e33b94ac17188a7371b7b3e
https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro/commit/4dae6f50d48f150f99fc1b828497eccb480bfe40

Abraços!

**Comment by lhcarvalho** [comment]
Olá @eneiasramos, apenas para esclarecimento, estamos falando do mesmo problema que comentei no outro post. O Filipe é o nosso suporte na equipe do Pagar.me. O site em questão é o lanaesquina.com.br. A versão do OSC é a última. Não tinha conhecimento desses patches. Vou checar se estão instalados. Se não estiverem, vou instalar e aviso aqui o resultado. Obrigado,

**Comment by lhcarvalho** [comment]
@eneiasramos, acabei de checar.
Os dois patches já estavam instalados.

**Comment by filipedeschamps** [comment]
@lhcarvalho obrigado pelo retorno aqui na issue. Irei fechar aquele chamado para nos centralizarmos aqui, combinado? Pois com isto, o @eneiasramos terá todos os dados junto conosco

**Comment by lhcarvalho** [comment]
combinado, @filipedeschamps !
@eneiasramos , vc já deve estar ciente, mas tem outras pessoas com o mesmo erro... esse aqui, por exemplo, é outro caso: https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/issues/149
Vou tentar checar mudando o template para o RWD, como sugerido e posto aqui se teve resultado.

**Comment by lhcarvalho** [comment]
@filipedeschamps e @eneiasramos, mesmo com o tema RWD não funcionou.
Vou deixar este tema ativado por 1hora, caso queiram testar algo.
Estou utilizando este produto para o teste:
http://lanaesquina.com.br/colchao-solteiro-ortobom-exclusive-com-ortopillow-e-molas-bonnel-30-x-88-x-188-cm
Tks,

**Comment by lhcarvalho** [comment]
Alguma luz no fim to túnel sobre esse problema?

**Comment by eneiasramos** [comment]
Olá @lhcarvalho ! Tudo bem?

A lojanaesquina.com.br está com vários erros de JS no checkout:

![lanaesquina-pagarme-osc-js-erros](https://cloud.githubusercontent.com/assets/2862728/10118099/88011f6c-6445-11e5-9da9-62b72f502d59.png)

É necessário eliminar esses erros antes de continuar os testes do módulo Pagarme e OSC juntos.

No aguardo, obrigado!

**Comment by lhcarvalho** [comment]
Obrigado pela dica Eneias,

Vou dar uma checada nesses erros e te aviso quando tiver resolvido eles. 

Abs!

Enviado do meu iPhone

**Comment by lhcarvalho** [comment]
A proposito,

Voce conhece alguma loja (pode ser só de temo ou teste) que tenha o OSC e o modulo pagar.me rodando bem, sem customizacoes?

Queria dar uma olhada pra ver como o formulario deveria se comportar... Agora q você me avisou desses erros, receio que tenha outros problemas no checkout escondidos...

Abs!

Enviado do meu iPhone

**Comment by lhcarvalho** [comment]
@eneias, você que conhece bem os plugins do OSC e do Pagar.me, veja se consegue me dar uma 'luz' sobre o que pode estar acontecendo de errado:

Todos esses erros de JS somem qnd eu desabilito o OSC e deixo apenas a forma de pgto 'cash on delivery' ativa. (fica apenas um alerta que o metodo getPreventDefault() deve ser substituido pelo defaultPrevented, mas acho que esse alerta não deve ser relevante, correto?)

Quando ativei apenas o OSC, o erro do 'MegaMenu.bar' e o '$j(...)' voltaram.
Ao ativar o OSC e o Pagar.me (boleto, CC e checkout) não apareceu nenhum erro novo, ficando apenas estes dois.

Voltei o tema para o RWD e esses dois erros de JS sumiram (aparecendo apenas dois alertas que ACHO não serem relevantes para essa situação)
![checkoutrwd](https://cloud.githubusercontent.com/assets/14809943/10118881/2262eb52-645b-11e5-971e-6f969f3426b0.PNG)

Fiz um teste rápido, e me pareceu que o checkout funcionou adequadamente. (ainda não tive tempo de checar todas as possiveis situacoes, mas a básica funcionou).

Estou concluíndo que é uma incompatibilidade do OSC com o meu template (http://themeforest.net/item/ultimo-fluid-responsive-magento-theme/3231798). Você concorda com esta conclusão?

Pela sua experiência, esse tipo de erro é algo que te parece relativamente tranquilo de eu arrumar por aqui?

Tks!

**Comment by lhcarvalho** [comment]
@eneiasramos e @filipedeschamps, achei um erro novamente no RWD... Desculpem a confusão de "agora esta funcionando, agora não esta mais, voltou, parou de novo..." heheh

Tinha ficado incomodado porque eu já havia testado no RWD encontrado um erro.
Ai vai um print do erro:
![errocheckoutrwd](https://cloud.githubusercontent.com/assets/14809943/10118920/e70f057a-645c-11e5-828e-b461965ba18d.PNG)

O erro acontece quando eu clico no botão 'Finalizar' ainda com o campo de texto 'CVV' selecionado, como demonstro no video abaixo. Se eu clicar fora da tela, ou der um 'tab' ANTES de clicar em finalizar, fecha normalmente...
http://screencast.com/t/SZxBBaY9aMjZ

Vou deixar o site no RWD, para retirar os erros de JS
A home não esta funcionando. Entrem direto em um produto:
http://lanaesquina.com.br/colchao-solteiro-ortobom-exclusive-com-ortopillow-e-molas-bonnel-30-x-88-x-188-cm

Abs,

**Comment by eneiasramos** [comment]
Olá @lhcarvalho ! Tudo bem?

Fiz alguns ajustes para a validação de cartão de crédito usando o OSC:

https://github.com/eneiasramos/pagarme-magento/commit/b67e7b61a2a789cae27082aa4fa166923484c5ca

Abçs!

**Comment by lhcarvalho** [comment]
Ótimo!

Obrigado @eneiasramos.
Agora está funcionando.

Abs!

**Comment by filipedeschamps** [comment]
Show de bola @lhcarvalho, obrigado pelo retorno!

@eneiasramos muito obrigado por todo auxílio, matou a pau :+1:

**Comment by lhcarvalho** [comment]
@eneiasramos e @filipedeschamps,

Infelizmente acho que tinha testado muito mal o checkout depois da ultima correção... continua com problema... tentei ir mais a fundo pra tentar identificar a fonte do problema, mas não consegui.

A única coisa que consegui corrigir foram os erros de script que estavam no meu checkout (obrigado pela dia, Eneias), que ocorriam por JQuery Conflict. Agora já esta tudo certo sobre isso e não aparece nenhum erro no console.

O problema continua acontecendo quando tentamos pagar com um endereço novo.
Parece que, depois que digitamos o CEP, o script que é acionado com as alterações das caixas de input do formulario do cc não roda mais... nao consegui entender porque...

Alguma luz?

**Comment by lhcarvalho** [comment]
@eneiasramos,

Tem 2 bugfixes que vc fez que acho que não entraram no master do OSC:

https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro/commit/de0fe40439960b621e33b94ac17188a7371b7b3e

e

https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro/commit/4dae6f50d48f150f99fc1b828497eccb480bfe40

Você acha que vale a pena baixar eles? Ou não estão relacionados?

**Comment by lhcarvalho** [comment]
Eita... coloquei esses dois fixes...
Esse problema sumiu ( @eneiasramos , peça lá pro @deividison acrescentar isso no master... )
O CardHash esta sendo gerado.

Agora apareceu outro problema:
Logo depois que digito o 3o digito do CVV, roda um script... até ai tudo bem...
Acho que o problema é que o input do CVV continua ativo, mesmo depois de terminar esse script...
Desta forma, quando eu clico no botão 'finalizar', acho que o mesmo script roda novamente (por causa do evento 'blur'???), desta forma a ação do botão em si é anulada.
Não causa nenhuma mensagem de erro. Se clicar novamente do botão 'finalizar', fecha o pedido normalmente.
O problema é que o cliente pode achar que é só uma demora do site e ficar 'esperando' algo acontecer... (aconteceu isso com meu CFO que entende de ecommerce, imagina com um consumidor leigo! heheh)
Esse deve ser fácil de resolver, não? Acho que se tirar o evento 'onblur' do input do  CVV deve funcionar... como o pagamento já é salvo ao digitar o 3o dígito, não precisa do evento no 'blur'? Certo?

Desculpa novamente a confusão de 'esta funcionando', 'não esta mais'...
E se eu tiver falando alguma besteira muito grande, também releve... eu não sou programador...

Valeu!

**Comment by lhcarvalho** [comment]
@eneiasramos,
inclui a linha abaixo no script que vc havia inserido no cc.phtml, após o 'if (this.value.length > 2) fireEvent(this, 'blur');' 

if (this.value.length > 2) this.blur();

Não sei se é a melhor solução, mas parece que funcionou dessa vez...

vou continuar testando por aqui...

**Comment by eneiasramos** [comment]
@lhcarvalho fiz um ajuste para esse problema:

https://github.com/eneiasramos/pagarme-magento/commit/4b98e476ba35a82e8dfb3178aca4b54cb330c956
