### ISSUE TITLE
Checkout Pagar.me - Testes de Aceitação para Configurações no Admin

### ISSUE THREAD

**Issue by devdrops** [pagarme/pagarme-magento#114]
## Contexto

Hoje temos um [cenário](https://github.com/pagarme/pagarme-magento/blob/v2/tests/acceptance/features/configure.feature) de testes com Behat para as configurações no Admin do Magento. Em #113, @xduh e eu começamos uma discussão sobre a validade desses testes e seu efeito no módulo como um todo, pois parecem que testamos somente a funcionalidade do Magento em si, o que não cabe a nós realizar neste projeto. Decidimos então questionar se vamos manter tais testes e/ou continuar a produzir esse modelo.

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me 2.0.0
* PHP 5.4

## Resultado esperado

Definir a validade de manter ou não tais tipos de testes.

## Resultado atual

Posição definida a respeito desses testes (manter ou não).

## Posssível correção

Caso os testes sejam necessários para manter uma configuração especial para a sequencia dos demais testes, podemos mover para um Provider ou para um setUp inicial e assim manter a funcionalidade.

**Comment by devdrops** [comment]
No meu ponto de vista, acredito que não é necessário manter esses testes, já que pouco servem para validar o módulo em si (validando somente a existência do campo).

**Comment by ricardotulio** [comment]
@devdrops esses testes foram criados pois não há como testar os arquivos xml de configuração (ou há? seria uma alternativa. Já houve casos em que admin inteiro do Magento quebrou por alterar o `config.xml` ou adicionar um campo pelo arquivo `system.xml`.

De qualquer forma, acho importante garantir que após qualquer alteração nesses arquivos, o admin continue funcionando, pois isso pode literalmente parar uma empresa.

**Comment by devdrops** [comment]
@ricardotulio certo, eu não tinha conhecimento desse ponto crítico e faz todo o sentido dentro do que colocamos de testes como  requisitos. Muito obrigado por trazer mais esse conhecimento.

Sabemos se há outra forma possível para manter testes na configuração que não seja testando a funcionalidade do Magento em si? Se sim, podemos explorar essas formas ao invés de fazer com testes na mecânica de persistência.
