### ISSUE TITLE
Checkout Pagar.me - Separar Juros entre Transações de Cartão de Crédito e Boleto

### ISSUE THREAD

**Issue by devdrops** [pagarme/pagarme-magento#129]
## Contexto

Hoje, o valor de `interest_rate` é salvo na tabela `pagarme_transactions` independente do tipo de transação, a saber, cartão de crédito ou boleto. Isso faz com que juros sejam aplicados de forma incorreta para armazenar na tabela (por exemplo, o valor de `interest_rate` destina-se somente à transações de cartão de crédito).

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me 2.0.0

## Passos para reproduzir

1. Acesse o painel administrativo do Magento
2. Clique em `Sistema > Configurações > Métodos de Pagamento`
3. Encontre a sessão `PagarMe - Configurações`
4. Insira dados para taxa de juros (`interest_rate`)
5. Salve a configuração
6. Realize o processo de compra pelo Checkout Pagar.me, com cartão de crédito, dentro das condições de juros configuradas em 4
7. Valide que os juros foram aplicados na transação
8. Realize um novo processo de compra pelo Checkout Pagar.me, com boleto
9. Valide que os juros não foram aplicados na transação 

## Resultado esperado

Juros de cartão de crédito são aplicados somente para transações por cartão de crédito. 

## Resultado atual

Juros são persistidos em `pagarme_transaction` independente do tipo de transação.

## Posssível correção

No ato de persistir os dados em `pagarme_transaction`, o valor configurado para taxa de juros é considerado, independente do tipo de transação (cartão de crédito ou boleto).

**Comment by xduh** [comment]
Acho que o 'interest_rate' pode ser utilizado para armazenar o desconto do boleto, provavelmente seria necessário alterar o nome da coluna, de modo que possa representar juros/desconto de acordo com o sinal.

**Comment by murilohns** [comment]
Acredito que não tenhamos mais esse problema.
Atualmente apenas em transações de cartão de crédito o campo `rate_amount` é preenchido.
