### ISSUE TITLE
Problema com o método addCreditCardInterestFee na model Observer

### ISSUE THREAD

**Issue by thufik** [pagarme/pagarme-magento#134]
## Contexto

Plataforma fechada de um parceiro está enfrentando problemas para gerar boleto bancário. Ao clicar em gerar o boleto é retornado um erro referente a inexistência do método  `addCreditCardInterestFee`

## Ambiente

* Magento C(Versão não especificada)
* PHP 5.5

## Passos para reproduzir

1 - Vá com um produto simples até a página de finalização;
2 - Tente finalizar um pedido com o boleto pagar.me;

## Resultado atual

Aparecerá o seguinte erro no Network da página:

```php
Method "addCreditCardInterestFee" is not defined in "Inovarti_Pagarme_Model_Observer"
```

**Comment by wilsonbrito** [comment]
Bom dia, 

A versão do magento é 1.9.2 

Qualquer dúvida estou a disposição 

Att

**Comment by petriuslima** [comment]
@wilsonbrito fiz uma alteração na branch `fix-observer-method-not-found` para correção do problema, poderia validar baixando essa nova [branch](https://github.com/pagarme/pagarme-magento/tree/fix-observer-method-not-found)? **Não se esqueça de limpar o cache do magento para uma avaliação confiável**.

Estarei criando o PR para a master mas aguardarei sua confirmação de que o erro foi corrigido em seu ambiente.
