### ISSUE TITLE
Checkout Pagar.me - Carregar pagarme.js somente na Rota de Checkout

### ISSUE THREAD

**Issue by devdrops** [pagarme/pagarme-magento#137]
## Contexto

Hoje, por configuração, carregamos o arquivo pagarme.js em todas as rotas, sem ter a necessidade disso.

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me 2.0.0

## Passos para reproduzir

1. Acesse qualquer rota da loja
2. Valide que o arquivo pagarme.js aparece carregado

## Resultado esperado

O arquivo pagarme.js seja carregado somente na rota de checkout.

## Resultado atual

Arquivo carregado em todas as rotas, sem necessidade disso.

## Posssível correção

Alterar o `pagarme_checkout.xml` para que o arquivo pagarme.,js seja carregado somente na rota relacionada ao `checkout_onepage`

**Comment by henriquekano** [comment]
Foi adicionado um ifconfig em referência à configuração `enabled` do modal: https://github.com/pagarme/pagarme-magento/blob/v2/app/design/frontend/base/default/layout/pagarme/pagarme_modal.xml#L5
