### ISSUE TITLE
Checkout Pagar.me - Salvar em pagarme_transaction mais Informações sobre as Transações 

### ISSUE THREAD

**Issue by devdrops** [pagarme/pagarme-magento#138]
## Contexto

Para atender detalhes de exibição de informação para o lojista e para o consumidor, é preciso que mais informações de cada transação sejam exibidas, como o método de pagamento, valor dos juros e URL do boleto por exemplo.

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me 2.0.0

## Passos para reproduzir

1. Acesse o painel administrativo do Magento
2. Clique em `Sales > Orders` e clique em qualquer Order cujo pagamento foi realizado com o Checkout Pagar.me
3. Validar que há mais informações exibidas nos detalhes da Order

## Resultado esperado

Informações como método de pagamento, valor dos juros e URL do boleto são exibidas na tela de Order.

## Resultado atual

Recurso ainda não implementado.

## Posssível correção

Adição de mais informações na tabela `pagarme_transaction`.

**Comment by leonampd** [comment]
@devdrops parte do que é proposto nessa issue foi implementado em #323 e #271. Vou fechar essa issue mas fica à vontade pra reabrir se necessário ok?
