### ISSUE TITLE
Dúvidas gerais

### ISSUE THREAD

**Issue by filipedeschamps** [pagarme/pagarme-magento#14]
@eneiasramos tudo bem? Tenho algumas dúvidas gerais sobre o módulo/integração com Magento. Você poderia me auxiliar? Breves respostas já seriam mais do que o suficiente :)

1) O módulo do Pagar.me permite venda e cadastro para Pessoa Jurídica (validando o CNPJ)? Se não, será necessário um módulo adicional?

2) Neste caso que uma venda será para uma empresa, você sabe se o boleto que vai ser gerado terá o CNPJ do comprador?

3) Você sabe se o módulo para Magento já oferece os mesmos recursos do One Step Checkout?

4) Você sabe quais são os status que um pedido pode passar? O módulo já cria isto automaticamente ou é necessário cadastrar (e atualizar) manualmente?

5) Os emails transacionais precisam ser configurados manualmente?

6) É gerado algum aviso automático para os boletos que estão prestes a vencer?

7) Você sabe me dizer se há algum recurso de venda assistida ou televendas?

8) É possível fazer o cancelamento de uma compra por cartão diretamente pelo Magento? Mesmo o cancelamento não sendo no mesmo dia da compra?

Qualquer ajuda que puder me dar ficarei eternamente agradecido meu caro! :+1:

**Comment by filipedeschamps** [comment]
Mais uma pergunta :)

9) É possível alterar a cor do botão que abre no Checkout?

Muito obrigado!

**Comment by devdrops** [comment]
Olá @filipedeschamps! Vamos lá:

> 1) O módulo do Pagar.me permite venda e cadastro para Pessoa Jurídica (validando o CNPJ)? Se não, será necessário um módulo adicional?

Hoje o módulo não realiza validação para CNPJ, sendo necessário usar um módulo externo que faça essa validação.

> 2) Neste caso que uma venda será para uma empresa, você sabe se o boleto que vai ser gerado terá o CNPJ do comprador?

Partindo do princípio de que o valor para o documento do comprador será contido no boleto, podemos dizer que sim; porém, tendo em mente a resposta da pergunta 1), tal funcionalidade não está disponível neste momento.

> 3) Você sabe se o módulo para Magento já oferece os mesmos recursos do One Step Checkout?

O módulo em si se responsabiliza pela integração de pagamento, cabendo à outros módulos a responsabilidade por outros recursos.

> 4) Você sabe quais são os status que um pedido pode passar? O módulo já cria isto automaticamente ou é necessário cadastrar (e atualizar) manualmente?

O módulo não altera/acrescenta novos status, ou seja, o pedido segue os mesmos status do Magento.

> 5) Os emails transacionais precisam ser configurados manualmente?

Sim.

> 6) É gerado algum aviso automático para os boletos que estão prestes a vencer?

Não.

> 7) Você sabe me dizer se há algum recurso de venda assistida ou televendas?

Não.

> 8) É possível fazer o cancelamento de uma compra por cartão diretamente pelo Magento? Mesmo o cancelamento não sendo no mesmo dia da compra?

Sim. Para isso, segue o passo a passo de Refund oferecido pelo Magento. No entanto é preciso acompanhar o status da transação na dashboard do Pagar.me.

> 9) É possível alterar a cor do botão que abre no Checkout?

Não.

Caso tenha mais dúvidas, por favor não deixe de entrar em contato conosco :wink:
