### ISSUE TITLE
Dúvida sobre internacionalização

### ISSUE THREAD

**Issue by petriuslima** [pagarme/pagarme-magento#151]
## Contexto

Na versão 2 do plugin para magento encontrei a seguinte linha [aqui](https://github.com/pagarme/pagarme-magento/blob/9fcbf00190290745a1d6521e3fae1d2e57dad6be/app/code/community/PagarMe/Core/Model/Postback.php#L125).

```php
$order->setState(Mage_Sales_Model_Order::STATE_PROCESSING, true, "pago");
```

Isso não tem problema pra internacionalização? Não deveríamos traduzir através do arquivo de tradução?

**Comment by ricardotulio** [comment]
@petriuslima esse é um texto de comentário que deveria ser trocado ou deixado em branco.

**Comment by ricardotulio** [comment]
Resolvido no PR #182
