### ISSUE TITLE
Checkout Pagar.me - Correção para dados de Customer

### ISSUE THREAD

**Issue by devdrops** [pagarme/pagarme-magento#156]
## Contexto

Durante testes manuais, verificamos que a forma de obter os dados do Customer para preencher o formulário do Checkout Pagar.me apresentavam o seguinte erro:

```
magento_1   | [Thu Mar 30 20:10:54 2017] [error] [client 172.18.0.1] PHP Fatal error:  Call to a member function getTelephone() on a non-object in /var/www/app/code/community/PagarMe/Checkout/Block/Form/Checkout.php on line 109, referer: http://magento/index.php/checkout/onepage/
```

Isso acontecia antes da execução dos testes, que já cadastravam o Customer por padrão.

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me 2.0.0

## Passos para reproduzir

1. Acesse a loja do Magento
2. Siga o procedimento de compra: adicionar produto no carrinho, seguindo para a tela de checkout.
3. Ao chegar no momento de preencher os dados de pagamento, validar o redirecionamento para a tela do carrinho e a mensagem de erro nos logs

## Resultado esperado

Os dados do Customer são preenchidos no formulário do Checkout Pagar.me e a compra continua sendo realizada.

## Resultado atual

Com o erro descrito acima, não é póssível realizar a compra.

## Posssível correção

Alterar a origem dos dados do Customer: ao invés de buscar do banco de dados, buscar da sessão atual.

**Comment by ricardotulio** [comment]
@devdrops você checkou a issue #155?
