### ISSUE TITLE
Checkout Pagar.me - Adicionar Metadata no Ato de Captura

### ISSUE THREAD

**Issue by devdrops** [pagarme/pagarme-magento#166]
## Contexto

Para manter o rastreio de informação das Orders feitas na loja, queremos adicionar dados extras para rastrear as informações com mais facilidade.

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me 2.0.0

## Passos para reproduzir

1. Acesse a dashboard do Pagar.me
2. Use os filtros de pesquisa das transações para encontrar pela referência do metadata.

## Resultado esperado

A busca por informações das transações fica mais fácil para o usuário.

## Resultado atual

Recurso ainda não implementado.

## Posssível correção

Adicionar metadata no ato da captura, em `PagarMe_Checkout_Model_Checkout`.

**Comment by henriquekano** [comment]
Já possui: https://github.com/pagarme/pagarme-magento/blob/v2/app/code/community/PagarMe/Modal/Model/Modal.php#L133.
