### ISSUE TITLE
Problemas em Transações Aprovadas no Cartão de Crédito

### ISSUE THREAD

**Issue by iurimedeiros** [pagarme/pagarme-magento#167]
Olá amigos, boa tarde!

Após realizar a atualização do módulo Pagar.me para a última versão, identificamos que não está retornando o status de pagamento aprovado, conforme configurado no módulo para pagamentos aprovados, deveria ser alterado o status do pedido para processando, algo que não é feito nesta última atualização e que nós não conseguimos faturar o pedido devido a não liberação desta função no menu superior.

Vale lembrar que nós aplicamos a atualização do módulo do Pagar.me em nossas duas operações de e-commerce e o erro ocorre em ambos, sendo que antes funcionava 100%.

Nós utilizamos de um Cloud Server robusto para rodar as nossas aplicações dos sites www.machinemotors.com.br e www.visualsurf.com.br, segue abaixo as informações do servidor.

* Magento Community 1.9.2.4
* Módulo Pagar.me 0.1.6
* Servidor Linux Centos6
* PHP 7.0
* Apache 2.4.6
* MySQL 5.0.12
* Infos: http://visualsurf.com.br/info.php (mesmo server do printscreen anexado)

![pagarme-problem](https://cloud.githubusercontent.com/assets/11665895/24727587/e86a240e-1a2c-11e7-96b7-a2159fa6475a.jpg)

**Comment by ricardotulio** [comment]
Boa tarde @iurimedeiros, tudo bem?

Esse problema ocorre com todos os novos pedidos?

**Comment by iurimedeiros** [comment]
Fala @ricardotulio tranquilo? Cara isso ocorre somente com todos os pedidos feitos por cartão de crédito, os que são por boleto bancário são faturados normalmente quando é identificado o pagamento. Abraço!

**Comment by iurimedeiros** [comment]
Eai @ricardotulio alguma posição a respeito deste problema que estou enfrentando? Isso já se estende a mais de mês e está me gerando um transtorno enorme. Abraço!

**Comment by luiz2000web** [comment]
Bom dia pessoal! Vocês sabem se foi corrigido esse bug, estou enfrentando o mesmo problema

**Comment by iurimedeiros** [comment]
Olá @luiz2000web, tudo bem? Cara sinto informá-lo de que o suporte do Pagar.me é péssimo, eles te vendem o setup para usar a ferramenta mas não garantem suporte para integrações que são fornecidas por eles mesmos.

Dai em uma última tentativa tentamos solução através deste canal ao qual ficamos reféns da boa vontade dos desenvolvedores que em grande parte são terceirizados.

Lamentável o descaso desta empresa!

**Comment by luiz2000web** [comment]
Olá @iurimedeiros tudo certo! nossa que chato isso, esse erro acontece somente quando configuro a transação com async (que é a melhor opção). Se deixo desativado quando a transação demora um pouco mais para processar o Magento retorna como erro redireciona para home e não gera pedido. Porem quando vou ver no pagarme a transação tá aprovada! tá osso!!! Vlw pelo retorno! vou tentar brigar mais um pouco aqui

**Comment by rodrigoPgSup** [comment]
Olá @iurimedeiros @luiz2000web , pedimos desculpas por toda a demora neste caso para vocês. Sou da equipe de suporte e já estamos investigando uma maneira de resolver isso, e o quanto antes 
retorno com uma posição para vocês. E outro ponto importante é que 100% dos nossos desenvolvedores são funcionários da Pagar.Me, não trabalhamos com terceiros.

**Comment by iurimedeiros** [comment]
Olá @rodrigoPgSup, estranho que foi só eu me posicionar a respeito do total descaso da empresa Pagar.me que a resposta veio logo em seguida né?

O fato da equipe de desenvolvedores ser 100% da Pagar.me é algo ainda mais alarmante pois demonstra a total falta de interesse em resolver os problemas enfrentados e não é porquê estou pegando no pé de vocês, prova disso é a abertura desta issue no dia 05 de abril e o meu problema foi informado via ticket no começo de março e a única resposta que obtive foi da isenção de responsabilidade.

É sempre muito interessante tornarmos público problemas como estes para que outros empresários não venham a cometer o erro de contratar uma empresa que trata seus clientes desta forma ou para que caso o façam, já façam sabendo como que as coisas funcionam.

Deixo aqui registrado para todos possam se inteirar do assunto e deixo claro que sou um cara muito justo, somente fiz isso após cerca de 3 tentativas de conciliação.

Sem mais,
Iuri Medeiros
Equipe Visual Surf

**Comment by iurimedeiros** [comment]
Oi @ricardotulio e @rodrigoPgSup, tudo bem? Hoje estava tentando entender de onde parte o problema do módulo ao entrar na aba fatura dentro do pedido e identificar que o pagamento consta como Pendente, cliquei sobre a fatura e dentro dela tem a opção Capturar ao qual ao ser clicada retorna a mensagem "Transação com status 'paid' não pode ser capturada." por este motivo acho que deve haver alguma divergência do status que o pagarme está retornando com o status ao qual o módulo está esperando.

Peço que caso ainda não tenham idéia de onde possa partir o problema, vejam se não pode ser isso realmente. Abraço!

**Comment by ricardotulio** [comment]
Bom dia @iurimedeiros, já recebemos esse problema do suporte, e provavelmente está relacionado ao recebimento de postback. 

Mas de qualquer forma, já estamos de olho nesse problema, e obrigado pela dica :)


Abraço!

**Comment by regnolasco** [comment]
@iurimedeiros ,
Acabei de contratar a pagarme, e estou com o mesmo problema, o suporte está a mais de 1 me olhando o erro? É isso mesmo?
E se o desenvolvimento é 100% dentro da pagarme, pq no modulo aparece o logo da inovarti?
Por favor, me nos respondam com o erro corrigido.
@ricardotulio @rodrigoPgSup aguardo posicionamento.

**Comment by iurimedeiros** [comment]
Oi @regnolasco tranquilo?

Cara como tu pode ver é um total descaso da empresa, esta issue foi aberta no dia 5 de abril, já vamos para 2 meses da abertura da issue e a quase 3 meses que informei o problema a Pagar.me e não é feito nada a respeito!

A empresa Pagar.me contratou a Inovarti e a Gamuza na época para que desenvolvessem os módulos para Magento, acredito eu que tenham tentado criar uma equipe interna de desenvolvimento para se desligar das empresas informadas e o resultado é este... péssimo suporte!

PS: Vai nas configurações do módulo do Pagar.me no Magento e desativa o ASync, isso resolve parcialmente o problema que estamos enfrentando!

Abraço,
Iuri Medeiros
Equipe Visual Surf

**Comment by regnolasco** [comment]
Fala @iurimedeiros ,
Desativei.
Passei tudo isso pro meu gerente de contas la.
E pra outros contatos que eu tenho aqui. Vamos ver segunda o que acontece.
Se tiver outra opcao de gateway que funcione, ja me avisa. Pq esse já é o sexto que estou tentando.
Valeu pela dica.
Abraço,
Reginaldo

**Comment by regnolasco** [comment]
Boa Tarde @iurimedeiros e @rodrigoPgSup ,
Fiz a atualização do modulo conforme orientado pelo pessoal e ate o momento nao funcionou.
Destaco que após a desativação do slynk, os pedidos pararam de dar problema com os status e estao entrando normalmente.
Porem ficamos com alguns pedidos travados com o status de revisao de pagamento e esses ainda nao foram corrigidos.
Att,
Reginaldo

**Comment by murilohns** [comment]
Olá @iurimedeiros e @regnolasco, o problema ainda está ocorrendo?

**Comment by murilohns** [comment]
Olá @iurimedeiros , irei fechar essa issue, mas sinta-se a vontade para reabrir caso precise.
