### ISSUE TITLE
BUG - Transação mudando status para paga indevidamente

### ISSUE THREAD

**Issue by rfviolato** [pagarme/pagarme-magento#17]
Nos deparamos com o seguinte bug:

Um usuário do módulo detectou que ocorreram algumas vezes mudanças de status indevidos de transação constando como pagas, sendo que somente uma foi paga de fato.

Ambas as transações foram de boleto, criadas pelo mesmo usuário. Chequei os postbacks das transações e somente a transação paga disparou postback, enquanto a que não foi paga não disparou postback (como deveria mesmo)

Fico a sua disposição para te fornecer os dados que você precisar para entender e solucionar o problema.

**Comment by jgabrielfaria** [comment]
@rfviolato pode pegar as credenciais (acesso FTP e painel admin) do site e enviar para eneias@gamuza.com.br com o link para essa issue?

**Comment by rfviolato** [comment]
@eneiasramos Passei os dados por email ;)

**Comment by eneiasramos** [comment]
@rfviolato qual a URL da loja?

**Comment by SocialGroups** [comment]
Efetuamos diversas correções no nosso módulo incluindo alguns problemas com atualizações de status, por favor atualize o módulo para a sua última versão disponível no master.
