### ISSUE TITLE
Lentidão e Travamento na página do checkout

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#172]
## Contexto

Bom dia pessoal. Alguns de meus clientes estão encontrando problemas no checkout, decorrentes do bloqueio da página. O Pagar.me bloqueia a página (aguarde...), até o término do carregamento dos arquivos. Mas eventualmente o aviso não sai da tela, interrompendo o fluxo de compra. Percebi esse comportamento principalmente em conexões lentas. Fiz alguns testes, monitorando o carregamento dos arquivos no firebug; e, as vezes, mesmo após o carregamento completo, o aviso continuava. Percebi que depois de uns 30s, se o aviso permanecer, não adianta esperar. Só recarregando a página.

## Ambiente

* Magento Community 1.9.3.0
* Módulo Pagar.me 0.1.6
* Servidor Linux Ubuntu 16.04.1 LTS
* PHP 7.0.8
* Apache 2.4
* MySQL 5.6.27
* Redis 3.0.6

## Passos para reproduzir

1. Configure uma conexão lenta (exemplos: rotear 3G do celular; baixar algo pesado; assistir vídeo 4k)
2. Acesse a página de Finalização do Pedido (checkout/onepage/)

## Resultado esperado

A tela exibe um aviso _Por favor aguarde..._ por um breve instante, e então mostra a página de checkout.

## Resultado atual

A tela (eventualmente) exibe um aviso _Por favor aguarde..._, e permanece assim por 3, 4, 5 min.

## Posssível correção

Sugiro adicionar um script de timeout, para recarregar a página, caso o bloqueio permaneça, após um tempo predeterminado (ex.: 40 segundos).
E acho que ajudaria, se colocassem todos os arquivos necessários no próprio módulo, sem a necessidade de carregar arquivos externos como `pagarme.min.js` ou `easyXDM.js`.

## Screenshots

![image](https://cloud.githubusercontent.com/assets/13813964/24910078/f0e0e824-1e9c-11e7-88dc-f89c86932f26.png)

**Comment by rafaelpatro** [comment]
Correção sugerida:

_skin/frontend/base/default/pagarme/js/checkout.js_

```php
function pagarmeShowLoader ()
{
    $("pagarme-overlay").setStyle({ height: pagarmeDocumentHeight() + "px" });
    $("pagarme-overlay").show ();
    $("pagarme-mask").show ();
    refreshExpired = window.setTimeout(function(){
        location.reload();
    }, 40000);
}

function pagarmeHideLoader ()
{
    window.clearTimeout(refreshExpired);
    $("pagarme-mask").hide ();
    $("pagarme-overlay").hide ();
}
```

**Comment by rafaelpatro** [comment]
Esse problema tem sido bem mais frequente hoje, após a manutenção.

**Comment by murilohns** [comment]
@vgsmith consegue dar uma olhada nesse problema?

**Comment by CajuCLC** [comment]
@rafaelpatro, estes arquivos que estao abrindo estao em seu servidor? Ja pensou em colocar em um CDN?
Utilizo o modulo da pagar.me em duas lojas com CloudFlare e nao temos este problema. Chegamos a ter antes quando nao tinha CDN, sei que isto seria somente um band aid para o problema, mas ajudaria.

**Comment by rafaelpatro** [comment]
Pois então, os arquivos que mencionei são carregados de um servidor do Pagar.me. Esses arquivos **não estão** disponíveis na extensão.

Obrigado pela sugestão @CajuCLC. Mas assim... reportei isso há quase um ano. E, não sei se foi minha correção, mas não estou mais passando por este problema. Vou até fechar aq a issue. Mas deixo a sugestão de manter no repositório todos os arquivos necessários ao funcionamento do módulo.

P.S.
@CajuCLC, há alguns meses implementei o HTTP/2 no host da loja. Então talvez essa mudança tenha solucionado o caso multiplexando os arquivos, e deixando espaço para mais conexões, assim como o CDN faria.

**Comment by rafaelpatro** [comment]
Reabrindo...
![image](https://user-images.githubusercontent.com/13813964/35925853-e509ac5c-0c0d-11e8-8382-f42ae19ab294.png)

**Comment by jonatasmaxi** [comment]
Ola @rafaelpatro tudo bom?

Meu nome é Jonatas e faço parte da equipe de suporte técnico do Pagar.me. 

O status_code 304, indica que não há necessidade de retransmitir a requisição de recursos. É uma implícita redireção para o recurso em cache. Este está relacionado com o resultado obtido na execução do condicional  if (modified_since). Tivemos um caso durante esta semana, de um cliente que havia realizado algumas otimizações de cache e logo depois este erro começou a ser mostrado a ele. 

Tentei replicar o problema em meu ambiente, porém, não obtive sucesso.

Vocês realizaram alguma modificação no sistema de vocês recentemente, principalmente, modificações que possam impactar diretamente como recursos no cache são carregados? 

Este problema também só ocore em conexões lentas? 

Fico no aguardo.

**Comment by rafaelpatro** [comment]
@jonatasmaxi, obrigado pelo retorno.

Sim, instalei [este módulo PWA](https://github.com/rafaelpatro/magento-meanbee-pwa), que realiza cache de alguns recursos. Ficou ativo por alguns dias, e impactou muito negativamente nas vendas, devido a este problema com a extensão do Pagar.me. Por isso acabei desativando o módulo PWA.

Tenho outras formas de pagamento que funcionaram normalmente com o _service worker_. Percebi que somente o Pagar.me requer o carregamento de arquivos externos, durante o checkout. E eventualmente esses arquivos não carregam por completo. Ou talvez até carregam, mas por algum motivo não desbloqueiam a página.

Poderia tentar replicar o problema, com o módulo que mencionei?
O ambiente teve poucas alterações, desde que postei a PR.

* Magento Community 1.9.3.4
* Módulo Pagar.me 0.1.6
* Servidor Linux Ubuntu 16.04.3 LTS
* PHP 7.0.22
* Tema: Magento RWD (original/poucas customizações)

Obrigado novamente! E um ótimo final de semana.

**Comment by diogodaluz** [comment]
Me parece que tem alguma relação com instabilidade dos Correios.

Notei que este BUG sempre ocorre concomitante  com instabilidade dos Correios.

Não consegui testar  em detalhes, mas me parece que o módulo do Pagar.me abre a conexão com o servidor Pagar.me para buscar os meios de pagamento e nesse meio tempo o checkout está buscando endereço, ou algum outro detalhe dos Correios (sem ter concluido a busca dos meios de pagamento disponíveis). Nesse caso o Pagar.me fica aguardando e rompe a conexão (timeout) deixando apenas o layer lá de "aguardando".

** Não consegui testar em detalhes, mas foi o que aparentou.

**Comment by murilohns** [comment]
Fala @diogodaluz, @rafaelpatro, @CajuCLC 

Corrigido através do #276, correção pode ser acessada a partir da versão 0.1.8 do módulo :wink:
