### ISSUE TITLE
ícone boleto aparece em todas as formas de pagamento

### ISSUE THREAD

**Issue by davirs** [pagarme/pagarme-magento#178]
O ícone do boleto não tem validação nenhuma, o que acontece é que ele aparece em todos os meios de pagamento no checkout.

Estou utilizando o checkout transparente da o2ti. 

http://prntscr.com/exmeob
http://prntscr.com/exmew6
http://prntscr.com/exmf0q

É possível validar esse ítem?

pagarme-magento/app/design/frontend/base/default/template/pagarme/form/boleto.phtml

**Comment by devdrops** [comment]
Olá @davirs!

Peço que por favor siga o formato de template para abertura de issues; precisamos do nível de detalhamento das respostas para entender todos os detalhes envolvidos e assim ajudar da melhor forma possível :wink:

**Comment by davirs** [comment]
@devdrops  desculpe por não seguir o template.. é que é um erro bobo e todas as informações relevantes estão citadas e complementadas com identificadores nos screenshots...

Acredito que o importante é entender... Abraço!

**Comment by devdrops** [comment]
Olá @davirs.

> @devdrops desculpe por não seguir o template.. é que é um erro bobo e todas as informações relevantes estão citadas e complementadas com identificadores nos screenshots...

Analisando as imagens, não encontramos nenhuma das referências abaixo (que fazem parte de nosso template para issues):

* Versão do Magento
* Versão do Módulo Pagar.me
* Ambiente do servidor
* Versão do PHP
* Qualquer outra característica a ser considerada (versão do Apache ou nginx, versão do MySQL, módulos instalados e suas versões, etc)

Por favor, siga o modelo de template de issues deste projeto para entendermos o que de fato ocorre.

**Comment by davirs** [comment]
magento 1.9.3.2
última versão pagarme aqui do github, deve ser 0.1.6
php 5.6

Porém nada disso importa neste caso... Como dito acima, o ícone de boleto não tem validação(php ou qualquer outra) para identificar que o pagamento ativo naquele instante é boleto.. Por isso ele aparece em todos os meios.

`<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Pagarme
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list pagarme-payment-icons">
    <li class="boleto on">
        <span><?php echo $this->__('Boleto') ?></span>
    </li>
</ul>
<?php if ($_instructions = $this->getInstructions()): ?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">
            <?php echo nl2br($_instructions) ?>
        </div>
    </li>
</ul>
<?php endif; ?>`

**Comment by leonampd** [comment]
Oi @davirs o problema ainda persiste? Estamos trabalhando em um novo módulo que vc pode acompanhar no branch `v2` e por isso este problema não foi atacado. Vou fechar esta issue mas fique à vontade para reabrir se julgar necessário.
