### ISSUE TITLE
Bairro Faltando

### ISSUE THREAD

**Issue by greenboxal** [pagarme/pagarme-magento#18]
Tem dois módulos instalados:

https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro 
https://github.com/pagarme/pagarme-magento

No checkout, ao preencher todos os campos do formulário e tentar finalizar a compra, aparece uma mensagem "bairro está faltando".

Parece que o magento ta consultando um webservice desatualizado de CEP. Sera um conflito ou culpa do WebService?

Podia usar o nosso(https://api.pagar.me/1/zipcodes/).

@eneiasramos

**Comment by eneiasramos** [comment]
Qual a URL da sua loja?

**Comment by greenboxal** [comment]
http://www.netchairs.com.br

**Comment by eneiasramos** [comment]
@greenboxal não encontrei o módulo pagarme ativo na sua loja.

**Comment by eneiasramos** [comment]
@greenboxal o módulo foi implementado na loja. Foram definidos 4 linhas para endereços e CPF como obrigatório.

**Comment by rafaelstz** [comment]
Estou recebendo o mesmo erro, o que pode ser? Mesmo com 4 linhas e com o checkout do tema RWD não funciona.
