### ISSUE TITLE
Parcelamento x juros

### ISSUE THREAD

**Issue by davirs** [pagarme/pagarme-magento#181]
Olá. Tenho este questionamento a mais de um ano, prometeram mudanças e até agora não houve atualizações. Por isto vou fazer o pedido novamente para formalizar.

**Se temos tipos de juros diferentes para trabalhar, exemplo:**
1x: 3,49%
2x-6x: 3,59%
7x-12x: 3,69%
Antecipação: 2,99%
e outros..
**porque eu só consigo configurar desta forma:**
![screenshot_37](https://cloud.githubusercontent.com/assets/4355062/25144595/c2063f7e-2444-11e7-9bbe-87953a9d6549.png)

É fundamental para regra do negócio poder ter um controle melhor dessa gestão.. 
Se eu fizer uma média geral e jogar em cima de todas as parcelas como funciona hoje não fica justo para o meu cliente pagar! Porque que se ele fizer poucas parcelas paga igual quem fez no máximo possível... Juridicamente falando pode dar problema, inclusive.

Vou deixar aqui o apela para que esta atualização seja feita assim que possível, porque em um ano a pagarme já teve tempo suficiente.

Vou deixar também como funciona o parcelamento de um concorrente para ilustrar melhor a diferença nas configurações.
Obrigado!!!

![moip cartao](https://cloud.githubusercontent.com/assets/4355062/25144822/807cd350-2445-11e7-9e0e-fe581f493879.jpg)

**Comment by devdrops** [comment]
Favor seguir a formatação original para issues, conforme [modelo](https://github.com/pagarme/pagarme-magento/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by davirs** [comment]
Com modelo ou sem modelo é isso aí que preciso. Abri a issue e anexei ela no meu ticket direto pelo pagarme.
Agora é só esperar mais um ano!
