### ISSUE TITLE
Problema no Fluxo de compra

### ISSUE THREAD

**Issue by ryaanx** [pagarme/pagarme-magento#187]
Baixamos a extensão atualizada e vimos que foi criado um status de "Pendente". Ou seja, o pedido fica "Pendente" e depois de "Pago" vai pra "Processando". Mas não está atualizando automaticamente o status depois que o pedido é pago.

**Comment by devdrops** [comment]
Favor informar:

* Versão do Magento
* Versão do Módulo Pagar.me
* Versão do PHP
* Qualquer outra característica a ser considerada

**Comment by vgsmith** [comment]
Boa tarde @ryaanx , como vai?

Como não tivemos mais notícias suas, estou encerrando esta issue. Caso o problema persista, é só reabri-la de acordo com a formatação [modelo](https://github.com/pagarme/pagarme-magento/blob/master/.github/ISSUE_TEMPLATE.md).

Grande Abraço
