### ISSUE TITLE
Problema no Fluxo de compra

### ISSUE THREAD

**Issue by pedrocesar-ti** [pagarme/pagarme-magento#19]
O pedido fica como "Processando" no Magento e aparece como "Pago" no Pagar.me.

@eneiasramos

**Comment by eneiasramos** [comment]
@pedrocesar-ti para utilizar outro status para o pedido acesse o menu: Sistema -> Status de Pedidos

**Comment by pedrocesar-ti** [comment]
Opa @eneiasramos estas issues geralmente são passadas pelos clientes do Pagar.me, estou passando esta resposta para ele verificar. 

Mas acredito que o problema esteja durante o checkout, fica processando a transação nãe o muda de status, isso pode confundir o cliente deste lojista.

**Comment by eneiasramos** [comment]
@pedrocesar-ti fiz um ajuste para adicionar o status novo para cartão de crédito:

https://github.com/eneiasramos/pagarme-magento/commit/0571c03fbe93e1c560c3c9148aa5ea50dc0aa31f

**Comment by pedrocesar-ti** [comment]
Ok @eneiasramos , solicitei que o cliente faça os testes solicitados.

**Comment by pedrocesar-ti** [comment]
@eneiasramos O cliente continua reclamando da situação, segue abaixo:

Baixamos a extensão atualizada e vimos que foi criado um status de "Pendente". Ou seja, o pedido fica "Pendente" e depois de "Pago" vai pra "Processando". Mas não está atualizando automaticamente o status depois que o pedido é pago.

**Comment by eneiasramos** [comment]
Envie os acessos para suporte@gamuza.com.br

**Comment by pedrocesar-ti** [comment]
Feito! @eneiasramos

**Comment by eneiasramos** [comment]
@pedrocesar-ti Qual a URL da loja?

**Comment by pedrocesar-ti** [comment]
@eneiasramos a URL foi aquele que te passei no e-mail, é a mesma que o cliente informou agora que perguntei.

**Comment by eneiasramos** [comment]
Qual a URL?

**Comment by pedrocesar-ti** [comment]
Te mandei e-mail novamente com a URL.

**Comment by eneiasramos** [comment]
qual o seu email?

**Comment by pedrocesar-ti** [comment]
pedro.azevedo@pagar.me

**Comment by eneiasramos** [comment]
Preciso dos acessos FTP também...

**Comment by pedrocesar-ti** [comment]
@eneiasramos Favor verificar o e-mail.

**Comment by ryaanx** [comment]
Olá, estou tendo o mesmo problema.. estou com a ultima versao tbm...

"Baixamos a extensão atualizada e vimos que foi criado um status de "Pendente". Ou seja, o pedido fica "Pendente" e depois de "Pago" vai pra "Processando". Mas não está atualizando automaticamente o status depois que o pedido é pago."
