### ISSUE TITLE
Conflito com OSC 6

### ISSUE THREAD

**Issue by marco-domingues** [pagarme/pagarme-magento#2]
Pessoal, estou com um conflito com o onestep da inovarti e este módulo da Pagar.Me.

Quando clica para escolher a forma de envio, a forma de pagamento e revisão do pedido é atualizada.  Funcionalidade normal do OSC. Mas, quando faz isso, não carrega algum arquivo necessário do módulo do pagar.me para finalizar a compra.
Então, quando preenchemos os dados do cartão e tentamos finalizar a compra,  aparece o erro que os dados do cartão não foram preenchidos.

Confirmei isso atualizando a página, assim ele volta a carregar o arquivo do pagar.me que é possível finalizar o pagamento. É nítido o erro, porque quando esta "funcionando" ele vai fazendo a checagem real time, mas quando não carrega este arquivo, você preenche e não é feita nenhuma verificação.

Obs: com o checkout default do magento funciona normalmente o módulo. Não testei com outros checkouts.

**Comment by eneiasramos** [comment]
Olá @marco-domingues ! Tudo bem?

Fiz um ajuste no módulo para o carregamento do JS na página de pagamento.

Todavia parece que existe um BUG no OSC para ajustar os handles do form de pagamento quando troca-se o método de envio.

@deivisonarthur apliquei um pequeno ajuste no arquivo:

skin/frontend/base/default/onestepcheckout/js/onestepcheckout.js

Segue:

var OnestepcheckoutCoreUpdater = {

    ...

    onRequestCompleteFn: function(transport) {

    ....

    // --- adicionar código abaixo ao final do método --
    OSCPayment.initObservers();  // payment form reload fix
    }, // final do método: onRequestCompleteFn

    ....
}; // final da classe: OnestepcheckoutCoreUpdater

Abraços!

**Comment by golifter** [comment]
olá @eneiasramos estou com o mesmo problema. Não entendi o que devo alterar no arquivo onestepcheckout.js

Pode me explicar mais detalhadamente, por favor?

**Comment by eneiasramos** [comment]
Olá @marco-domingues  e @golifter ! Tudo bem?

Segue os bugfixes que apliquei no módulo:

https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro/commit/de0fe40439960b621e33b94ac17188a7371b7b3e

https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro/commit/4dae6f50d48f150f99fc1b828497eccb480bfe40

Espero que ajude!

Abraços!

**Comment by marco-domingues** [comment]
O primeiro já havia alterado, mas mesmo assim não estava funcionando o checkout. Continuava não "encontrando" os dados do cartão algumas vezes.
Vou testar mais tarde a segunda alteração!

Obrigado pela ajuda @eneiasramos

**Comment by golifter** [comment]
Olá @eneiasramos obrigado pela resposta!

Fiz a sua alteração e desativei também o jquery do modulo os6.
Parece que resolvemos o problema. Vou fazer mais alguns testes.

Muito obrigado pela ajuda

**Comment by eneiasramos** [comment]
@marco-domingues e @golifter qualquer problema é só dizer :)
