### ISSUE TITLE
Problemas na conexão com a api

### ISSUE THREAD

**Issue by lucasPiovesan** [pagarme/pagarme-magento#201]
Pessoal, estou tendo problemas ao navegar pelo checkout de minha loja.

Está dando esse erro:

#0 /public_html/lib/Varien/Http/Client.php(61): Zend_Http_Client->request(NULL)

#1 /public_html/app/code/community/Inovarti/Pagarme/Model/Api.php(196): Varien_Http_Client->request()

#2 /public_html/app/code/community/Inovarti/Pagarme/Model/Api.php(169): Inovarti_Pagarme_Model_Api->request('https://api.pag...', Object(Varien_Object))

#3 /public_html/app/code/community/Inovarti/Pagarme/Block/Form/Cc.php(62): Inovarti_Pagarme_Model_Api->calculateInstallmentsAmount(Object(Varien_Object))

#4 /public_html/app/design/frontend/base/default/template/pagarme/form/cc.phtml(35): Inovarti_Pagarme_Block_Form_Cc->getInstallmentsAvailables()

Houve alguma alteração na api?

**Comment by ricardotulio** [comment]
Fala @lucasPiovesan, tudo bem? 

Sim, tivemos algumas alterações na API e também tivemos relatos de clientes que utilizam o Magento, mas o problema já foi corrigido. O problema persiste?

**Comment by lucasPiovesan** [comment]
@ricardotulio problema foi resolvido, obrigado e desculpa pela demora no feedback!
