### ISSUE TITLE
Magento 1.7.0.2 - Instalação Pagarme - Tabela não existe

### ISSUE THREAD

**Issue by cadulrocha** [pagarme/pagarme-magento#207]
## Contexto

Instalando o modulo pagarme da erro ao fazer qualquer gravação em Métodos do Pagamento, publico o problema e a solução que encontrei. 

## Ambiente

magento comunnity 1.7.0.2 
Modulo Pagarme 0.1.6
PHP 5.5.38
My Sql - 5.6
Linux
## Passos para reproduzir

1. Acesse o painel administrativo do Magento
2. Clique em `Sistema > Configurações > Métodos de Pagamento`
3. Encontre a sessão `PagarMe - Configurações`
4. Informe uma API KEY e uma Encryption Key
5. Salve a configuração 

## Resultado esperado

Bingo!

## Resultado atual

SQLSTATE[42S02]: Base table or view not found: 1146 ""xxxxxx.pagarme_split_rules' doesn't exist 

## Possível correção

Nesse caso, tive que executar o sql direto no banco de dados para criar as tabelas. Pra quem tiver esse erro, tente instalar o modulo em outra versao 1.9, procure as tabelas  pagarme_marketplace_menu, pagarme_split_rules, exporta, e executa na loja atual. Comigo resolveu.

**Comment by vgsmith** [comment]
Boa tarde @cadulrocha , como vai?

Segui o passo a passo mencionado, mas não foi possível reproduzir esse bug. Foi realizada a limpeza de cache após a instalação do módulo?

Ainda sim, agradeço pela solução enviada.

Abs

**Comment by vgsmith** [comment]
Boa tarde @cadulrocha, tudo certo?

Como não tivemos mais notícias suas, estou encerrando esta issue. Caso o problema persista, é só reabri-la.

Grande Abraço
