### ISSUE TITLE
Ordens de venda estão sendo excluídas

### ISSUE THREAD

**Issue by ygorlazaro** [pagarme/pagarme-magento#209]
## Contexto

Fala pessoal! Estou tendo alguns problemas com ordens de venda no banco de dados. Elas aparentemente estão sendo excluídas, caso o pagamento não seja realizado por alguma restrição no cartão.

Esse componente tem alguma funcionalidade que exclua pedidos em determinados casos?

## Ambiente

[caso essa issue se trate de um bug, descreva como é o ambiente que ele ocorre, por exemplo:]

* Magento Community 1.9.3.1
* Módulo Pagar.me 0.1.6
* Servidor Linux
* PHP 5.4
* Apache 2.2
* MySQL 5.6
* Qualquer outra característica a ser considerada

**Comment by leonampd** [comment]
Oi @ygorlazaro tudo bem? 

Cara, antes de mais nada, pedimos desculpas pela demora em responder. Isso de fato acontece quando a compra não é autorizada por algum motivo. Nesses casos o cliente final é notificado que houveram problemas na transação e o módulo permite que ele refaça a compra com outro cartão, por exemplo. O problema é que nem sempre o cliente faz uma nova tentativa. 

Diante desse cenário estamos estudando uma maneira de melhorar esse fluxo e essa funcionalidade estará no novo módulo, ainda em desenvolvimento. Você pode acompanhar o progrsso através do branch [V2](https://github.com/pagarme/pagarme-magento/tree/v2).

Estou fechando essa issue, mas sinta-se a vontade para reabrí-la caso julgue necessário.

**Comment by ygorlazaro** [comment]
Olá @leonampd, na verdade essa demanda é tão antiga que paramos de usar a pagar.me na nossa loja. Mesmo assim, obrigado.
