### ISSUE TITLE
Retorno correto de erros no popup e email

### ISSUE THREAD

**Issue by davirs** [pagarme/pagarme-magento#21]
Este módulo retorna apenas  2 tipos de erro em popup na tela de checkout.
O primeiro quando você não insere algum dado do cartão (mas isso ja tem um script que cuida e não deixa finalizar sem)
O outro é um erro geral quando retorna transação negada.

O grande diferencial de um módulo de pagamento é informar realmente ao cliente o que aconteceu de errado, caso contrário o mesmo ficará tentando pagar várias vezes até desistir da compra.

a stone e a cielo retornam códigos de erros pela API. Provavelmente a pagarme tenha seus próprios códigos...
Seria necessário pegar estes erros e informar no popup exatamente o que está acontecendo.. O cliente já fica sabendo no ato qual é o problema evitando todo o transtorno de suporte e desistências... Com esse erro genérico a própria cielo não homologa a loja...

O mesmo erro da popup é enviado para o cliente via email.

segue anexo e um screen da loja...

![screenshot_14](https://cloud.githubusercontent.com/assets/4355062/10736268/2ae24f16-7bf3-11e5-8237-f71204dd61f3.png)

@jgabrielfaria
@eneiasramos

**Comment by SocialGroups** [comment]
Efetuamos diversas implementações de logs dos responses da nossa api, poderia por favor validar, todas estão disponíveis no master.
