### ISSUE TITLE
Valor mínimo de parcelas

### ISSUE THREAD

**Issue by panuci** [pagarme/pagarme-magento#216]
## Valor mínimo de parcelas

Percebi que o módulo está fazendo uma verificação direta no código e colocando o valor mínimo da parcela para R$ 5,00. "app/code/community/Inovarti/Pagarme/Block/Form/Cc.php". Em contato com o Pagarme me informaram que está validação não existe em sua plataforma.

Qual é o motivo desta validação no código? É alguma regra que deixou de existir? De qualquer forma fiz a correção em minha loja, liberando o valor mínimo, e até o momento está tudo correndo bem.

**Comment by leonampd** [comment]
Oi @panuci tudo bem?

Sei que já faz algum tempo desde que vc abriu essa issue mas, dei uma olhada na versão atual do módulo e não encontrei essa regra. Acredito que se vc fizer o update não enfrente mais esse problema. Vou fechar essa issue mas fique à vontade para reabrir se julgar necessário, ok?
