### ISSUE TITLE
classe em cada li dentro de ul de id:payment_form_pagarme_cc

### ISSUE THREAD

**Issue by regnolasco** [pagarme/pagarme-magento#217]
Olá Amigos,

É possivel atualizar o modulo colocando uma classe em cada li dentro do ul de id:payment_form_pagarme_cc   ??

## Ambiente
* Magento Community 1.9.2.2
* Módulo Pagar.me 0.1.6
* PHP 5.4
* MySQL 5.6

**Comment by leonampd** [comment]
Oi @regnolasco tudo bem?

Antes de mais nada, pedimos desculpa pela demora em retornar. Podería, por favor, explicar um pouco melhor a sua solicitação? Se possível, seguir o nosso formato de issues.

Abs
