### ISSUE TITLE
Pedido Duplicado no Pagar.me

### ISSUE THREAD

**Issue by lucasPiovesan** [pagarme/pagarme-magento#219]
Boa tarde pessoal,

Estou passando por um problema em minhas lojas onde o pedido entra no magento normalmente, e quando vou olhar o painel no pagar.me tem duas cobranças desse pedido. Ou seja, no magento entra uma instancia do meu pedido e no pagarme está entrando duas instacias, o que gera transtornos maiores se o pedido for de cartão.

Analisando os logs do magento, do módulo do pagar.me e do meu servidor, nenhum me mostra algum erro. Gostaria de saber se tem alguma informação ou algum ocorrido do tipo que possa me ajudar, ou se quiserem podemos fazer uma call para debater o ocorrido e explicar melhor o cenário.

Lembrando que trabalho com vários dos métodos de pagamentos disponíveis como pagseguro, mercado pago, stello, mundipagg, moip, braspag e vindi em outras lojas. Porém somente no pagar.me do dia 12 de Julho de 2017 até hoje está me apresentando esse problema, poderia ser alguma instabilidade na api de vocês?

**Comment by lucasPiovesan** [comment]
Alguma noticia a respeito? O erro voltou a acontecer aqui. Preciso de ajuda para poder corrigir.

**Comment by derekstavis** [comment]
Galera do @pagarme/support e @pagarme/operations pode ajudar com esse problema?

**Comment by lucasalegretti** [comment]
Boa tarde @lucasPiovesan, tudo bom?

Vamos conseguir te atender melhor se mandar essa demanda essa por e-mail, poderia nos mandar por gentileza? relacionamento@pagar.me. Eu até abriria o chamado para você, mas não consegui encontrar seu e-mail :/

Com esse chamado, conseguimos investigar mais a fundo e olhar nossos logs para entender o que pode ter acontecido, tudo bem? Se possível, poderia nos mandar os IDs dessas transações como exemplo também, por favor?

Já adianto que não deve ser algo com nossa API, não foi identificada nenhuma instabilidade que possa estar causando esse comportamento, mas conseguimos trabalhar juntos para resolver essa questão.

Se precisar de alguma ajuda, só me avisar.

**Comment by lucasPiovesan** [comment]
@lucasalegretti encaminhei um email com o ocorrido. Obrigado pela ajuda!

**Comment by vgsmith** [comment]
Boa tarde @lucasPiovesan , tudo certo?

Como a questão será tratada via suporte técnico, estou encerrando esta Issue.

Fico à disposição,
Abs
