### ISSUE TITLE
Transações acusam falta de dados quando dados são inseridos

### ISSUE THREAD

**Issue by rfviolato** [pagarme/pagarme-magento#22]
Segue a mensagem de erro quando o cliente tentou passar uma transação:

Operação de Pagamento Falhou. 
Razão 
Número do cartão está faltando. 
Nome do portador do cartão está faltando. 
Data de expiração do cartão está faltando. 
Código de segurança do cartão está faltando.

Tipo de Checkout 
onepage

Cliente: 
Iuri Medeiros da Silva <iuri@visualsurf.com.br>

Produtos 
Câmara de Ar Cadeira de Rodas 200x50 x 1 BRL 24.99

Total: 
BRL 43.39

Endereço de Cobrança: 
Iuri Medeiros da Silva 
(...)

Endereço de Entrega: 
Iuri Medeiros da Silva 
(...)

Forma de Entrega:

Forma de Pagamento: 
Cartão de Crédito

Data e Hora: 
27/10/2015 12:33:41

Verifiquei com ele e as API keys estavam corretas.

**Comment by eneiasramos** [comment]
@rfviolato qual a URL da sua loja?

**Comment by rfviolato** [comment]
Fala, @eneiasramos!

O URL da loja do cliente é http://visualsurf.com.br/

**Comment by eneiasramos** [comment]
@rfviolato poderia desabilitar o merge de css e js?

**Comment by rfviolato** [comment]
@eneiasramos Não entendi, qual merge?

**Comment by eneiasramos** [comment]
@rfviolato acesse o menu: Sistema -> Configuração -> Avandaçado -> Desenvolvedor: Ajustes de JS e Ajustes de CSS

**Comment by rfviolato** [comment]
@eneiasramos Feito!

**Comment by eneiasramos** [comment]
@rfviolato os seguintes bugfixes para o OSC devem estar aplicados:

https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro/commit/de0fe40439960b621e33b94ac17188a7371b7b3e

https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro/commit/4dae6f50d48f150f99fc1b828497eccb480bfe40

Há também um erro de JS na página do checkout que dever ser corrigido:

TypeError: element is null
prototype.js (linha 1931, col 5)
2

**Comment by rfviolato** [comment]
@eneiasramos 

Como procedo? Isso são commits que estão no ar ou tenho q orientar o cliente pra fazer aquelas mudanças?

**Comment by eneiasramos** [comment]
@rfviolato o desenvolvedor do lojista não pode deixar erros de JS no checkout...

**Comment by iurimedeiros** [comment]
Apliquei os bugfixes no OSC, o que poderia estar causando este erro de JS no prototype? Vocês tem alguma idéia sobre o que eu poderia fazer para resolver isso? Uma coisa que o Rafael se esqueceu de mencionar é que quando o módulo está em ambiente de teste ele valida todos os dados corretamente, será que isso ajuda em algo? Obrigado!

**Comment by eneiasramos** [comment]
Em alguma parte do site está referenciando um elemento que não existe...

**Comment by rfviolato** [comment]
Exato, pelo que vi está tentando acessar a propriedade `style` de um elemento que não está na variável

**Comment by iurimedeiros** [comment]
Eu realmente não sei como fazer, estive vendo e este problema parece que ocorreu com outros usuários do módulo. Como vocês chegaram ao erro que está chamando um elemento que não existe? No gerenciador do Chrome eu não encontrei nada além de uns alertas nas fontes... Obrigado!

**Comment by eneiasramos** [comment]
Envie os acessos FTP e ADMIN para suporte@gamuza.com.br

**Comment by iurimedeiros** [comment]
Cara já enviei um e-mail com os dados solicitados conforme solicitado, se precisar de algo mais não deixe de me falar. Abraço!

**Comment by iurimedeiros** [comment]
Fala Eneias, blza? Cara percebi que o problema estava relacionado ao cache do Magento, não sei se tinha alguma outra coisa interferindo? A pergunta é tem alguma coisa que possa ser feita para que o cache Page blocks HTML possa ser ativado novamente? Motivo: minha loja fica extremamente lenta com o cache desabilitado. Obrigado novamente!

**Comment by eneiasramos** [comment]
@iurimedeiros tudo bem?

Implementei o módulo Pagarme na loja e o cache já estava desabilitado...

Poderia habilitar o cache na loja e efetuar testes de compra?

Por favor, deixe-nos a parte de qualquer problema encontrado.

**Comment by iurimedeiros** [comment]
Olá Enéias, tudo ótimo e com você?

Cara eu já realizei testes e quando é habilitado o cache Page blocks HTML o módulo para de funcionar! Realizei testes com todos os demais caches e os demais não impedem o funcionamento do módulo, somente o que acabo de informar.

Abraço!

**Comment by eneiasramos** [comment]
@iurimedeiros tudo bem?

O seu checkout ainda continua com erro de JS:

![visualsurf](https://cloud.githubusercontent.com/assets/2862728/11366311/a6eee8e2-9293-11e5-9392-de78c9932870.png)

**Comment by iurimedeiros** [comment]
Fala Enéias, blza?

Cara estive vendo este erro, e aparentemente é um erro característico desta versão do Prototype, tem diversos relatos informando sobre o erro na linha 1931, um exemplo disto é a questão deste link: http://stackoverflow.com/questions/17022543/in-prototype-js-in-magento-on-line-1931-when-we-see-it-on-firebug.

Sinceramente, acredito que o problema que ocorre ao habilitar o cache não esteja relacionado a este erro do Prototype, pois caso realmente o erro fosse causado pelo Prototype acredito eu que até mesmo com o cache desabilitado não funcionaria o módulo.

Grande abraço!
