### ISSUE TITLE
Problemas no calculo de parcelas

### ISSUE THREAD

**Issue by murilohns** [pagarme/pagarme-magento#220]
## Contexto

O problema ocorre quando há alguma forma de desconto do próprio magento (Shopping cart promotions), neste caso colocamos 10% de desconto no boleto da pagar.me.

Segue o fluxo do que ocorre:

1º Ao finalizar uma compra de valor R$500 (Exemplo), utilizando boleto, o desconto é aplicado no valor total da compra, como na imagem abaixo:

![image](https://user-images.githubusercontent.com/18074134/28620916-6153bf96-71e5-11e7-9ade-43a87ba78947.png)
​​​
2º Não clique em finalizar pedido e volte para seu carrinho, aparecerá a seguinte tela:​

![image](https://user-images.githubusercontent.com/18074134/28620927-6f3ac230-71e5-11e7-91d2-4744918f7238.png)

3º Agora clique neste finalizar pedido, e selecione como meio de pagamento cartão de crédito(pagar.me). Ficará da seguinte forma:

![image](https://user-images.githubusercontent.com/18074134/28620938-7d817a28-71e5-11e7-9b5d-0ac0a83d9dde.png)​

Ou seja, nosso módulo está exibindo o valor com desconto aplicado.

4º Finalize o pedido com cartão de crédito. Aparecerá o seguinte valor na tela final:
​
![image](https://user-images.githubusercontent.com/18074134/28620944-88bacfac-71e5-11e7-9a2e-1c0fa548710c.png)

E a transação aparece da seguinte maneira em sua dashboard.pagar.me:

![image](https://user-images.githubusercontent.com/18074134/28620952-934c8e74-71e5-11e7-9841-5aa018edc956.png)

5º Porém, na página final de compra do usuário, aparece a seguinte tela:
![image](https://user-images.githubusercontent.com/18074134/28620999-d1708f98-71e5-11e7-98dc-fee2496fab8a.png)
​
Testei com outras formas de pagamento, e dado que o valor é transacionado corretamente, e o valor final do carrinho também aparece corretamente, chegamos a conclusão que a forma como as parcelas de cartão de crédito são exibidas estão erradas.

## Ambiente
* Magento Community 1.9.x
* Módulo Pagar.me 0.1.6
* Docker e Linux
* Apache 2.2
* MySQL 5.6
* Qualquer outra característica a ser considerada

## Passos para reproduzir

1. Crie uma regra de desconto no magento, clicando em Promotions > Shopping Card Price Rules
2. Crie uma regra de desconto, configurada da seguinte maneira:
Conditions:

![image](https://user-images.githubusercontent.com/18074134/28621229-a9b9e386-71e6-11e7-8ecb-e10e6b85f134.png)

Actions:

![image](https://user-images.githubusercontent.com/18074134/28621256-be4c3830-71e6-11e7-8826-d87a15a9d221.png)

3. Crie uma transação com os passos listados acima.

## Possível correção

* Fix na forma de exibir as parcelas.

**Comment by devdrops** [comment]
Fala @murilohns, beleza?

Cara, pelas imagens parece que tem algum outro módulo incluso e isso deve ser levado em conta para reproduzir o problema, já que pode acontecer algum conflito ou influência. Sabe me dizer se conseguimos reproduzir esse comportamento reportado em um ambiente isolado (somente o nosso módulo instalado)? Se ainda não fez esse teste, posso te ajudar com isso :wink:

**Comment by rafaelpatro** [comment]
Estou tendo esse mesmo problema também. Exatamente como descrito acima.
Ocorre quando o usuário vai até a última etapa da compra, e não finaliza, mas volta para as formas de pagamento.
Acho que o módulo deve estar lendo o valor total da sessão, já alterada por regras de preço.

## Ambiente

* Magento Community 1.9.3.0
* Módulo Pagar.me 0.1.6
* Servidor Linux Ubuntu 16.04.1 LTS
* PHP 7.0.8
* Apache 2.4
* MySQL 5.6.27
* Redis 3.0.6

**Comment by murilohns** [comment]
@devdrops Testei local, apenas com o módulo da pagar.me instalado e ocorre o mesmo problema.

**Comment by devdrops** [comment]
@murilohns e @rafaelpatro, muito obrigado pelo feedback de vocês! Vamos analisar o que acontece pra colocar uma correção nisso, e qualquer novidade vamos nos falando nesta mesma issue ok?

**Comment by gbaims** [comment]
Pessoal, não sei se ajuda.

Tive problemas com cálculo de descontos no Magento 1.9.3.x. Parece que essa é uma incompatibilidade com o PHP 7. Eu sugeriria refazer o reste utilizando o PHP 5.6 para ver se funciona bem.

**Comment by devdrops** [comment]
Oi @gbaims!

Muito obrigado pelo teu feedback! Pode dar mais contexto pra gente entender como você chegou nessa conclusão? Por exemplo, qual foi o teu ambiente de testes, o que você usou, quais versões, enfim, assim podemos reproduzir o problema e conseguir mais detalhes para investigar o problema.

**Comment by gbaims** [comment]
Fala @devdrops.

Assumi uma loja que estava em 1.9.2.1 desenvolvida por terceiros a pouco tempo. Efetuei a atualização direto para o 1.9.3.4 e passei a ter problemas com o total de alguns pedidos.

Talvez isso possa ajudar melhor: [https://github.com/Inchoo/Inchoo_PHP7/issues/80](https://github.com/Inchoo/Inchoo_PHP7/issues/80)

**Comment by thiagobs** [comment]
Blza galera?

@murilohns, já tive problemas parecidos como este em outros meios de pagamento. O que acontece é que o Magento guarda no Quote a informação do desconto aplicado, visto que ele já aplicou uma regra ao passar pela tela de finalização, então quando volta ao carrinho e novamente vai para a tela de finalização, acontece que o Quote fica com o valor final aplicado já com o desconto da regra. Sendo assim, qualquer meio de pagamento irá pegar este valor final com desconto para qualquer validação, e neste caso do Pagar.me, irá calcular as parcelas sobre este valor.

Uma possível solução, como foi no meu caso, seria aplicar um "reset" nos meios de pagamentos assim que o usuário reentrar na página de finalização da compra, mas isso envolve o módulo de checkout que você está utilizando ou criar algum event sobre a entrada da página de finalização.

**Comment by murilohns** [comment]
Resolvido pelo #224

**Comment by murilohns** [comment]
Esse problema foi resolvido na nova versão do módulo, que pode ser baixada em https://github.com/pagarme/pagarme-magento/releases
