### ISSUE TITLE
Boleto em branco

### ISSUE THREAD

**Issue by golifter** [pagarme/pagarme-magento#223]
Olá pessoal,

Ao clicar no link de impressão do boleto o mesmo abre uma janela em branco.

Já tentei reinstalar o modulo e nada.

A URL é http://regeneratepro.magemojo.io/store

**Comment by murilohns** [comment]
Fala @golifter , tudo bem meu caro?

Realizei um teste aqui, e notei que você está na versão 2017-07-17 da API pagar.me. Essa versão começa a trabalhar com boletos de forma diferente, e o módulo teve de ser adaptado para essa versão.
A alteração ocorreu recentemente, então sugiro que você **baixe o módulo novamente**, e instale-o atualizado que os boletos devem voltar a funcionar :)

**Comment by golifter** [comment]
@murilohns cara funcionou perfeitamente!

Obrigado pela ajuda.

Grande abraço

**Comment by murilohns** [comment]
beleza @golifter , se precisar reabrir a Issue sinta-se a vontade.

**Comment by rafaelpatro** [comment]
Olá @murilohns 
Um cliente teve o mesmo problema. Atualizei os arquivos e voltou a funcionar.

Mas outro cliente continua com os arquivos desatualizados. E os boletos continuam funcionando na loja.

Sabe dizer por que isso ocorre? Existe uma configuração específica por cliente, na API do Pagar.me? Ex.: _Clientes de agosto/2017 em diante..._

Devo atualizar os arquivos mesmo em ambientes que estão funcionando?

**Comment by murilohns** [comment]
Olá @rafaelpatro, tudo bem?

Sim, existem diversas versões da API pagar.me. O atual módulo do _magento_ está homologado nas versões 2013-03 e 2017-07.

Acredito que você só precise atualizar os arquivos caso seu cliente deseje atualizar a versão de API dele, assim você garante que o site dele continuará funcionando normalmente.
