### ISSUE TITLE
Calculo de juros incorreto

### ISSUE THREAD

**Issue by murilohns** [pagarme/pagarme-magento#225]
## Contexto

Juros é exibido corretamente, mas ao criar a transação é gerado o valor sem o calculo de juros.

## Ambiente

* Magento Community 1.9.3.1
* Módulo Pagar.me 0.1.6
* Docker
* PHP 5.4
* MySQL 5.5

## Passos para reproduzir

Configurar cartão de crédito pagar.me com X juros ao mês, e Y meses sem juros, como na imagem abaixo:

![image](https://user-images.githubusercontent.com/18074134/31191171-b97bd18a-a913-11e7-94e5-7dd2eb76ba65.png)

Criar uma transação parcela em Z quantidades, que deva aplicar juros, como na imagem abaixo:
![image](https://user-images.githubusercontent.com/18074134/31191467-93a4510c-a914-11e7-88d9-617006751f79.png)

## Resultado esperado

Transação parcelada em 12x de R$120 = R$ 1440

## Resultado atual

Transação parcelada em 12x de R$80 = R$ 960
![image](https://user-images.githubusercontent.com/18074134/31191537-d65e0baa-a914-11e7-9e88-74128832cd82.png)

**Comment by HTStore** [comment]
Você já conseguiu resolver?
