### ISSUE TITLE
Otimização

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#227]
Boa tarde. Estou realizando algumas otimizações na página de checkout, utilizando HTTP/2.

1 Acredito que o atributo async e/ou defer [neste trecho](https://github.com/pagarme/pagarme-magento/blob/ff959dd7666d22162e046ff3fee6c08780b8f802/app/design/frontend/base/default/layout/pagarme.xml#L35) deve ajudar na performance. Minha dúvida é se isso pode causar algum impacto negativo.

1.1 Outra dúvida é se existe algum motivo especial para este mesmo _script_ estar no corpo da página? Pode ser movido para o cabeçalho, sem afetar o funcionamento?

2. Outra questão quanto ao arquivo _https://assets.pagar.me/checkout/checkout.js_, que carrega a biblioteca _ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js_. Meu Magento já carrega a biblioteca 1.12. Como faço para que a biblioteca 1.11 seja descartada? Vi que o script em _checkout.js_ valida a versão, afim de evitar o jquery defasado. Mas não está funcionando. Talvez a validação esteja errada.

Obrigado, e uma boa semana.

**Comment by murilohns** [comment]
Corrigido através do #276, correção pode ser acessada a partir da versão 0.1.8 do módulo :wink:
