### ISSUE TITLE
4 linhas de endereço. Tá errado.

### ISSUE THREAD

**Issue by RAIMUNDOS54** [pagarme/pagarme-magento#239]
Meu e-commerce sempre usou 2. O sistema deve ser naturalmente compatível com o que estiver configurado na loja.

**Comment by leonampd** [comment]
Oi @RAIMUNDOS54 tudo bem?

Sou Leonam do time de dev aqui do Pagar.me. O nosso módulo tem a premissa de utilizar os recursos da plataforma e além disso, nossa API espera que os dados de endereço sejam informados dessa forma. Mesmo assim, para atender essas peculiaridades temos um `observer` que você pode implementar do seu lado e customizar conforme sua necessidade: `pagarme_get_customer_info_from_order_after`.

Aproveitando, peço que você responda seguindo o template de issues sugerido. Assim nos ajuda a identificar cenários semelhantes e te ajudar mais assertiva, tudo bem? Também nos ajuda a mapear casos semelhantes e priorizar nosso trabalho.

**Comment by RAIMUNDOS54** [comment]
Deve ser colocada uma opção no painel administrativo. Novos clientes tem que mudar o endereço para comprar? Que tipo e inconveniência não calculada seria esta? Não faz sentido.

**Comment by leonampd** [comment]
@RAIMUNDOS54 tudo bem?

Não entendi muito bem o seu problema e reforço o pedido para **seguir o template de issues**. De todo modo, abaixo vou esclarecer a situação:
 
**Por quê precisamos de quatro linhas de endereço?**

Atualmente nosso módulo é compatível com a versão [v2017-07-17](https://docs.pagar.me/v2017-07-17). Nesta versão existe um objeto `address`, dentro de `customer` que, necessariamente, precisa receber: `street`, `street number`, `zipcode` e `neighborhood`. Estes dados são obrigatórios para transações via cartão de crédito devido a análise do anti-fraude.
 
Esse é motivo das quatro linhas de endereço. É a maneira, nativa da plataforma, que causa menos impacto e demanda menos esforço por parte dos lojistas. Como dito acima, se algum destes dados não for informado a transação será negada pela nossa API.
  
Diante desse cenário, o time de desenvolvimento tentou encontrar uma solução que fosse capaz de parsear as informações de endereço informadas em uma única linha mas encontramos alguns impedimentos:
  
 - Seria necessário definir um padrão. Ex `<nome da rua>, <número>, <bairro>, <complemento>`
 
Essa opção é ruim porque o cliente final vai precisar conhecer esse padrão e qualquer coisa que fuja desse formato, pode significar a perda de uma venda por dados inválidos e a conversão seria diretamente prejudicada. Além disso, variações como endereço sem número, fogem do padrão, o que invalida um `parser` como este.
  
Além disso, este padrão poderia mudar de lojista para lojista invalidando também qualquer tipo de tratamento automático da nossa parte.
  
**É possível utilizar outra configuração de endereço?** 

Sim. Mas neste caso, será necessário a implementação do `observer` que comentei. Esta foi a maneira que encontramos para flexibilizar a configuração e deixar a cargo do lojista a definição de como tratar esse caso.

**Comment by fredpiuma** [comment]
Essa obrigatoriedade de 4 linhas para o endereço é padrão não só no Pagar.me. O PagSeguro também utiliza exatamente dessa forma, porém lá eles tem uma diferença na tela de configuração do módulo, existem 4 campos para indicar o que deve ser enviado para eles nesses 4 campos, então é possível por exemplo enviar linha1=input1, linha2=input2, linha3=input1, linha4=input1. Ou seja, seriam enviados dados incorretos nas linhas 3 e 4 para o PagSeguro, mas isso é uma solução para lojas com apenas 2 linhas de endereço. Talvez seja uma solução futura para não obrigar lojas nessa condição a editar os arquivos do módulo ou do core, o que não é uma boa prática.
