### ISSUE TITLE
Campos não identificados no Checkout Simplificado

### ISSUE THREAD

**Issue by filipedeschamps** [pagarme/pagarme-magento#24]
@eneiasramos tudo bem meu caro?

Um cliente nosso (http://www.planetasuplementos.com/) está utilizando o Checkout Simplificado e parece estar passando pelos exatos mesmos problemas da issue https://github.com/pagarme/pagarme-magento/issues/22.

Você sabe dizer se temos algum patch para ele?

Obrigado!

**Comment by eneiasramos** [comment]
@filipedeschamps não encontrei o JS do pagarme habilitado nessa loja...

**Comment by filipedeschamps** [comment]
@eneiasramos interessante, o cliente reporta estar com o módulo ativo. Mandei no seu email os dados de acesso para ver se você consegue nos ajudar. Muito obrigado!

**Comment by eneiasramos** [comment]
@filipedeschamps o módulo está ativo mas não está instalado corretamente...

**Comment by filipedeschamps** [comment]
Boa @eneiasramos ! Você sabe em qual parte da instalação está errado?

**Comment by eneiasramos** [comment]
Está faltando pasta skin e js do módulo...

**Comment by filipedeschamps** [comment]
Show de bola, já reportei o desenvolvedor do site, valeu meu caro!

**Comment by filipedeschamps** [comment]
@eneiasramos o cliente retornou o seguinte:

```
O módulo está instalado corretamente no servidor sim, inclusive com as 
pastas informadas.

Eu adicionei as pastas informadas também dentro do fallback do tema e o 
problema persiste.
```

Como podemos avaliar se está instalado de forma correta? Muito obrigado!

**Comment by eneiasramos** [comment]
Envie os acessos FTP e admin para suporte@gamuza.com.br

**Comment by filipedeschamps** [comment]
Feito, valeu meu caro :+1:

**Comment by digitalvoip** [comment]
Visitei esta loja http://www.planetasuplementos.com de fato o checkout simplificado não critica o CPF... mas sei que se instalar o OSC 6 (o que eu uso) vai funcionar, mas só com este OSC 6 a tela do checkout fica feia.... então instalei o CheckoutVendaMais disponibilizado grátis pelo http://ipagare.com e a tela fica beleza. O único problema que tenho, aparentemente, é que o meu ckeckout ao clica no botão finalizar compra aparece a tela anexa... fica um plugin executando e não sai daquilo (ver tela anexa). Se alguém puder ajudar eu agradeço muito, meu skype = salvador-ba
![tela](https://cloud.githubusercontent.com/assets/15305033/12311666/7c70c628-ba37-11e5-8ed1-efd2106c0f05.jpg)
