### ISSUE TITLE
Transações no cartão acusam falta de dados, ajuda para identificar problemas de .js

### ISSUE THREAD

**Issue by thiagoprado88** [pagarme/pagarme-magento#25]
Eneias você poderia ajudar a identificar alguma problema de .js na loja: www.armazem2000.com.br ? Todo dia tem o erro igual da #22   :Razão
Número do cartão está faltando. Nome do portador do cartão está faltando. Data de expiração do cartão está faltando. Código de segurança do cartão está faltando. 
Tipo de Checkout
onepage 

Obrigado

**Comment by eneiasramos** [comment]
@thiagoprado88 não consegui simular esse erro na www.armazem2000.com.br

**Comment by thiagoprado88** [comment]
Estranho @eneiasramos aconteceu um agora pouco, mas não acho que ocorre sempre e nem com todos os clientes, por isso que não temos ideia do que fazer. Operação de Pagamento Falhou.
Razão
Falha na transação, por favor tente novamente ou entre em contato com o banco emissor do cartão. Transação recusada pela operadora de cartão. 
Tipo de Checkout
onepage 
Cliente:
Moises Lopes <lopes.moises@uol.com.br> 
Produtos
Delipaste Fabbri Pistacchio Fino /Pistache - 250g x 1 BRL 56.9
Total:
BRL 64.9 
Endereço de Cobrança:
Moises Lopes
Rua Doutor Brasílio Machado
263
apto 111
Santa Cecília
São Paulo, São Paulo, 01230010
Brasil
T: (11) 3825-1748 
F: (11) 98426-5126 
Endereço de Entrega:
Moises Lopes
Rua Doutor Brasílio Machado
263
apto 111
Santa Cecília
São Paulo, São Paulo, 01230010
Brasil
T: (11) 3825-1748 
F: (11) 98426-5126 
Forma de Entrega:
Frete 
Forma de Pagamento:
Cartão de Crédito 
Data e Hora:
04/11/2015 16:13:40

**Comment by eneiasramos** [comment]
@thiagoprado88 somente esse erro que obtive quando utilizei dados de cartão de crédito de teste...

**Comment by thiagoprado88** [comment]
Esse erro continua aparecendo, acabou de acontecer com essa cliente
Operação de Pagamento Falhou.
Razão
Número do cartão está faltando. Nome do portador do cartão está faltando. Data de expiração do cartão está faltando. Código de segurança do cartão está faltando. 
Tipo de Checkout
onepage 
Cliente:
Adriana Ferreira <aferreira@ig.com.br> 
Produtos
Ampola Saborizante Mini-Gourmet- Gran Chef - 100 unidades x 1 BRL 28
Total:
BRL 42 
Endereço de Cobrança:
Adriana Ferreira
Rua do Torneiro
41
São Lucas
Uberlândia, Minas Gerais, 38412342
Brasil
T: (34) 3219-4444 
F: (34) 9961-6666 
Endereço de Entrega:
Adriana Ferreira
Rua do Torneiro
41
São Lucas
Uberlândia, Minas Gerais, 38412342
Brasil
T: (34) 3219-4444 
F: (34) 9961-6666 
Forma de Entrega:
Frete 
Forma de Pagamento:
Cartão de Crédito 
Data e Hora:
24/11/2015 10:52:07

**Comment by thiagoprado88** [comment]
Alguns clientes usam o celular para faze compras, já fez algum texte com o IOS ou android?

**Comment by rafaelpatro** [comment]
Passei por esse mesmo problema ontem e consegui resolver.
Ao finalizar o checkout recebia a mesma mensagem de falta de dados.
O console exibia o seguinte:
![image](https://cloud.githubusercontent.com/assets/13813964/23331026/0b783446-fb3c-11e6-9808-bf25ae1f2440.png)

Achei esse tópico explicando o funcionamento do prototype.js, responsável pela renderização do código nas etapas do checkout: http://stackoverflow.com/questions/1812560/prototype-ajax-updater-eval-javascript-functions

Enfim, é só ajustar a declaração do método _pagarmeValidadeFields_.
