### ISSUE TITLE
Split de pagamento por loja

### ISSUE THREAD

**Issue by pfgianoto** [pagarme/pagarme-magento#254]
Boa tarde!
trabalho com magento multilojas, onde cada loja é de um vendedor. No módulo atual pelo que vi no código, é feito uma vinculação de produto com vendedor, ai quando vende o produto é feito o split daquele produto especifico com o vendedor! No entanto existe a possibilidade de vincular uma das lojas do meu magento a um vendedor? (pegando o total do pedido ou algo do tipo ao inves do valor do produto) ai o pedido que entrar dessa loja faz o split com o vendedor vinculado aquela loja?

Ex:

Loja Mãe (minha loja)
- Loja do João (sub loja, e vende os mesmos produtos da Loja Mae)
- Loja da Maria (sub loja, e vende os mesmos produtos da Loja Mae)

Ao entrar um pedido na Loja do João, faz o split com o João
Ao entrar um pedido na Loja da Maria, faz o split com a Loja da Maria.

Isso é possivel? Alguma sugestão de customização para que o módulo atenda dessa forma?

abraços!!

**Comment by leonampd** [comment]
@pfgianoto tudo bem?

Sim hoje o módulo atual não tem essa funcionalidade. Inclusive, pretendemos depreciar esse módulo este ano já que está em desenvolvimento um novo módulo para magento 1.x. Ainda assim não temos previsão para que essa demanda entre no módulo. Se quiser pode acompanhar o desenvolvimento dele pelo branch `v2`.

De todo modo, acredito que para implementar isso, seria preciso gerenciar e vincular os `recipients_ids` às lojas e, no processo de criação da transação aplicar a regra do split.

**Comment by pfgianoto** [comment]
Ola @leonampd obrigado pelo retorno parceiro!
Tem previsão para o novo módulo?
o módulo atual esta funcional certo? estou pensando em tentar customizar para atender dessa forma que mencionei.

abs

Pedro

**Comment by pfgianoto** [comment]
Aproveitando, @leonampd o módulo trabalha com multilojas? pois estou tentando executar o módulo em uma loja de teste com multiloja e aparece o seguinte erro no checkout: http://prntscr.com/hz2n17

abs!
