### ISSUE TITLE
Pedido não muda para estornado no magento

### ISSUE THREAD

**Issue by Hzc2500** [pagarme/pagarme-magento#255]
## Contexto

Bug que está ocorrendo em todos os pedidos que são cancelados no pagar.me, não estão alterando de status no magento.

## Ambiente

* Magento Community 1.9.2.4
* Módulo Pagar.me 0.1.5
* Servidor Linux
* PHP 5.5
* MySQL 5.6

## Passos para reproduzir

Quando o cliente realiza uma compra e é recusada pelo pagar.me, no magento ele continua com status de pagamento confirmado.

## Resultado esperado

Era esperado que ao ser cancelado, o pedido fosse mudado para o status estornado

## Resultado atual

O pedido ainda continua como pedido confirmado.

**Comment by leonardo-barbosa** [comment]
Olá @Hzc2500 , boa tarde.
Saberia me informar se os testes estão sendo realizados em ambiente local ou em algum host com endereço público?
Também percebi que sua versão do módulo está desatualizada, visto que a atual é a 0.16, sendo assim peço que realize a atualização do mesmo em seu site.

Faz sentido? Fico no aguardo.

Abraços,

**Comment by Hzc2500** [comment]
Já encontramos uma solução para o caso, @leonardo-barbosa obrigado 👍
