### ISSUE TITLE
Pedidos registrados somente no pagar.me

### ISSUE THREAD

**Issue by renorram** [pagarme/pagarme-magento#258]
## Contexto

Alguns pedidos feitos no magento foram registrados no pagar.me e foram faturados no cartão do cliente mas não estão no magento, já verifiquei backups do magento e não encontrei esses pedidos. Teve dois casos reportados, no 1º não encontrei nem dados do pedido e nem do cliente no magento porém o pedido foi registrado no pagarme e faturado no cartão do cliente, no 2º caso foram registrados 3 pedidos similares no pagar.me porém só um está no magento, nesse último os dados do cliente foram registrados no magento normalmente.

## Ambiente

* Magento Community 1.9.3.7
* Módulo Pagar.me 0.1.6
* Servidor CentOS Linux release 7.4.1708
* PHP 5.6
* Apache 2.4.6
* MySQL 5.7
* Módulo de OSC: Checkout VendaMais IPagare

## Passos para reproduzir

Como o erro parece ser algo repentino e não encontrei nenhuma informação nos logs, não consegui criar uma sequência de passos capaz de reproduzir o mesmo erro.

## Possível correção (?)

Utilizando a v2, que vi ser mencionado em alguns issues, asseguraria que isso não aconteceria novamente ?

No geral queria saber se mais alguém passou por isso e se existe alguma forma de solucionar ou pelo menos uma pista de qual seja o problema.

**Comment by thiagobs** [comment]
@renorram Hoje estamos tendo o mesmo problema com um de nossos lojistas clientes, onde aconteceu exatamente a mesma coisa: entram pedidos e transações capturadas no Pagar.me, porém elas não são exibidas no Magento.

Isso está ocorrendo apenas em alguns pedidos esporádicos, e no nosso caso foram somente em pagamentos com cartão de crédito.

Usamos também a versão 0.1.6.

**Comment by murilohns** [comment]
Fala, @renorram e @thiagobs beleza?

Esporadicamente isso acontece para transações de cartão de crédito devido à um erro de TimeOut no Magento.

Tentarei fazer um fluxo aqui para explicar melhor, ok?

1. O cliente clica para efetuar um pedido em sua loja. O módulo do Pagar.me envia uma requisição de transação para a API.

2. Por algum motivo, a transação demora mais que o ideal para ser processada.

3. Cliente clica novamente para efetuar a compra. O módulo do Pagar.me envia uma requisição de transação para a API.

4. Pagar.me retorna a resposta do segundo _click_.

5. Pedido do segundo _click_ é finalizado.

6. Pagar.me termina o processamento da segunda transação.

Então ficaria parecido com isso:

1º Click > Requisição Pagar.me > 2º Click > Requisição Pagar.me > Resposta 2º Click > Resposta 1º Click.

Com isso, mesmo que os pedidos não sejam cadastrados no magento, a transação ocorre no Pagar.me

Neste caso, recomendamos que você estorne uma das transações duplicadas e prossiga com o pedido com a outra.

Se quiserem que nossa equipe investigue melhor o que houve com esses pedidos, por favor, enviem um e-mail para suporte@pagar.me que poderemos investigar melhor e coletar mais dados sobre essas transações.

Att.

**Comment by renorram** [comment]
@murilohns obrigado pela atenção! :smile: vou entrar em contato pra ver como solucionar da melhor maneira.
