### ISSUE TITLE
Postback url não está sendo enviada durante a criação da transação

### ISSUE THREAD

**Issue by leonampd** [pagarme/pagarme-magento#261]
## Contexto

Atualmente a url de postback não é informada no momento em que é feita a requisição para a criação da transação.

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me 3.4.1
* Servidor Linux
* PHP 5.4
* Apache 2.2
* MySQL 5.6

## Passos para reproduzir

1. Realizar uma compra via cartão de crédito (checkout transparente) na plataforma
2. Verificar presença da url de postback no response da requisição

## Resultado esperado

Que a url de postback seja informada

## Resultado atual

Postback url não informada

**Comment by Josano** [comment]
Esse bug já foi corrigido?
