### ISSUE TITLE
Não aparecem as parcelas no <select>

### ISSUE THREAD

**Issue by fredpiuma** [pagarme/pagarme-magento#263]
## Contexto

* É um BUG de 2 ou 3 dias para cá a loja de meu cliente não está exibindo as opções de parcelamento no select. Fiz alguns testes, mas nada resolveu. Então hoje fui verificar a versão do ambiente de testes e está com o mesmo problema da versão do ambiente de produção.

## Ambiente

* Problema tanto no ambiente de produção como no de testes
* Magento Community 1.9.3.6
* Módulo Pagar.me mais recente
* Servidor Linux
* PHP 5.6
* Apache 2.2
* MySQL 5.6 (MariaDB)
* Atualizamos com essa versão que saiu a 1 mês, mas NÃO resolveu
* NÃO utilizamos nenhum módulo de personalização da tela de compras como o OSC6
* NÃO utilizamos nenhuma outra forma de pagamento além do Pagar.me
* NÃO fizemos nenhuma mudança, nenhuma instalação ou atualização. Está exatamente igual estava a 4 dias atrás quando ainda funcionava perfeitamente
* Conferimos as duas keys e ta ok
* Reiniciamos o apache
* Limpamos cache
* Não é problema no client-side, o $this->getInstallmentsAvailables() da linha cc.phtml:35 vem um array vazio
* Não tem erros no var/log/apache2 ou no magento/var/reports

## Passos para reproduzir

1. Coloco um produto no carrinho
2. Clico em finalizar compra
3. Informo endereço
4. Seleciono o método de envio
5. Escolho cartão de crédito
6. Não aparecem as parcelas

**Comment by redati** [comment]
Eu também estou com mesmo problema desde ontem.

Uso o OSC6. 

Apenas o boleto funciona. A opção de cartão parou de funcionar.

**Comment by jonatasmaxi** [comment]
Olá @redati  tudo bom?

Meu nome é Jonatas e faço parte da equipe de suporte técnico do Pagar.me. 

Estamos investigando o que pode ter causado o problema e assim que tiver uma solução atualizaremos por aqui. 

Já temos uma noção do que pode ter causado o problema e estamos validando com o @fredpiuma via ticket, sinta-se à vontade para entrar em contato conosco no e-mail suporte@pagar.me neste meio tempo.

Qualquer dúvida estou à disposição.

**Comment by redati** [comment]
Beleza, se precisar de alguma informação  da minha parte sinta se a vontade. Aqui a parte do código que processa a opção de cartão trava, ou seja, tudo que deveria aparecer após a opção de cartão como o campo para preencher os dados do cartão, resumo do pedido e botão para finalizar o pedido não aparece. Se desabilitar opção de cartão, o boleto e tudo mais funciona normal. Abç.

**Comment by jonatasmaxi** [comment]
Olá @redati , tudo bom?

Validando com o @fredpiuma descobrimos que o erro estava sendo causado pelo parâmetro max_installments proveniente da configuração do número máximo de parcelas do módulo do Pagar.me.  O valor enviado para gente era 15 e o número máximo de parcelamento que aceitamos é 12. 

O @fredpiuma alterou esta configuração e o dele voltou a funcionar normalmente. 

Consegue validar pra gente se isto resolve o seu problema @redati ?

Se precisar de mais alguma coisa estou à disposição. 

Abraços.

**Comment by redati** [comment]
Aqui estava 12 e coloquei 10, não adiantou. 
![pagarme](https://user-images.githubusercontent.com/6043222/35697304-e7839aac-0770-11e8-9162-d31c4c2141f3.JPG)

**Comment by jonatasmaxi** [comment]
Ola @redati, tudo bom?

Certo, como o problema parece estar relacionado a outro assunto, irei abrir outra issue e te incluir no acompanhamento da mesma, ok?

**Comment by murilohns** [comment]
Olá @redati, pode nos enviar a tela de configuração do módulo do Pagar.me em sua plataforma?

Somente a página de configuração de cartão de crédito, por favor.

Por favor, esconda sua chave de api e criptografia para não serem expostas no print.

**Comment by jonatasmaxi** [comment]
@fredpiuma  o problema foi resolvido? Se sim, posso te ajudar em algo mais?

**Comment by fredpiuma** [comment]
Resolvido. Obrigado.
