### ISSUE TITLE
Formulário de preenchimento dos dados do cartão não aparece

### ISSUE THREAD

**Issue by jonatasmaxi** [pagarme/pagarme-magento#267]
## Contexto

Campos para preenchimento dos dados de cartão não aparecem 

## Ambiente

Magento 1.9
Módulo Pagar.me 0.1.6
OSC6
Ningx 1.13 - Naxsi e cloudflare ativado.
PHP 7 com modulo Inccho.
Percona 5.7

## Passos para reproduzir
1. Coloco um produto no carrinho
2. Clico em finalizar compra
3. Informo endereço
4. Seleciono o método de envio
5. Escolho cartão de crédito
6. Não aparece o formulário para preenchimento dos dados de cartão. 

## Resultado esperado

Formulário para preenchimento dos dados do cartão é mostrado

## Resultado atual

Formulário para preenchimento dos dados do cartão não é mostrado

## Screenshots

![image](https://user-images.githubusercontent.com/11192676/35698251-9f5cc980-0773-11e8-978a-832208dc9e90.png)

**Comment by jonatasmaxi** [comment]
@redati pode me ajudar a complementar os dados do ambiente?

Qual a URL de sua loja?

**Comment by redati** [comment]
https://decoraonline.com.br

Ningx 1.13 - Naxsi e cloudflare ativado.
PHP 7 com modulo Inccho.
Percona 5.7

Log do magento ativado mas sem erros, sem reports, sem exceptions, sem erro no nginx. 

Restaurei um backup do bd do dia anterior mas não resolveu.

**Comment by jonatasmaxi** [comment]
Olá @redati tudo bom?

Vi por aqui que o Misael já está em contato com a nossa equipe de suporte. Identificamos que estão ocorrendo alguns erros no loading dos scripts quando selecionado o método de pagamento de Cartão de Crédito. 

Quer que coloquemos algum email em cópia no chamado aberto?

**Comment by redati** [comment]
Resolvi o problema do script. Na verdade não relacionado, é do algolia seaarch.

**Comment by redati** [comment]
Se eu desabilitar opção de cartão, tudo funciona corretamente.

**Comment by redati** [comment]
![naopasou](https://user-images.githubusercontent.com/6043222/35699542-8abce218-0777-11e8-95dd-e6ab27e7b004.JPG)

Desabilitei o modulo One Step e garrou nessa tela.

**Comment by redati** [comment]
![esse](https://user-images.githubusercontent.com/6043222/35700226-880e62ba-0779-11e8-9eba-9390c75ad4ff.JPG)

**Comment by redati** [comment]
Fatal error: Uncaught TypeError: Argument 1 passed to Mage_Rule_Model_Abstract::validate() must be an instance of Varien_Object, instance of Inovarti_Pagarme_Helper_Checkout_Data given, called in /usr/share/nginx/bk/app/code/community/Inovarti/Pagarme/Block/Form/Cc.php on line 57 and defined in /usr/share/nginx/bk/app/code/core/Mage/Rule/Model/Abstract.php:351
Stack trace:
#0 /usr/share/nginx/bk/app/code/community/Inovarti/Pagarme/Block/Form/Cc.php(57): Mage_Rule_Model_Abstract-&gt;validate(Object(Inovarti_Pagarme_Helper_Checkout_Data))
#1 /usr/share/nginx/bk/app/code/community/Inovarti/Pagarme/Block/Form/Cc.php(69): Inovarti_Pagarme_Block_Form_Cc-&gt;hasCreditCardDiscountRules()
#2 /usr/share/nginx/bk/app/code/community/Inovarti/Pagarme/Block/Form/Cc.php(114): Inovarti_Pagarme_Block_Form_Cc-&gt;getCheckoutTotalAmount()
#3 /usr/share/nginx/bk/app/design/frontend/base/default/template/pagarme/form/cc.phtml(35): Inovarti_Pagarme_Block_Form_Cc-&gt;getInstallmentsAvailables()
#4 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Template. in /usr/share/nginx/bk/app/code/core/Mage/Rule/Model/Abstract.php on line 351

**Comment by jonatasmaxi** [comment]
@redati você chegou a testar com o checkout Pagar,me e ver se acontece o mesmo erro?

**Comment by redati** [comment]
mesma coisa.

se eu comentar //$ruleIsValid = $rule->validate(Mage::helper('checkout'));

em app/code/community/Inovarti/Pagarme/Block/Form/Cc.php ai tudo aparece normal

**Comment by redati** [comment]
fiz um pedido com cartão e foi processado. 

Mas abrir o pedido no admin, tive o erro:

rror: error setting certificate verify locations:
  CAfile: /usr/share/nginx/bk/.modman/pagarme-magento/lib/pagarme/lib/Pagarme/ca-certificates.crt
  CApath: /etc/ssl/certs

#0 /usr/share/nginx/bk/.modman/pagarme-magento/lib/pagarme/lib/Pagarme/Request.php(26): RestClient->run()
#1 /usr/share/nginx/bk/app/code/community/Inovarti/Pagarme/Model/TransactionPayables.php(37): PagarMe_Request->run()
#2 /usr/share/nginx/bk/app/code/community/Inovarti/Pagarme/Model/TransactionPayables.php(11): Inovarti_Pagarme_Model_TransactionPayables->request('/transactions/3...')
#3 /usr/share/nginx/bk/app/code/community/Inovarti/Pagarme/Block/Adminhtml/Order/View/Tab/SplitOrder.php(26): Inovarti_Pagarme_Model_TransactionPayables->preparePayables('32800922')
#4 /usr/share/nginx/bk/app/design/adminhtml/default/default/template/pagarme/order/view/tab/split.phtml(16): Inovarti_Pagarme_Block_Adminhtml_Order_View_Tab_SplitOrder->getPayables()
#5 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Template.php(241): include('/usr/share/ngin...')
#6 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#7 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#8 /usr/share/nginx/bk/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#9 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#10 /usr/share/nginx/bk/app/code/core/Mage/Adminhtml/Block/Widget/Tabs.php(303): Mage_Core_Block_Abstract->toHtml()
#11 /usr/share/nginx/bk/app/design/adminhtml/default/default/template/widget/tabs.phtml(38): Mage_Adminhtml_Block_Widget_Tabs->getTabContent(Object(Inovarti_Pagarme_Block_Adminhtml_Order_View_Tab_SplitOrder))
#12 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Template.php(241): include('/usr/share/ngin...')
#13 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#14 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#15 /usr/share/nginx/bk/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#16 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#17 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#18 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Text_List->_toHtml()
#19 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#20 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('left', true)
#21 /usr/share/nginx/bk/app/design/adminhtml/default/default/template/page.phtml(58): Mage_Core_Block_Abstract->getChildHtml('left')
#22 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Template.php(241): include('/usr/share/ngin...')
#23 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#24 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#25 /usr/share/nginx/bk/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#26 /usr/share/nginx/bk/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#27 /usr/share/nginx/bk/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#28 /usr/share/nginx/bk/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#29 /usr/share/nginx/bk/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(128): Mage_Core_Controller_Varien_Action->renderLayout()
#30 /usr/share/nginx/bk/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Sales_OrderController->viewAction()
#31 /usr/share/nginx/bk/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('view')
#32 /usr/share/nginx/bk/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#33 /usr/share/nginx/bk/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#34 /usr/share/nginx/bk/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#35 /usr/share/nginx/bk/index.php(83): Mage::run('', 'store')
#36 {main}

**Comment by jonatasmaxi** [comment]
Você sabe qual a versão do cURL do seu servidor? Essa informação consta na página phpInfo.

**Comment by redati** [comment]
cURL support | enabled
-- | --
cURL Information | 7.35.0
Age | 3
Features
AsynchDNS | Yes
CharConv | No
Debug | No
GSS-Negotiate | Yes
IDN | Yes
IPv6 | Yes
krb4 | No
Largefile | Yes
libz | Yes
NTLM | Yes
NTLMWB | Yes
SPNEGO | No
SSL | Yes
SSPI | No
TLS-SRP | Yes
HTTP2 | No
Protocols | dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, smtp, smtps, telnet, tftp
Host | x86_64-pc-linux-gnu
SSL Version | OpenSSL/1.0.1f
ZLib Version | 1.2.11


OpenSSL support | enabled
-- | --
OpenSSL Library Version | OpenSSL 1.1.0g 2 Nov 2017
OpenSSL Header Version | OpenSSL 1.1.0g 2 Nov 2017
Openssl default config | /usr/lib/ssl/openssl.cnf

**Comment by jonatasmaxi** [comment]
Aparentemente está tudo certo com a versão do cURL. O erro parece estar relacionado com a chamada do método que verifica as existência das regras de desconto. Esse método é chamado por um outro que calcula o valor total do pedido, exatamente aqui: https://github.com/pagarme/pagarme-magento/blob/30a02eccf72d60e3c1df3ee2dfd8978f1b65a8c7/app/code/community/Inovarti/Pagarme/Block/Form/Cc.php#L69 
Vocês possuem algum outro módulo que possa estar fazendo alterações nos objetos utilizados durante a execução desta função? https://github.com/pagarme/pagarme-magento/blob/30a02eccf72d60e3c1df3ee2dfd8978f1b65a8c7/app/code/community/Inovarti/Pagarme/Block/Form/Cc.php#L53

**Comment by redati** [comment]
não tenho mais o erro ao ver o pedido. Esta tudo normal, exceto que so consigo usar comprar com cartão com a linha //$ruleIsValid = $rule->validate(Mage::helper('checkout')); comentada.

Quanto a outros módulos. 
Não utilizo módulos de promoção e de pagamento é somente a pagar.me. Plugg.to não sei se pode ser, mas desativei o módulo e não adiantou, bem como o do facebook pixel, pois apenas os dois são mais recentes, o restante são modulos que estão a muito tempo junto com pagarme. 

Fiz um grep recursivo com o nome das funções em app/code mas so modulo pagarme usando.



O php para de processar aqui app/code/community/Inovarti/Pagarme/Block/Form/Cc.php na linha $pagarmeHelper = Mage::helper('pagarme'); la quase no final, apos essa linha nada mais é processado, pois obtive logs apenas antes dessa linha, depois dessa linha nada mais processa.

**Comment by redati** [comment]
So esse pequeno tempo que comentei a linha recebi alguns pedidos qual o risco de manter ela comentada ?

**Comment by redati** [comment]
Isso funciona pra mim. Posso deixar assim ? 

//$ruleIsValid = $rule->validate(Mage::helper('checkout'));
   $ruleIsValid = $rule->getIsActive();

**Comment by vagnervst** [comment]
Olá @redati, somente a linha que importa o helper foi comentada? Em seus testes, transações parceladas foram feitas com o valor correto? Pois o helper, neste caso, é importado para utilizar a função de formatação dos valores para que remove casas decimais (requisito para a nossa API), comenta-la pode causar conflitos com o parcelamento.

**Comment by redati** [comment]
Sim. Somente essa linha https://github.com/pagarme/pagarme-magento/blob/30a02eccf72d60e3c1df3ee2dfd8978f1b65a8c7/app/code/community/Inovarti/Pagarme/Block/Form/Cc.php#L57

Da função hasCreditCardDiscountRules.

adicionei o $ruleIsValid = $rule->getIsActive(); para 

if ($ruleIsValid && $isPaymentMethodEqual) {
                return true;
            }  
retorna true como esperado.

Recebi dois pedidos parcelados aqui após isso que estão aprovados ja.

**Comment by redati** [comment]
@jonatasmaxi beleza? Voltei um backup de uma versão anterior e esta tudo correndo bem. Peço que apague post por favor, se possível, obrigado pela atenção, grande abraço.

**Comment by andreregino** [comment]
Tive o mesmo problema recentemente e bastou mudar a versão do PHP de 7.0.* para 5.6.*
