### ISSUE TITLE
Erro crítico: Parcelas sem juros cobrando juros??

### ISSUE THREAD

**Issue by davirs** [pagarme/pagarme-magento#27]
o módulo está configurado da seguinte forma:
![config painel](https://cloud.githubusercontent.com/assets/4355062/11004119/9c86547a-849d-11e5-8c26-7778a9442ee2.png)

No pedido ficou assim:
![screenshot_17](https://cloud.githubusercontent.com/assets/4355062/11004432/59f02a26-849f-11e5-9b7a-0633ad0b362a.png)

o valor exibido no parcelamento não bate com o valor total da venda.  Vários clientes relatando este problema.
Não sei se está processando certo no painel da pagarme e retornando errado ou se está processando e retornando errado.

preciso que seja verificado. 
ticket: 6692

@jgabrielfaria

**Comment by charlesalmeida** [comment]
Infelizmente esse Módulo é um fiasco. Muitos problemas.

**Comment by deivisonarthur** [comment]
@charlesalmeida vi em seu perfil que você é programador era para saber dar manutenção a um módulo open source. Caso você seja incapacitado intelectualmente aguarde que iremos abrir uma nova versão brevemente. Então você poderá usa-lo para vender suas lojas em Magento sem programar ;)

**Comment by charlesalmeida** [comment]
@deivisonarthur Infelizmente a empresa @pagarme que forneceu o módulo não deixou claro que seria um Bônus e sim complemento de um serviço. Exemplo disto está home do site deles que eles fornecem integração para Magento.Se o código é aberto ou não, isso não vem ao caso.

**Comment by davirs** [comment]
@deivisonarthur desculpe, te considero pra caramba mas desta vou ter que discordar de você e dar minha opinião sincera... Em algum momento alguém pagou para que esse módulo fosse desenvolvido e paga até hoje pela sua manutenção. Eu mesmo ajudei a pagarme listando vários erros e melhorias e o Enéias Ramos, que é o programador contratado pela pagarme vem resolvendo e aprimorando o módulo de forma excelente. O @filipedeschamps  ou o @jgabrielfaria podem dar mais detalhes sobre isso.

O fato é o seguinte, se a empresa quer trabalhar com pagamento e fornecer esta integração para seus clientes, o mínimo que se espera é um módulo descente, independente se é ou não opensource. lembrando que o CHECKOUT É A ETAPA VITAL para qualquer e-commerce. Lembrando também que o suporte vem acontecendo

@charlesalmeida, concordo contigo. Saber ou não programar não vem ao caso.
Todas as minhas issues vem sido respondidas. Qualquer coisa abre um ticket support@pagarme.zendesk.com

**Comment by charlesalmeida** [comment]
@davirs Tenho Ticket aberto 7242 @filipedeschamps , o problema que o módulo não funciona. Já temos contrato validado  junto @pagarme e estamos aguardando resolver para lançarmos a loja. Que pelo visto não será resolvido muito rapidamente. Vou concluir por aqui meu comentários pois só utilizarei serviços da pagar.me se módulo for desenvolvido por outra empresa.

**Comment by michelbrito** [comment]
@davirs @charlesalmeida acredito que a melhor forma conseguir correções é criando essas issues e se for o caso, entrar em contato com o suporte da pagar.me.
Cobrar melhorias é ótimo pra todo mundo mas não acho justo colocar por agua abaixo o trabalho de pessoas que dedicaram horas para fazer o melhor. 
Pois a forma que foi passada pelo @charlesalmeida termina desmotivando o desenvolvedor.
@charlesalmeida uma dica: começa deixando de usar o seu computador ou smartphone, pois eles também tem erros.

**Comment by davirs** [comment]
@michelbrito da minha parte tudo certo. Como dito acima.

**Comment by eneiasramos** [comment]
Caros,

utilizem as versões atualizadas dos módulos Pagarme e OSC. Pois corrigem esse erro de cálculo de juros do cartão de crédito.

abçs!
