### ISSUE TITLE
Cenário de testes para validação de juros/parcelamento em transações de cartão de crédito não passam

### ISSUE THREAD

**Issue by leonampd** [pagarme/pagarme-magento#289]
## Contexto

Temos alguns cenários de testes e2e que validam a aplicação de juros baseado em parcelas. Estes testes, atualmente, não estão passando no travis-ci. Isso acontece, porque por algum motivo, o usuário já está logado em um dos steps quando não deveria.

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me 3.5.2
* Servidor Linux
* PHP 5.4
* Apache 2.2
* MySQL 5.6

## Passos para reproduzir

1. Suba os containers
2. execute os testes e2e
3. O cenário `When login with registered user` irá disparar uma exception que diz que não foi possível encontrar nenhum elemento chamado `E-mail address`

## Resultado esperado

Que o usuário não esteja logado quando chega neste step

## Resultado atual
O usuário está logado neste step e não deveria.

## Possível correção

Forçar o processo de logout ou, verificar se o usuário já está logado e seguir o fluxo

## Screenshots

https://i.imgur.com/1UhLVOJ.png

**Comment by murilohns** [comment]
Acredito que esses testes já estão sendo cobertos por outros cenários de verificação de juros.

Irei fechar essa Issue, mas se necessário sinta-se a vontade para reabrir
