### ISSUE TITLE
Tratamento de exception incorreto para transações de cartão de crédito com número inválido

### ISSUE THREAD

**Issue by leonampd** [pagarme/pagarme-magento#292]
## Contexto
O tratamento da exception disparada caso o número do cartão de crédito seja inválido está incorreto. 

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me 3.5.4
* Servidor Linux
* PHP 5.4
* Apache 2.2
* MySQL 5.6

## Passos para reproduzir

1. Tentar realizar uma compra, no checkout transparente, com um cartão de crédito com número inválido
2. Uma mensagem de erro com o stack trace de uma exception será exibido

## Resultado esperado
Espera-se que a mensagem de erro seja mostrada ao cliente corretamente.

## Resultado atual
O tratamento de erros implementado está incorreto, causando o problema.
```
2018-05-14T14:21:38+00:00 ERR (3): Warning: json_decode() expects parameter 1 to be string, object given  in /var/www
14T14:21:38+00:00 ERR (3): Notice: Trying to get property of non-object  in 14T14:21:38+00:00 ERR (3): Warning: array_reduce() expects parameter 1 to be array, null given  in /var/www/a
2018-05-14T14:21:38+00:00 DEBUG (7):
```

## Possível correção
Corrigir o tratamento feito no método `PagarMe_CreditCard_Model_Creditcard::generateCard`.

## Screenshots
![screenshot from 2018-05-14 11-24-49](https://user-images.githubusercontent.com/1620107/40003824-b26aa55a-576a-11e8-8969-7cbbccad5530.png)

**Comment by lflimeira** [comment]
O PR https://github.com/pagarme/pagarme-magento/pull/302 resolve essa issue.
