### ISSUE TITLE
Módulo não funciona: Valores dos pedidos errados.

### ISSUE THREAD

**Issue by charlesalmeida** [pagarme/pagarme-magento#30]
Quando realiza um pedido vai corretamente para dashboard pagar.me mas para o painel do magento vai valores sempre inconsistentes, utilizando onestepchekout.com.br, magento 1.9.1.0.

**Comment by eneiasramos** [comment]
Olá @charlesalmeida ! Tudo bem?

Atualize para a última versão disponível no link:

https://github.com/pagarme/pagarme-magento

Att,
