### ISSUE TITLE
Após Boleto pago não altera o Pendente no Pedido

### ISSUE THREAD

**Issue by alanaguiar26** [pagarme/pagarme-magento#312]
Olá,
Eu tenho o módulo configura no meu magento 1.9.3.6, o pagamento confirmado via boleto no pagar.me não muda o status no pedido na loja. Não sei se é um problema ou falta eu configurar algo.

Só fica como pendente o pedido e não consigo Faturar o pedido.

Se alguém puder me ajudar.

* Magento Community 1.9.3.6
* Módulo Pagar.me 0.1.8
* Servidor Linux
* PHP 5.6
* Apache 2.4

**Comment by murilohns** [comment]
Olá @alanaguiar26 , tudo bem?

Acredito que seja algum problema em seu servidor, que esteja bloqueando os _POSTbacks_ de boleto. Você pode ver o erro que tá dando através dessa [rota](https://api.pagar.me/1/transactions/TRANSACTION_ID/postbacks?api_key=SUA_CHAVE_DE_API).

Se tiver dúvidas de como usar essa rota, me diz o ID de uma transação com esse problema e eu vejo pra você

Fico no aguardo

**Comment by alanaguiar26** [comment]
Bom dia,


Não sei se é bloqueio no servidor, pois eu estava utilizando o opencart neste mesmo servidor com cloudflare e estava ok.

Eu consegui abrir a pagina de postback.


Se você quiser ver a transação é 46295514, ontem eu consegui mudar o status dela clicando em adicionar envio, ficou como processando.

No painel do Magento em detalhes do pedido quando eu clicava no id da transação ele abria uma janela mostrando que estava pago, mas não mudava o status do pedido.


[cid:131f056d-5637-431e-bad3-5ee05b8f5738]


Eu fiz um novo pedido de teste ontem com valor menor e paguei o boleto, estou esperando compensar o boleto a transação é #46408789.


[cid:042f8d7c-3500-43e8-8184-9d70ba7ec320]

________________________________
De: Murilo Henrique Nascimento Souza <notifications@github.com>
Enviado: segunda-feira, 2 de julho de 2018 09:19
Para: pagarme/pagarme-magento
Cc: alanaguiar26; Mention
Assunto: Re: [pagarme/pagarme-magento] Após Boleto pago não altera o Pendente no Pedido (#312)


Olá @alanaguiar26<https://github.com/alanaguiar26> , tudo bem?

Acredito que seja algum problema em seu servidor, que esteja bloqueando os POSTbacks de boleto. Você pode ver o erro que tá dando através dessa rota<https://api.pagar.me/1/transactions/TRANSACTION_ID/postbacks?api_key=SUA_CHAVE_DE_API>.

Se tiver dúvidas de como usar essa rota, me diz o ID de uma transação com esse problema e eu vejo pra você

Fico no aguardo

**Comment by murilohns** [comment]
Fala @alanaguiar26 , tudo bem?

Qual versão do Módulo você tem instalada?

Pelo que vi, os _POSTbacks_ estão tendo resposta HTTP 503 de seu servidor. Isso acontece pois o magento está tentando mudar o pedido para Pago, mas não está conseguindo, devido à algum fluxo errado, do pedido, ou algo parecido com isso.

Fico no aguardo

**Comment by alanaguiar26** [comment]
Módulo Inovarti_Pagarme - Versão 0.1.8

[image1.png]

Em 3 de jul de 2018, à(s) 10:33, Murilo Henrique Nascimento Souza <notifications@github.com<mailto:notifications@github.com>> escreveu:


Fala @alanaguiar26<https://github.com/alanaguiar26> , tudo bem?

Qual versão do Módulo você tem instalada?

Pelo que vi, os POSTbacks estão tendo resposta HTTP 503 de seu servidor. Isso acontece pois o magento está tentando mudar o pedido para Pago, mas não está conseguindo, devido à algum fluxo errado, do pedido, ou algo parecido com isso.

Fico no aguardo

**Comment by alanaguiar26** [comment]
eu desativei o cloudflare agora, pra ver se chega o postback.

pelo que eu vi ele tenta novamente.


Eu tinha problemas de postback no cloudflare utilizando o pagseguro, mas com pagarme utilizando o opencart nunca tive problemas e  se eu não me engano no cartão de crédito recebo normalmente.


O problema do pagseguro resolvi adicionando os IPs deles no firewall do cloudflare.


________________________________
De: Alan Aguiar <aln.aguiar@hotmail.com>
Enviado: terça-feira, 3 de julho de 2018 10:47
Para: pagarme/pagarme-magento
Cc: pagarme/pagarme-magento; Mention
Assunto: Re: [pagarme/pagarme-magento] Após Boleto pago não altera o Pendente no Pedido (#312)

Módulo Inovarti_Pagarme - Versão 0.1.8

[image1.png]

Em 3 de jul de 2018, à(s) 10:33, Murilo Henrique Nascimento Souza <notifications@github.com<mailto:notifications@github.com>> escreveu:


Fala @alanaguiar26<https://github.com/alanaguiar26> , tudo bem?

Qual versão do Módulo você tem instalada?

Pelo que vi, os POSTbacks estão tendo resposta HTTP 503 de seu servidor. Isso acontece pois o magento está tentando mudar o pedido para Pago, mas não está conseguindo, devido à algum fluxo errado, do pedido, ou algo parecido com isso.

Fico no aguardo

**Comment by alanaguiar26** [comment]
Acho que descobri o problema, estava na sequencia de ID das faturas no banco de dados, não sei porque ele estava puxando uma sequencia já existente. renomeei no banco de dados a sequencia e voltou a funcionar.


SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '300000001' for key 'UNQ_SALES_FLAT_INVOICE_INCREMENT_ID', query was: INSERT INTO `sales_flat_invoice`

Só a transação 46295514 que eu acho que não tem mais tentativas de retorno néh do postback, pois é mais antiga. Se você conseguir enviar novamente.


Agora esta ok.



________________________________
De: Alan Aguiar <aln.aguiar@hotmail.com>
Enviado: terça-feira, 3 de julho de 2018 11:34
Para: pagarme/pagarme-magento
Cc: pagarme/pagarme-magento; Mention
Assunto: Re: [pagarme/pagarme-magento] Após Boleto pago não altera o Pendente no Pedido (#312)


eu desativei o cloudflare agora, pra ver se chega o postback.

pelo que eu vi ele tenta novamente.


Eu tinha problemas de postback no cloudflare utilizando o pagseguro, mas com pagarme utilizando o opencart nunca tive problemas e  se eu não me engano no cartão de crédito recebo normalmente.


O problema do pagseguro resolvi adicionando os IPs deles no firewall do cloudflare.


________________________________
De: Alan Aguiar <aln.aguiar@hotmail.com>
Enviado: terça-feira, 3 de julho de 2018 10:47
Para: pagarme/pagarme-magento
Cc: pagarme/pagarme-magento; Mention
Assunto: Re: [pagarme/pagarme-magento] Após Boleto pago não altera o Pendente no Pedido (#312)

Módulo Inovarti_Pagarme - Versão 0.1.8

[image1.png]

Em 3 de jul de 2018, à(s) 10:33, Murilo Henrique Nascimento Souza <notifications@github.com<mailto:notifications@github.com>> escreveu:


Fala @alanaguiar26<https://github.com/alanaguiar26> , tudo bem?

Qual versão do Módulo você tem instalada?

Pelo que vi, os POSTbacks estão tendo resposta HTTP 503 de seu servidor. Isso acontece pois o magento está tentando mudar o pedido para Pago, mas não está conseguindo, devido à algum fluxo errado, do pedido, ou algo parecido com isso.

Fico no aguardo

**Comment by murilohns** [comment]
Fala @alanaguiar26, obrigado pelo retorno. Fico feliz que tenha conseguido arrumar! =D

Reenviei o _POSTback_ para a transação 46295514, ela deve estar atualizada em sua plataforma, ok?

Vou fechar essa Issue, mas sinta-se à vontade para reabri-la se precisar =D
