### ISSUE TITLE
Cálculo de parcelas no front-end não atualizam de acordo com descontos e acréscimos

### ISSUE THREAD

**Issue by DevMoustache** [pagarme/pagarme-magento#329]
## Contexto

Valores de Desconto ou Acréscimo não estão sendo exibidos corretamente na simulação de Parcelas.

Apesar da exibição errada, quando vamos finalizar a compra o valor é contabilizado e cobrado corretamente.

## Ambiente

Magento Community 1.9.3.3
Módulo Pagar.me v2
Módulo OneStepCheckout 2.0.3

## Passos para reproduzir

1. Na tela de checkout, escolher um frete cobrado ou aplicar um cupom de desconto.

## Resultado esperado

As parcelas devem ser montadas de acordo com o valor total do pedido, e não só o valor singular dos produtos.

## Resultado atual

As parcelas são calculadas com base no valor do pedido sem descontos / acréscimos.

## Possível correção

Como correção rápida, puxei os valores de descontos e acréscimos no arquivo de cálculo de parcelas, mas os valores corretos deveriam vir direto do helper do plugin.

Arquivo:
\app\design\frontend\base\default\template\pagarme\form\credit_card.phtml

Ajuste:
![parcelas](https://user-images.githubusercontent.com/42074515/43737778-d944587c-9998-11e8-9b23-4f8b35f2d555.png)

## Screenshots

Erro:
![print_parcelas](https://user-images.githubusercontent.com/42074515/43737802-ef152d5c-9998-11e8-825d-ada5a33c2d8a.png)

**Comment by murilohns** [comment]
Acredito que esteja relacionada à issue #220
