### ISSUE TITLE
Pedidos recusados pelo payment provider não deveriam chegar na tela de sucesso

### ISSUE THREAD

**Issue by leonampd** [pagarme/pagarme-magento#343]
## Contexto

Quando uma tentativa de compra com dados de cartão inválidos por exemplo, é recusada pelo _payment provider_ o comprador é direcionado para a tela de sucesso.

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me 3.14.3

## Passos para reproduzir

1. Acesse a loja com um usuário válido
2. Inicie o processe de compra de um produto
3. Durante o checkout no bloco de pagamento informe os dados de cartão com data de expiração inválida. Exemplo: `0215 => Fev/2015`

## Resultado esperado

Mensagem de erro informando problemas na autorização e nenhum pedido criado na plataforma.

## Resultado atual

Direcionamento do usuário para a tela de sucesso e pedido criado na plataforma com status recusado.

## Possível correção

Em casos onde o módulo estiver configurado para criar transações _sync_, disparar uma exception caso a transação seja recusada pelo _payment provider_.

**Comment by murilohns** [comment]
Resolvido no #344
