### ISSUE TITLE
[Mr M] Checkout Pagar.me não exibe as parcelas por problema na configuração

### ISSUE THREAD

**Issue by vagnervst** [pagarme/pagarme-magento#345]
## Contexto
Quando uma compra não ultrapassa o valor mínimo para parcela configurado na sessão de Checkout Pagar.me, as parcelas não são exibidas no Checkout Pagar.me, fazendo com que o fluxo de compra não prossiga para a página de sucesso.

## Ambiente

* Magento Community 1.9.1.0
* Módulo Pagar.me 0.1.8
* Valor mínimo para parcela do Checkout Pagar.me maior que o total do pedido

## Passos para reproduzir

1. Configure o valor mínimo da parcela com um número alto (ex: R$200)
2. Compre um produto de R$100
3. Veja se o Checkout exibe as parcelas

## Resultado esperado
Enviar `installments` como `1`.

## Resultado atual
Installments é enviado como `""`.

**Comment by murilohns** [comment]
Por que deve ser enviado como 1, sendo que o valor mínimo da parcela é R$100?

O correto não seria exibir ao usuário uma mensagem parecida com: "O valor mínimo da compra é de R$100"?

**Comment by murilohns** [comment]
Isso não será corrigido no módulo antigo.
O módulo atual (Branch v2) já corrige esse problema.
