### ISSUE TITLE
Sistema de locação. Checkout dando "value" is required.

### ISSUE THREAD

**Issue by SuicideVillan** [pagarme/pagarme-magento#346]
No checkout surge o alerta `"value" is required.` Sem o recurso Antifraude o alerta passa a ser `child "external_id" fails because ["external_id" is required].`– Imaginei ser a versão da API ou o módulo de locação.

Magento 1.9
Pagar.me 0.1.8
Módulo SalesIgniter – rentalbooking

**Comment by leonampd** [comment]
Oi @SuicideVillan tudo bem? Pode esclarecer melhor o problema, por favor? Para que nossos times consigam lhe ajudar de forma mais assertiva é ideal que os tópicos abaixo sejam preenchidos:

## Passos para reproduzir

[lista organizada de processos para reproduzir a issue, por exemplo:]

1. Acesse o painel administrativo do Magento
2. Clique em `Sistema > Configurações > Métodos de Pagamento`
3. Encontre a sessão `PagarMe - Configurações`
4. Informe uma API KEY e uma Encryption Key
5. Salve a configuração

## Resultado esperado

[descreva o resultado esperado para a execução do processo]

## Resultado atual

[descreva o que atualmente está ocorrendo com a execução do processo e explique o problema]

**Comment by murilohns** [comment]
Fala @SuicideVillan , tudo bem?

Por favor, entre em contato com relacionamento@pagar.me e solicite a troca de sua versão de API para 2017-07-17.

A mensagem deve ser enviada pelo mesmo e-mail cadastrado na [dashboard](https://dashboard.pagar.me).
