### ISSUE TITLE
Nome do Portador incorreto na tela do pedido

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#348]
## Contexto

Mesmo preenchendo um _nome do portador_ diferente na finalização de compra, aparece o _nome do cliente_ no bloco de informações de pagamento, na tela do pedido.

## Ambiente

* Magento Community 1.9.3.4
* Módulo Pagar.me 3.14.5
* Servidor Linux
* PHP 7.0
* Apache 2.4
* MySQL 5.7
* Redis

## Passos para reproduzir

1. Realize um pedido via cartão de crédito, preenchendo o um portador diferente do nome do cliente
2. Acesse o pedido no painel administrativo do Magento
3. Verifique o nome do portador no bloco de informações de pagamento

## Resultado esperado

O bloco de informações de pagamento deve exibir o nome do portador, preenchido na finalização do pedido.

## Resultado atual

O bloco de informações de pagamento exibe o nome do cliente.

**Comment by murilohns** [comment]
Olá @rafaelpatro, esse problema faz referência à branch v2 ou à master?

**Comment by rafaelpatro** [comment]
V2

**Comment by murilohns** [comment]
Obrigado pela informação Rafael!

Vamos corrigir o problema assim que possível =)

**Comment by murilohns** [comment]
Corrigido no #370
