### ISSUE TITLE
Opção de Captura Parcial

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#349]
## Contexto

Bom dia! Gostaria de sugerir a opção de captura parcial para pagamentos via cartão de crédito.
Eventualmente um ou mais itens pedidos estão avariados ou vencidos, impossibilitando o envio. Então pode ser realizado um contato com o cliente, avaliando a captura parcial do pedido.

## Passos para reproduzir

1. O cliente realiza um pedido de 10 itens, via cartão de crédito
2. Ao separar a compra, o lojista identifica um dos itens vencido
3. O lojista contata o cliente, oferecendo a captura parcial, ou substituição, ou cancelamento
4. O cliente opta pela captura parcial, e envio dos itens disponíveis
5. Ao faturar o pedido, o lojista poderia ajustar a quantidade do item vencido para zero, na tela de confirmação de pagamento

## Resultado esperado

Permitir a captura parcial, ajustando o campo quantidade, na tela de confirmação de pagamento.

## Resultado atual

A tela não permite editar os campos de quantidade.

## Possível correção

* Adicionar a variável `$_canCapturePartial`, e manter o workflout de captura do Magento compatível, utilizando o parâmetro `$amount` para obter o valor de captura.
https://github.com/pagarme/pagarme-magento/blob/8b2008db4ac206fc82dd8d1d554c34af230e010b/app/code/community/PagarMe/CreditCard/Model/Creditcard.php#L26

### Módulo com canCapturePartial desativado:
![image](https://user-images.githubusercontent.com/13813964/46351719-66c85380-c62e-11e8-97d4-aa50e22e77ff.png)

### Módulo com canCapturePartial ativado:
![image](https://user-images.githubusercontent.com/13813964/46351581-1650f600-c62e-11e8-90a4-dc99f2b6d7c1.png)

**Comment by murilohns** [comment]
Corrigido no PR #359 
a feature pode ser acessada a partir da versão 3.15.0 do módulo
