### ISSUE TITLE
Notificação automática de pagamento aprovado não funciona

### ISSUE THREAD

**Issue by davirs** [pagarme/pagarme-magento#35]
Quando um pagamento é feito com cartão de crédito e é aprovado, não está enviando a notificação de pagamento aprovado para o cliente.

![screenshot_15](https://cloud.githubusercontent.com/assets/4355062/11638827/1a319332-9d10-11e5-8c71-3fd0a721d94e.png)

![screenshot_17](https://cloud.githubusercontent.com/assets/4355062/11638975/fe420bec-9d10-11e5-8fb7-323ce1ec684e.png)

O magento está configurado para capturar/autorizar
![screenshot_16](https://cloud.githubusercontent.com/assets/4355062/11638874/5a3b2b5a-9d10-11e5-9d7a-6b0c3f870ac9.png)

OBS: Boleto as nofiticações estão OK.

@jgabrielfaria 
@eneiasramos 
@filipedeschamps

**Comment by SocialGroups** [comment]
Problema solucionado na última versão do nosso módulo disponível no master =D
