### ISSUE TITLE
Devolução/Reembolso inconsistente

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#350]
## Contexto

O reembolso não está registrando os valores corretos.
Segue a [documentação oficial do Magento](https://docs.magento.com/m1/ce/user_guide/order-processing/credit-memo-create.html) para melhor compreensão do assunto.

_Obs.: Ciente de que o módulo não oferece reembolso online, o problema citado também afeta os registros da loja, relatórios, etc._

## Ambiente

* Magento Community 1.9.3.4
* Módulo Pagar.me 3.14.5 (branch V2)
* Servidor Linux
* PHP 7.0
* Apache 2.4
* MySQL 5.7
* Redis

## Passos para reproduzir

1. Acesse o painel administrativo do Magento
1. Abra um pedido confirmado/capturado
1. Clique na aba _Invoices_, e acesse a fatura paga
1. Clique no botão _Refund_ (outras traduções: _Reembolsar, Credit Memo_)
1. Verifique valores inconsistentes nos totais
1. Salve o reembolso
1. Verifique os totais incorretos no pedido

## Resultado esperado

Sem qualquer ajuste manual, o formulário de reembolso deveria exibir o valor integral da compra.

## Resultado atual

O total registrado no reembolso é zero, ou igual ao valor dos juros (quando há juros no pedido).

### Como é exibido o formulário de reembolso:
![image](https://user-images.githubusercontent.com/13813964/46359811-66d14f00-c640-11e8-8649-e6d9efcc5a5a.png)

### Como deveria ser exibido o formulário de reembolso:
![image](https://user-images.githubusercontent.com/13813964/46359933-a9932700-c640-11e8-87d5-d3a8818e5633.png)

### Como é exibido o pedido após o reembolso:
![image](https://user-images.githubusercontent.com/13813964/46360210-5a012b00-c641-11e8-93b5-c60a46bb8c50.png)

### Como deveria ser exibido o pedido após o reembolso:
![image](https://user-images.githubusercontent.com/13813964/46360351-96348b80-c641-11e8-8133-78eed5bc1309.png)

**Comment by rafaelpatro** [comment]
## Possível correção

Trabalhar com o parâmetro `$amount` disponível no [workflow de reembolso](https://github.com/OpenMage/magento-mirror/blob/1ed39d11b6c40b1e9a05d933460b97f4d021baef/app/code/core/Mage/Payment/Model/Method/Abstract.php#L491) do Magento.

    public function refund(Varien_Object $payment, $amount)

**Comment by rafaelpatro** [comment]
Ok.
Então o problema é só na minha loja. Vou tentar desativar alguns módulos, começando pelo antigo módulo.

**Comment by murilohns** [comment]
Show Rafael!

Vou instalar o módulo antigo ao lado do v2 para verificar se é incompatibilidade entre eles de fato!

**Comment by rafaelpatro** [comment]
Boa tarde @murilohns
Vc testou no mesmo ambiente que descrevi acima? O compilador estava ativo? (no meu caso, não)

Fiz mais alguns testes aqui.

1. Desativado módulo Pagarme 0.1.6:  **O erro persiste!**
```xml
<config>
    <modules>
        <Inovarti_Pagarme>
            <active>false</active>
            <codePool>community</codePool>
            <depends>
                <Mage_Payment />
            </depends>
        </Inovarti_Pagarme>
    </modules>
</config>
```
1. Desativado Boleto Pagarme 3.14.6: **O erro persiste!**
```xml
<config>
    <modules>
        <PagarMe_Boleto>
            <active>false</active>
            <codePool>community</codePool>
            <depends>
                <PagarMe_Core />
            </depends>
        </PagarMe_Boleto>
    </modules>
</config>
```
1. Desativado Cartão Pagarme 3.14.6: **O erro desaparece!**
```xml
<config>
    <modules>
        <PagarMe_CreditCard>
            <active>false</active>
            <codePool>community</codePool>
            <depends>
                <PagarMe_Core />
            </depends>
        </PagarMe_CreditCard>
    </modules>
</config>
```

Obs.: Enquanto o módulo _PagarMe_CreditCard_ está ativo, o reembolso dá problema em todos os outros módulos de pagamento.

Enfim, acho q o problema está relacionado ao módulo de cartão. Reparei que vcs trabalham com um autoloader. É possível que alguma classe esteja interferindo no reembolso?

**Comment by rafaelpatro** [comment]
Fiz uma busca por _adminhtml_sales_order_creditmemo_new_ nos meus arquivos, e reparei que o PagarMe_CreditCard é o único módulo terceiro que interage com a tela _New Credit Memo_.
```xml
    <adminhtml_sales_order_creditmemo_new>
        <reference name="creditmemo_totals">
            <block type="pagarme_creditcard/sales_RefundTransaction" name="pagarme_creditcard.refundtransaction"/>
        </reference>
    </adminhtml_sales_order_creditmemo_new>
```

É provável que o problema tenha origem na classe _PagarMe_CreditCard_Block_Sales_RefundTransaction_.

**Comment by murilohns** [comment]
Fala @rafaelpatro, o problema é de compatibilidade entre o Módulo da branch master, e o módulo da branch v2.

![image](https://user-images.githubusercontent.com/18074134/46552055-d8630480-c8af-11e8-8160-9d39ecf68b9e.png)

Estou investigando o que está causando essa incompatibilidade

**Comment by murilohns** [comment]
Corrigido no PR #357 

A correção pode ser acessada a partir da versão 3.14.7
