### ISSUE TITLE
Estorno parcial pela plataforma

### ISSUE THREAD

**Issue by murilohns** [pagarme/pagarme-magento#351]
## Contexto

Estorno parcial pela plataforma.

Com essa feature, é possível que o cliente devolva um produto do pedido dele, e apenas o valor desse produto seja estornado.

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me 3.14.5
* Ambiente docker do módulo

## Passos para reproduzir

1. Crie um pedido com mais de 1 produto.
2. Acesse o `painel administrador > pedidos` e selecione o pedido que foi criado.
3. Acesse as invoices deste pedido
4. Tente estorná-lo parcialmente.

## Resultado esperado
Selecionar os produtos à serem estornados
![image](https://user-images.githubusercontent.com/18074134/46366928-b1f45d80-c652-11e8-9ae2-d1cf9a2e5599.png)

## Resultado atual
Não é possível selecionar os produtos que serão estornados.
![image](https://user-images.githubusercontent.com/18074134/46366947-c33d6a00-c652-11e8-866f-4e2721a94728.png)

## Possível correção

Utilizar o parâmetro `$_canCapturePartial` na classe `PagarMe_CreditCard_Model_Creditcard`

**Comment by rafaelpatro** [comment]
```php
protected $_canRefundInvoicePartial = true;

**Comment by rafaelpatro** [comment]
Melhor ainda se estornasse junto ao adquirente.

**Comment by murilohns** [comment]
Corrigido no PR #365 
a feature pode ser acessada a partir da versão 3.15.0 do módulo

**Comment by rafaelpatro** [comment]
Boa tarde @murilohns 
Gostaria de sugerir o reembolso parcial para os boletos também.
