### ISSUE TITLE
Pedidos pendentes não aparecem para o cliente no frontend

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#354]
## Contexto

Os pedidos finalizados através do módulo Pagar.me não aparecem na tela de pedidos do cliente, no frontend. Apenas após a confirmação do pagamento, é que a compra é listada para o cliente no frontend.

## Ambiente

* Magento Community 1.9.3.4
* Módulo Pagar.me 3.14.6
* Servidor Linux
* PHP 7.0
* Apache 2.4
* MySQL 5.7
* Redis

## Passos para reproduzir

1. Realize uma compra via boleto pelo frontend
1. Acesse a tela de pedidos
1. Verifique que a compra não consta na lista de pedidos
1. Acesse o painel administrativo do Magento, em _Sales > Orders_
1. Verifique que a compra consta na lista de pedidos
1. Acesse o pedido, e confirme o pagamento
1. O registro agora deve aparecer na tela de pedidos do cliente

## Resultado esperado

O pedido deveria ser exibido na tela de pedidos recentes.

## Resultado atual

O pedido não é exibido em lugar algum no frontend.

**Comment by rafaelpatro** [comment]
## Possível correção

Configurar os novos pedidos para outro status, exceto `pending_payment`.

Ou ativar a exibição pela tag visible_on_front:
```xml
<config>
    <global>
        <sales>
            <order>
                <states>
                    <pending_payment translate="label">
                        <visible_on_front>1</visible_on_front>
                    </pending_payment>
                </states>
            </order>
        </sales>
    </global>
</config>
```

**Comment by murilohns** [comment]
Corrigido no PR #360
a feature pode ser acessada a partir da versão 3.15.0 do módulo
