### ISSUE TITLE
Disable/Enable Place Order Button

### ISSUE THREAD

**Issue by golifter** [pagarme/pagarme-magento#37]
Olá,
Verifiquei que o módulo adiciona uma clase "disable" no botão antes de preenchermos os dados do cartão, mas ele não remove a mesma classe após o preenchimento dos dados.

Estou usando o OSC 6

Obrigado

**Comment by digitalvoip** [comment]
Olá, por acaso é uma tela como esta anexa que lhe aparece? Esta tela está aparecendo pra mim.
Também uso o OSC 6 e o CheCkoutVendaMais disponibilizado grátis pelo http://ipagare.com

Já testei com o OSC desativado e ativado...dá na mesma.. não faço idéia do que pode estar gerando isso e onde intervir.

Se puder ajudar, Grato.
![tela](https://cloud.githubusercontent.com/assets/15305033/12311318/3647b834-ba35-11e5-82c5-aa8a4c18a611.jpg)

**Comment by eneiasramos** [comment]
Olá @golifter ! Tudo bem?

Atualize o seu módulo para a última versão disponível no link:

https://github.com/pagarme/pagarme-magento

Att,
