### ISSUE TITLE
Erro de card_hash inválido

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#371]
## Contexto

Alguns clientes estão enfrentando problemas com o card_hash, após qualquer falha na tentativa de finalização da compra com cartão.

## Ambiente

* Magento Community 1.9.3.10
* Módulo Pagar.me 3.15.0
* Servidor Linux
* PHP 7.0
* Apache 2.4
* MySQL 5.7

## Passos para reproduzir

1. Acesse a loja e adicione algum item ao carrinho de compras
1. Prossiga até a etapa de finalização
1. Preencha algum campo com um valor inválido (CEP, Telefone, CPF, etc)
1. Preencha o formulário do cartão com dados válidos
1. Clique para finalizar a compra
1. O erro de campo inválido deve aparecer
1. Corrija o campo inválido
1. Retorne ao carrinho, pois vc lembrou que precisa de mais um item
1. Após 5 minutos, retorne à página de finalização
1. Prossiga o fluxo de compra até a última etapa, utilizando os mesmos dados do cartão
1. Clique para finalizar a compra
1. O erro de card_hash inválido deve aparecer

## Resultado esperado

Na tela de finalização de compra, ao voltar uma etapa, ou ao voltar ao carrinho, após um erro de campo inválido, e após corrigir o erro, a compra deveria ser finalizada sem maiores problemas.

## Resultado atual

O erro de _card_hash_ inválido é exibido na tela, e ainda orienta o cliente a consultar a documentação da API do Pagar.me

**Comment by murilohns** [comment]
fala @rafaelpatro, desculpa a falta de atualização.

Estamos investigando esse problema, e assim que possível a correção será lançada

**Comment by murilohns** [comment]
corrigido na #375
