### ISSUE TITLE
Erro no checkout

### ISSUE THREAD

**Issue by tiagoexe** [pagarme/pagarme-magento#374]
olá, bom dia!
alguém sabe do que se trata esse erro? ele acontece no checkout quando o modulo pagar.me esta habilitado.

There has been an error processing your request
Invalid header line detected

Trace:
#0 /home/danitagraa/public_html/lib/Zend/Http/Response.php(696): Zend_Http_Response::extractHeaders('HTTP/2 200 \r\nda...')
#1 /home/danitagraa/public_html/lib/Zend/Http/Client.php(1110): Zend_Http_Response::fromString('HTTP/2 200 \r\nda...')
#2 /home/danitagraa/public_html/lib/Varien/Http/Client.php(61): Zend_Http_Client->request(NULL)
#3 /home/danitagraa/public_html/app/code/community/Inovarti/Pagarme/Model/Api.php(250): Varien_Http_Client->request()
#4 /home/danitagraa/public_html/app/code/community/Inovarti/Pagarme/Model/Api.php(206): Inovarti_Pagarme_Model_Api->request('https://api.pag...', Object(Varien_Object))
#5 /home/danitagraa/public_html/app/code/community/Inovarti/Pagarme/Model/Abstract.php(217): Inovarti_Pagarme_Model_Api->calculateInstallmentsAmount(Object(Varien_Object))
#6 /home/danitagraa/public_html/app/code/community/Inovarti/Pagarme/Block/Form/Cc.php(97): Inovarti_Pagarme_Model_Abstract->getAvailableInstallments('940', Object(Varien_Object), Object(Inovarti_Pagarme_Model_Api))
#7 /home/danitagraa/public_html/app/design/frontend/base/default/template/pagarme/form/cc.phtml(35): Inovarti_Pagarme_Block_Form_Cc->getInstallmentsAvailables()
#8 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/danitagra...')
#9 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#10 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#11 /home/danitagraa/public_html/app/code/core/Mage/Payment/Block/Form/Cc.php(157): Mage_Core_Block_Template->_toHtml()
#12 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Payment_Block_Form_Cc->_toHtml()
#13 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#14 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('payment.method....', true)
#15 /home/danitagraa/public_html/app/code/core/Mage/Checkout/Block/Onepage/Payment/Methods.php(72): Mage_Core_Block_Abstract->getChildHtml('payment.method....')
#16 /home/danitagraa/public_html/app/design/frontend/add/store/template/onestepcheckout/onestep/form/payment_method.phtml(29): Mage_Checkout_Block_Onepage_Payment_Methods->getPaymentMethodFormHtml(Object(Inovarti_Pagarme_Model_Cc))
#17 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/danitagra...')
#18 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/add/st...')
#19 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#20 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#21 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#22 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('paymentmethod', true)
#23 /home/danitagraa/public_html/app/design/frontend/add/store/template/onestepcheckout/onestep.phtml(28): Mage_Core_Block_Abstract->getChildHtml('paymentmethod')
#24 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/danitagra...')
#25 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/add/st...')
#26 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#27 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#28 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#29 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Text_List->_toHtml()
#30 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#31 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#32 /home/danitagraa/public_html/app/design/frontend/add/store/template/page/1column.phtml(49): Mage_Core_Block_Abstract->getChildHtml('content')
#33 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/danitagra...')
#34 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/add/st...')
#35 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#36 /home/danitagraa/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#37 /home/danitagraa/public_html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#38 /home/danitagraa/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#39 /home/danitagraa/public_html/app/code/community/Inovarti/Onestepcheckout/controllers/IndexController.php(68): Mage_Core_Controller_Varien_Action->renderLayout()
#40 /home/danitagraa/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Inovarti_Onestepcheckout_IndexController->indexAction()
#41 /home/danitagraa/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#42 /home/danitagraa/public_html/app/code/local/Webnstack/SystemConfig/Controller/Router/Standard.php(20): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#43 /home/danitagraa/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Webnstack_SystemConfig_Controller_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#44 /home/danitagraa/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#45 /home/danitagraa/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#46 /home/danitagraa/public_html/index.php(83): Mage::run('', 'store')
#47 {main}

Error log record number: 333088607071

**Comment by murilohns** [comment]
oi @jonatasmaxi , qual o caminho desse arquivo que preciso modificar?

**Comment by tiagoexe** [comment]
Muito obrigado, resolveu o meu problema

valeu mesmo

Em ter, 13 de nov de 2018 às 12:53, Murilo Henrique Nascimento Souza <
notifications@github.com> escreveu:

**Comment by rabraga** [comment]
@jonatasmaxi,
Também estou com o mesmo erro. Qual o local do arquivo para atualização?
