### ISSUE TITLE
E-mail de confirmação de pagamento duplicado

### ISSUE THREAD

**Issue by diogodaluz** [pagarme/pagarme-magento#379]
## Contexto

No Magento está configurado para mandar uma cópia da confirmação de pagamento (e também do pedido) para o e-mail do administrador da loja.

> Quando o módulo do Pagar-me está configurado para "enviar e-mail da fatura" o administrador da loja recebe 2 X o e-mail da confirmação da compra e o cliente final recebe 1 X.
> Quando o módulo do Pagarme está configurado para NÃO enviar e-mail da fatura, o administrador da loja recebe 1X o e-mail da confirmação da compra e o cliente final NÃO recebe.

## Ambiente
Módulo Inovarti_Pagarme - Versão 0.1.6
Magento 1.9.3.1

**Comment by murilohns** [comment]
oi @diogodaluz, o próprio magento deveria fazer o gerenciamento desses e-mails.

Você pode configurar quando cada e-mail será enviado neste menu:
![image](https://user-images.githubusercontent.com/18074134/53104518-441bd600-350e-11e9-9a29-38e291c441bf.png)
