### ISSUE TITLE
Nossa loja retorna ERR (3): Warning: curl_setopt() expects exactly 3 parameters, 2 given  in 

### ISSUE THREAD

**Issue by Samuel291** [pagarme/pagarme-magento#380]
https://github.com/pagarme/pagarme-magento/blob/c94363f838509fcb33e462c4b86208d3f9db8c37/app/code/community/Inovarti/Pagarme/Block/Adminhtml/Notifications.php#L38

**Comment by Samuel291** [comment]
Provavelmente o código correto seria:
$defaults = array(
            CURLOPT_URL => 'https://api.github.com/repos/pagarme/pagarme-magento/releases',
            CURLOPT_HTTPHEADER => $headers,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FAILONERROR => false
  );
        $ch = curl_init();
        curl_setopt_array($ch,  $defaults);

**Comment by Samuel291** [comment]
Fiz essa alteração e esse erro parou de ser gerado no log system.log

**Comment by jonatasmaxi** [comment]
Oi Samuel, tudo bom?

Muito obrigado pelas considerações. De fato, este erro acontece em algumas instalações do Magento porém como os releases lançados no github hoje são de um outro módulo, orientamos os clientes a remover o trecho de código. Ainda assim, vou aplicar essas modificações por aqui e abrir um Pull Request para o time responsável revisar essa questão, tudo bem? 

Qualquer dúvda estou por aqui.

**Comment by Samuel291** [comment]
Tudo bem, no caso os novos arquivos estarão ou já estão disponíveis aqui no github?

**Comment by murilohns** [comment]
Olá @Samuel291, a versão que você está utilizando do módulo está depreciada.

Lançamos uma nova versão do módulo, que pode ser baixada em https://github.com/pagarme/pagarme-magento/releases e recomendamos que utilize essa versão.

Dado isso, estarei fechando essa issue, mas sinta-se a vontade pra reabrir se necessário.
