### ISSUE TITLE
Enviar Informações do Pedido para o Pagar.me

### ISSUE THREAD

**Issue by WidecommerceDev** [pagarme/pagarme-magento#381]
Possuímos um cliente em comum que utiliza Magento como plataforma e que gostaria de utilizar a integração da Conta Azul com o Pagar.me. Onde ele já lançaria o pedido do Pagar.me direto para a Conta Azul gerando as NF's. Para isso ele entrou em contato com o atendimento do Pagar.me e o mesmo nos deu a seguinte informação:

**Utilizando a versão que vocês têm hoje vocês já conseguem nos enviar informações sobre a venda no campo "metadata".
Este campo é aberto e vocês conseguem enviar as informações de produto através dele. 
A única questão é que vocês precisariam de um TI ou um DEV do lado de vocês para fazer esta integração, visto que vocês usam Magento que é uma plataforma aberta e a integração da Magento com o Pagar.me é feita através de "plug in".
Segue link da docs: https://docs.pagar.me/v1/reference#criar-transacao**

Minha dúvida é a seguinte. O módulo disponibilizado aqui no github já tem essa funcionalidade? É possível desenvolver isso nesse módulo? Seria por parte nossa, ou vocês poderiam nos ajudar?

**Comment by murilohns** [comment]
Oi @WidecommerceDev , tudo bem?

Pode me dizer qual versão do módulo vocês estão utilizando?

Fico no aguardo.

**Comment by WidecommerceDev** [comment]
Existe essa possibilidade na versão mais atual?

**Comment by murilohns** [comment]
Oi @WidecommerceDev, sim.
Os dados de metadata do pedido são enviados nessa linha para cartão de crédito:
https://github.com/pagarme/pagarme-magento/blob/v2/app/code/community/PagarMe/CreditCard/Model/Creditcard.php#L634
E nessa linha para boleto:
https://github.com/pagarme/pagarme-magento/blob/v2/app/code/community/PagarMe/Bowleto/Model/Boleto.php#L258

Note que em ambos os campos, o dado de _metadata_ é preenchido por um array, e você pode adicionar a informação que precisar nele.

**Comment by WidecommerceDev** [comment]
@murilohns legal. 

E a versão 0.1.8? Também é possível?

Esse tipo de funcionalidade vocês irão lançar num futuro, ou ficaria a cargo de cada loja mesmo?

**Comment by murilohns** [comment]
Oi @WidecommerceDev, sim, é possível

> E a versão 0.1.8? Também é possível?

Para boleto o metadata é enviado nessa linha:
https://github.com/pagarme/pagarme-magento/blob/master/app/code/community/Inovarti/Pagarme/Model/Boleto.php#L54
e para cartão de crédito, é enviado aqui:
https://github.com/pagarme/pagarme-magento/blob/master/app/code/community/Inovarti/Pagarme/Model/Abstract.php#L39
e aqui:
https://github.com/pagarme/pagarme-magento/blob/master/app/code/community/Inovarti/Pagarme/Model/Abstract.php#L119

> Esse tipo de funcionalidade vocês irão lançar num futuro, ou ficaria a cargo de cada loja mesmo?

Essa funcionalidade não será implementada.
A única função do módulo é criar transações no Pagar.me e pedidos no Magento, e gerenciar o fluxo do pedido até que ele esteja como `pago` no Pagar.me.

Toda integração externa ao Magento o módulo não fará, porém, se necessário você pode adaptar o módulo às necessidades de seu sistema =)

**Comment by WidecommerceDev** [comment]
@murilohns Perfeito. Obrigado pelo retorno :)

**Comment by murilohns** [comment]
Vou fechar a issue, mas pode reabri-la se precisar =D
