### ISSUE TITLE
Confirmação e Captura não está somando os Juros

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#387]
# Contexto
Ao configurar parcelamento com juros, o módulo calcula os valores perfeitamente. Mas na Confirmação do Pagamento, o valor dos juros não é somado. Então o valor capturado fica inferior ao valor cobrado no pedido.

# Ambiente
* Magento Community 1.9.3.10
* Módulo Pagar.me 3.15.0
* Servidor Linux
* PHP 7.0
* Apache 2.4
* MySQL 5.7

# Passos para reproduzir
1. Configure o pagamento via cartão de crédito com juros (ex. 2% a partir de 3x).
1. Realize uma compra pelo frontend optando pelo parcelamento em 10x.
1. Acesse o painel administrativo do Magento, e fature/capture o pedido.
1. Verifique que a fatura exibe um montante sem considerar os juros.
1. Acesse o dashboard.pagar.me e verifique que o valor capturado é inferior ao valor cobrado.

# Resultado esperado
O Pagar.me deve capturar o valor integral do pedido, incluindo os juros.

# Resultado atual
O Pagar.me está capturando o montante, sem considerar os juros cobrados no pedido.

# Screenshots
![image](https://user-images.githubusercontent.com/13813964/52717103-744ffb80-2f87-11e9-83d7-11e1241363b8.png)

## Tela do Pedido
![image](https://user-images.githubusercontent.com/13813964/52717192-ae210200-2f87-11e9-8e92-7c49105975a5.png)

## Tela da Fatura
![image](https://user-images.githubusercontent.com/13813964/52717241-d27cde80-2f87-11e9-8163-eee5f44e6a37.png)

## Tela do Dashboard Pagar.me
![image](https://user-images.githubusercontent.com/13813964/52717319-048e4080-2f88-11e9-94c7-d34f1b0856c2.png)

**Comment by murilohns** [comment]
Obrigado por reportar @rafaelpatro.

Enquanto esse problema não é corrigido, peço que capture a transação pela [dashboard](dashboard.pagar.me) para garantir que os juros sejam considerados nessa captura

**Comment by murilohns** [comment]
Corrigido em #388
