### ISSUE TITLE
Lentidão e travamento no CRON para cancelamento de boletos

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#389]
# Contexto
A tarefa do Cron para cancelamento de boletos está enfrentando lentidão, e congestionando a fila de tarefas. O tempo médio de execução da tarefa está em 15 min, atrasando demais outras tarefas não menos importantes.
Acredito que o gargalo esteja no atraso da comunicação pela API Pagar.me. Esse atraso se agrava quando existem muitos boletos pendentes, e o protocolo se repete para cada pedido.

![image](https://user-images.githubusercontent.com/13813964/52973275-42ca9c00-339c-11e9-8d3a-9f869c9a31a9.png)

# Ambiente
* Magento Community 1.9.3.10
* Módulo Pagar.me 3.17.1
* Servidor Linux
* PHP 7.0
* Apache 2.4
* MySQL 5.7

# Possível solução
Seria possível fornecer uma solução massiva? Atualizar um lote de pedidos de boletos?

https://github.com/pagarme/pagarme-magento/blob/97c2e5c319192ea63f698c23bd09b5c1e0eeda4a/app/code/community/PagarMe/Bowleto/Model/UnpaidBoleto.php#L96

**Comment by murilohns** [comment]
Fala @rafaelpatro, o que acha de aumentar o tempo de execução dessa task?

Acredito que se ela rodar duas vezes ao dia já seja o suficiente para cancelar boletos não pagos.

**Comment by rafaelpatro** [comment]
Vou seguir seu conselho. Obrigado
