### ISSUE TITLE
Erro de CEP em compras internacionais.

### ISSUE THREAD

**Issue by r1tt3r** [pagarme/pagarme-magento#39]
Quando algum cliente de fora do Brasil tenta realizar uma compra, ao finalizar o pedido o modulo retorna mensagem de CEP inválido. 

URL: http://www.idoloseternos.com.br

**Comment by SocialGroups** [comment]
Olá Boa tarde tudo bem ?

O que ocorre é que se vocês estivem com o anti fraude habilitado dentro do pagar.me cep`s internacionais não vão funcionar.

Qualquer dúvida estamos a disposição.
Atenciosamente,
Lucas Santos
