### ISSUE TITLE
PagarMe API: Operation timed out for order

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#390]
# Contexto
Gostaria relatar um problema que verifiquei em uma transação específica.

Ao acessar um pedido pago via cartão de crédito, não foi possível verificar qualquer informação no bloco de pagamento.
![image](https://user-images.githubusercontent.com/13813964/53246542-caabf100-368f-11e9-9594-44a65b520a78.png)

Segue registro do _system.log_, no instante da compra:
```log
2019-02-22T10:27:08+00:00 DEBUG (7): PagarMe API: Operation timed out for order 86974
2019-02-22T10:27:26+00:00 DEBUG (7): Order , transaction 77211471 updated to canceled
```
_O registro de exceções exception.log não emitiu qualquer mensagem._

No dashboard.pagar.me a transação foi identificada como _Erro genérico_.
![image](https://user-images.githubusercontent.com/13813964/53247143-5a9e6a80-3691-11e9-81b0-2dd7b51cb932.png)

Registrei outras compras com sucesso na mesma manhã, então acredito que seja um problema pontual.
Mas estou reportando, pois pode haver alguma falha no tratamento de erro do módulo. Talvez no tratamento do _Erro genérico_, ou então no _timed out_.

# Ambiente
* Magento Community 1.9.3.10
* Módulo Pagar.me 3.17.1
* Servidor Linux
* PHP 7.0
* Apache 2.4
* MySQL 5.7

**Comment by murilohns** [comment]
@rafaelpatro, pode me mostrar os histórico de status desse pedido, por favor?

**Comment by rafaelpatro** [comment]
![image](https://user-images.githubusercontent.com/13813964/53249080-01850580-3696-11e9-8d93-0b6b72f8b49d.png)

Cancelei manualmente.

**Comment by leonampd** [comment]
Oi @rafaelpatro td bem?

Brigado pelo report e desculpas pela demora em responder. Estamos endereçando alguns débitos técnicos/melhorias para serem feitas no módulo e pegamos essa issue pra entender melhor o escopo. Olhando no nossos registros vi que para a transação `77211471` o `order_id` atrelado é `100082878`, que bate com o print mas o log menciona a `86974` pra indicar o problema de timeout.

A princípio, parece que houve um problema na atualização do pedido `100082878` via postback e problemas de timeout com outro pedido. Confirma?

**Comment by rafaelpatro** [comment]
Obrigado pelo retorno, @leonampd 

Não. O Magento usa diferentes identificadores para o mesmo registro.
Nesse caso em questão a tabela _sales_flat_order_ possui um registro com `entity_id = 86974` e `increment_id = 100082878`.

**Comment by murilohns** [comment]
Pelo que vi, o pedido teve o comportamento que o módulo propôs, apenas faltam acrescentar algumas coisas ao módulo quando esse timeout ocorrer:

- [ ] Status inicial para o pedido
- [ ] Gravar informações da transação no pedido
- [ ] Realizar testes de postback nesse cenário, para entender o motivo do status do pedido não ter sido atualizado.

**Comment by leonampd** [comment]
@murilohns tbm tem o ponto que o @rafaelpatro levantou. Dado que os ID's são diferentes, a atualização do status não funcionou por isso.
