### ISSUE TITLE
Tentando entender o Módulo

### ISSUE THREAD

**Issue by aquere** [pagarme/pagarme-magento#393]
Oi pessoal!

Estou tentando entender algumas coisas do módulo, porém está bem complicado.

Ao instalar o módulo ele mostra dentro das "Formas de Pagamento" 5 opções para configuração:

- Pargar.me - Configuração
- Pargar.me - Configurações
- Pargar.me - Boleto
- Pargar.me - Cartão de Crédito
- Pargar.me - Checkout

Se eu mantenho a configuração pelas abas Pargar.me - Configuração, Pargar.me - Boleto e Pargar.me - Cartão de Crédito ele funciona perfeitamente com as notificações dos clientes, entretanto não aparece o cartão dentro da página de checkout (o que na minha opinião é muito importante para o entendimento do cliente).

Caso eu configuro o módulo apenas pela aba Pargar.me - Configurações (e desativo as abasa Pargar.me - Boleto e Pargar.me - Cartão de crédito) ele aparece o cartão dentro do checkout, preenche o cartão de acordo com os dados do cliente, porém não notifica o meu cliente do pagamento aprovado ou recusado.

ps. o cartão que eu falo não é a opção modal e sim a do checkout transparente.

Estou utilizando versão 3.18 do Módulo junto com o Firecheckout e Magento 1.9

**Comment by murilohns** [comment]
Olá @aquere, tudo bem?

Você pode seguir esse tutorial de configuração do módulo:
https://docs.pagar.me/v2/docs/instalando-modulo-magento

Gostaria de aproveitar para perguntar: Você possui os dois módulos do Pagar.me instalados? (3.18 e 0.1.8)? Se sim, acredito que isso deva estar gerando confusão em sua configuração.

Fico no aguardo.

**Comment by aquere** [comment]
@murilohns Opa, tudo certo?

Desativei o módulo desenvolvido pela Inovarti, correto?

Ficando apenas a aba do "Pagar.me - Configurações".

Entretanto, o pagamento via cartão de crédito não notifica o cliente o novo pedido, nem o pagamento aprovado ou reprovado. Apenas quando é feito por boleto.

**Comment by murilohns** [comment]
oi @aquere, o próprio magento deveria fazer o gerenciamento desses e-mails.

Você pode configurar quando cada e-mail será enviado em System > Configuration > Sales - Sales E-mails:
![image](https://user-images.githubusercontent.com/18074134/53104518-441bd600-350e-11e9-9a29-38e291c441bf.png)

**Comment by aquere** [comment]
@murilohns Sim, eu entendo. Entretanto, quando utilizo o módulo antigo da Inovarti, ele deixa eu setar qual o Status de Novo Pedido e de Pagamento Aprovado, assim ele conseguia enviar as notificações.

Quando o módulo 3.1.8 está ativado, ele não deixa configurar nada e não altera dentro do Magento quando o pagamento foi aprovado.

Entende?

**Comment by murilohns** [comment]
Olá @aquere, o módulo antigo está com o fluxo de status errado.

**Pedidos pagos** sempre possuirão no status `Processing`
**Pedidos apenas autorizados**, ou boletos apenas gerados estarão em `Pending Payment`
**Pedidos recusados** só serão registrados na plataforma se a opção "transação assíncrona" estiver marcada com "Sim", e eles ficam registrados como 'Cancelled'
Se a opção "transação assíncrona" estiver desabilitada, a mensagem de recusa do pedido será exibida na hora para o cliente, e ele não ficara registrado na plataforma.

**Comment by aquere** [comment]
@murilohns Ótimo! Porém não é algo que está especificado na configuração do módulo e gerou dúvidas para a gente. Vou adequar o fluxo e te passo um feedback! Desde já muito obrigado ;)

**Comment by aquere** [comment]
@murilohns Sabe me dizer qual a URL que eu devo configurar no Postback?

**Comment by murilohns** [comment]
@aquere, essa opção não deve ser configurada à menos que você queira testar o POSTBACK para algum lugar que não seja o site de sua loja.

**Comment by aquere** [comment]
@murilohns Entendi. Entretanto, a minha loja Magento não recebe o status de Pagamento Aprovado e não atualiza o pedido. Ficando somente como pagamento pendente.

**Comment by aquere** [comment]
@murilohns Todos meus pedidos com a AIP Test ficam com status: Pending Payment - Em processamento no gateway. Aguardando resposta

**Comment by murilohns** [comment]
Oi @aquere, pode me enviar a URL de sua loja?

Também gostaria de acrescentar que, para transações de cartão de crédito você pode resolver esse problema alterando a opção "transação assíncrona" para "não"

**Comment by aquere** [comment]
@murilohns Claro! www.vendoguardachuva.com.br

Deixei ativado apenas o módulo novo para você fazer os testes :)

**Comment by murilohns** [comment]
Qual o status do pedido 1600005103 em sua plataforma, @aquere ?

**Comment by aquere** [comment]
Em processamento no gateway. Aguardando resposta

**Comment by murilohns** [comment]
Ok =/
Pode entrar em contato com suporte@pagar.me por favor?

Vamos precisar de informações mais profundas e sensíveis.

Ao enviar o e-mail, pode enviar essa Issue como referência, para que nosso time pegue o contexto do problema, ok?

Qualquer dúvida fico à disposição.

**Comment by aquere** [comment]
@murilohns Acabou de sair um pedido, final 5109 que está como Processing - Valor capturado: R###,##

**Comment by murilohns** [comment]
Vi que você mudou o fluxo, e colocou "transação assícrona" como "não"
Isso faz com que você tenha a resposta do pedido na hora.
Em pedidos pagos com cartão de crédito, pedidos aprovados serão criados com o status `Processing` e compras recusadas não serão registrados na plataforma.

Para boleto, o comportamento continua o mesmo: O pedido é criado como `Pending Payment` e seu status deve ser alterado para `Processing` após o boleto ser pago.

**Comment by aquere** [comment]
@murilohns Sim, conforme tu me orientou. Acredito que está tudo ok agora. Entretanto, já existia outros status de pedidos vinculados ao "Processing" que ele não puxa. Podemos mudar o nome direto desse status padrão do magento sem problemas?

**Comment by murilohns** [comment]
@aquere, sim.

Apenas confira se a transação no Pagar.me está paga antes de alterar o status =)

**Comment by aquere** [comment]
@murilohns Perfeito, muito obrigado pela ajuda!
