### ISSUE TITLE
Número de installments não está sendo gravado no objeto Order Payment

### ISSUE THREAD

**Issue by jonatasmaxi** [pagarme/pagarme-magento#394]
Oi gente, tudo bom?

Essa demanda chegou via case no Salesforce. 

O cliente relata que possui integração com o sistema Ecossys e no objeto Payment do Pedido (Classe Order)  não está sendo gravado corretamente a informação de transações parceladas. 

O nome do parâmetro que eles esperam que contenha informação é cc_installments, parâmetro cujo qual não achei referências no código deste módulo. 

Acho que um bom lugar pra colocar isso é aqui: https://github.com/pagarme/pagarme-magento/blob/97c2e5c319192ea63f698c23bd09b5c1e0eeda4a/app/code/community/PagarMe/CreditCard/Model/Creditcard.php#L437 

Qualquer dúvida estou por aqui.

**Comment by leonampd** [comment]
Pelo que observei não existe um método como o `setCCLast4` para parcelas. Talvez consigamos armazenar essa info em `additional_data`, como foi feito aqui:

https://github.com/pagarme/pagarme-magento/blob/797418e5fea7e0a78abfa92b891599156379f82e/app/code/community/PagarMe/CreditCard/Model/Creditcard.php#L251-L261

**Comment by murilohns** [comment]
Pelo que vi o Magneto fazia algo parecido com `$payment->setInstallments())`:
https://github.com/pagarme/pagarme-magento/blob/master/app/code/community/Inovarti/Pagarme/Model/Abstract.php#L160

Mas como será que o magento armazena esse `installments` do objeto `payment`? :thinking:

**Comment by jonatasmaxi** [comment]
https://github.com/pagarme/pagarme-magento/blob/v2/app/code/community/PagarMe/CreditCard/Model/Creditcard.php#L421 pode ser útil
