### ISSUE TITLE
Tornar campo de parcelas não preenchido por padrão

### ISSUE THREAD

**Issue by vagnervst** [pagarme/pagarme-magento#396]
Um cliente sugeriu deixarmos o seletor de parcelas como "Selecione..." por padrão. 

Na experiência dele a página recarrega quando o usuário corrige um erro, deixando o campo como "1x" de volta, o que pode atrapalhar caso ele tenha selecionado um valor menor antes.

Dod
- [ ] Campo de parcelas deve ser zerado no magneto - Link do PR: https://github.com/pagarme/pagarme-magento/pull/407
- [ ] #404

**Comment by danielqcampos** [comment]
Creio que isso seja algo fundamental para quem usa esse produto. Como a opção fica pré definida, ao clicar em finalizar pedido ele primeiro atualiza e depois tem que clicar de novo para realmente finalizar o pedido. Deixando a opção selecione, o cliente terá de qualquer forma que escolher a opção de parcela e isso fará a atualização nem ser percebida pelo cliente.

**Comment by leonampd** [comment]
Essa issue acredito que possa ser atacada junto com #404 dado que basicamente vai ser preciso mexer no mesmo lugar.

**Comment by murilohns** [comment]
Release feito: https://github.com/pagarme/pagarme-magento/releases/tag/v3.18.2
