### ISSUE TITLE
Juros não aparecem na parcela nem atualizam total do pedido

### ISSUE THREAD

**Issue by aquere** [pagarme/pagarme-magento#397]
Ao finaliza compra e escolher o meio de pagamento como cartão de crédito o mesmo não informa a porcentagem de juros por parcela e nem atualiza o total do pedido de acordo com o parcelamento selecionado.

**Comment by murilohns** [comment]
Olá @aquere, pode dar mais detalhes do problema, por favor?

Ex: Imagem do Checkout e Imagem de configuração do juros

**Comment by aquere** [comment]
![Untitled-1](https://user-images.githubusercontent.com/7633099/54947792-e9fd9e80-4f19-11e9-849b-b52e2cabddec.jpg)

**Comment by murilohns** [comment]
#407 corrige esse problema.

**Comment by murilohns** [comment]
Corrigido #407 (Versão 3.18.2)

Agora o cliente pode ver o valor total do pedido na hora de selecionar as parcelas.
