### ISSUE TITLE
Módulo ignorando configuração de pagamento

### ISSUE THREAD

**Issue by irwingmax** [pagarme/pagarme-magento#398]
De acordo com o case 09731577, cliente fez a seguinte configuração:
Checkout Transparente aceita apenas transações com cartão de crédito
Checkout Pagar.me aceita apenas transações com boleto.

No momento do teste, foi notado que o módulo ignora essa configuração e no Checkout transparente ele mantem as duas opções de pagamento

**Comment by murilohns** [comment]
@irwingmax, por que o cliente precisa passar cartão de um jeito e boleto do outro?

opinião pessoal: boleto é muito melhor pelo checkout transparente

**Comment by irwingmax** [comment]
@murilohns  Não sei ao certo, o cliente entrou em contato querendo configurar dessa maneira e não funcionou

**Comment by rafaelpatro** [comment]
Também já tentei configurar _Somente Boleto_ no transparente, e não funcionou.
Ficou aparecendo o boleto e cartão.

**Comment by leonampd** [comment]
### Possível correção

Implementar o método `isAvailable` consultando a configuração `transparent_payment_methods` definida aqui:
https://github.com/pagarme/pagarme-magento/blob/797418e5fea7e0a78abfa92b891599156379f82e/app/code/community/PagarMe/Core/etc/system.xml#L177
