### ISSUE TITLE
Finalizar pedido com cartão de credito pelo admin

### ISSUE THREAD

**Issue by pedrobnu** [pagarme/pagarme-magento#401]
no admin ao criar um pedido não é possivel escolher a opção pagarme não busca qualquer form

**Comment by murilohns** [comment]
Olá @pedrobnu, pode nos dar mais detalhes sobre esse problema, por favor?

Passos para reproduzir é um ótimo começo

**Comment by pedrobnu** [comment]
então, vamos lá, precisa ativar em formas de pagamento o  cartão de credito pagar.me ir ainda em painel ir em vendas / pedidos  e criar um pedido vai pedir pra criar um cliente ou selecionar um , no meu caso selecionei um já criado,  na tela de novo pedido adicionar um produto , escolher uma forma de entrega, e então escolher uma forma de pagamento no caso o cartão de credito pagar.me antes ativado, e não ira aparecer nenhum form para preencher os dados do cartão, no caso de outras Plataformas de pagamentos , como payU por exemplo é possivel finalizar o mesmo pelo painel de admin ,
![capt](https://user-images.githubusercontent.com/44219402/55904620-aad07e00-5ba6-11e9-8753-afc7adac126b.png)
![capt1](https://user-images.githubusercontent.com/44219402/55904631-af953200-5ba6-11e9-8b03-e0a813a2294d.png) como visto nas prtscreen
obrigado pela atenção @murilohns . qlquer duvida estou a disposição pra responder
