### ISSUE TITLE
V2- Não finalização de compra no cartão de crédito

### ISSUE THREAD

**Issue by WidecommerceDev** [pagarme/pagarme-magento#402]
Boa tarde !

Utilizamos a versão v2 3.18.1 do módulo pagarme, e não conseguimos finalizar compras no cartão de crédito.
Ao tentar finalizar é retornado um alerta dizendo que alguns campos do Formulário estão faltando, porém os mesmos estão preenchidos.

Verificando o console de desenvolvedores do chrome, verificamos o seguinte erro:  "pagarme is not defined".

Ao analisar os códigos javascript inseridos pelo módulo, verificamos de que o erro é disparado no momento em que uma verificação sobre os dados do cartão vai se iniciar.O trecho de código é:
`  const cardValidations = pagarme.validate({
    card
  })`

Buscamos em toda estrutura do módulo onde o objeto pagarme é instanciado, porém sem sucesso.

Podem ajudar ?

**Comment by murilohns** [comment]
Olá @WidecommerceDev, o script do pagar.me é importado no começo da página, como você pode ver nessa linha:

https://github.com/pagarme/pagarme-magento/blob/v2/app/design/frontend/base/default/layout/pagarme/pagarme_creditcard.xml#L7

**Comment by WidecommerceDev** [comment]
> Olá @WidecommerceDev, o script do pagar.me é importado no começo da página, como você pode ver nessa linha:
> 
> https://github.com/pagarme/pagarme-magento/blob/v2/app/design/frontend/base/default/layout/pagarme/pagarme_creditcard.xml#L7

Problema resolvido, obrigado.

**Comment by murilohns** [comment]
Olá @WidecommerceDev, pode me dizer qual foi a solução do problema?

Fico no aguardo.
