### ISSUE TITLE
Campo de parcelas não exibe o valor total da transação em caso de juros

### ISSUE THREAD

**Issue by leonampd** [pagarme/pagarme-magento#404]
### Contexto

Em casos que o módulo tem a configuração de juros definida para parcelamento, durante o checkout, o campo de seleção de parcelas mostra apenas o valor de cada parcela.

### Feedback de clientes

Seria interessante que o valor total da transação seja mostrado neste campo de modo a tornar mais claro que haverá juros de acordo com a quantidade de parcelas escolhida pelo comprador.

**Comment by leonampd** [comment]
### Sugestão de implementação

O nosso módulo já usa a rota `[/calculate_installments_amount]` para exibir o valor das parcelas informado em `installments_amount`. Para contemplar essa demanda bastaria usar o campo `amount` que a rota retorna. Faz sentido?

**Comment by murilohns** [comment]
Link do PR: https://github.com/pagarme/pagarme-magento/pull/407

**Comment by murilohns** [comment]
Corrigido no #407
