### ISSUE TITLE
Repositório sem issue/pr templates

### ISSUE THREAD

**Issue by leonampd** [pagarme/pagarme-magento#405]
### Contexto

Quando viramos a chave do novo módulo no repositório, perdemos os templates de issues e prs, que estávam presentes somente no branch `master`.

**Comment by leonampd** [comment]
## Correção

Para resolver o problema basta replicar os templates que hoje estão em https://github.com/pagarme/pagarme-magento/tree/master/.github. Acredito também que faça sentido ajustar o nome dos branches mantendo o `master` como o default.

**Comment by murilohns** [comment]
Link do PR: https://github.com/pagarme/pagarme-magento/pull/406
