### ISSUE TITLE
Checkout Não Finaliza - Aparece a tela anexa

### ISSUE THREAD

**Issue by digitalvoip** [pagarme/pagarme-magento#41]
Senhores,
Alguém pode ajudar.
Busco saber se você pode me ajudar:
Estou a testar o pagar.me na loja http://mahogany-se.com.br

1) Instalei o módulo manualmente via FTP
2) Instalei o OSC (para validação de CPF, máscaras de CEP, telefones, etc..)
3) Instalei o CheCkoutVendaMais 1.8

Ocorre que ao clicar em finalizar uma compra a tela do checkout aparece uma execução como se estivesse buscando algo e fica congelado.

Peço acessar a loja pra reproduzir este evento e ver se pode me dar uma dica de como resolver....segue a tela anexa.

meu skype = salvador-ba

![tela](https://cloud.githubusercontent.com/assets/15305033/12311171/3cd9cb3e-ba34-11e5-969c-f2c7c6607a91.jpg)
u

**Comment by eneiasramos** [comment]
Olá @digitalvoip ! Tudo bem?

Por favor utilize a última versão atualizada disponível no link:

https://github.com/pagarme/pagarme-magento

Att,
