### ISSUE TITLE
Card_hash Inválido e Número Inválido

### ISSUE THREAD

**Issue by guilhermeaquere** [pagarme/pagarme-magento#415]
## Contexto

Ao finalizar a compra em navegadores que já possuem os dados de telefones/contatos salvos e fazem o auto preenchimento da informação conforme está salva no navegador do usuário estou recebendo a falha na hora de finalizar a compra.

Logo que o cliente recebe a notificação de que está com o Número Inválido, ele corrige o erro e recebe outro em seguida: card_hash inválido.

Segue os prints que recebemos nos e-mails:

![Número-Inválido](https://user-images.githubusercontent.com/7633099/58277930-370ebd00-7d71-11e9-9281-1a8c87580201.jpg)

![Card-Hash](https://user-images.githubusercontent.com/7633099/58277931-370ebd00-7d71-11e9-89d7-689db8f0a890.jpg)

PS: Se ele não tem os dados do número de telefone salvo no navegador, o usuário não consegue digitar qualquer outro caractere que não seja número no campo de telefone.

## Ambiente

* Magento Community 1.9.3.8
* Módulo Pagar.me v3.19.2
* Firecheckout

**Comment by murilohns** [comment]
Obrigado por reportar @aquere.

O número de telefone não deve possuir o ddi, apenas o ddd para que o módulo funcione corretamente, assim como você enviou na segunda imagem.

Com relação ao `card_hash` inválido, realmente o módulo está com um problema com relação à isso e vamos resolvê-lo assim que possível.

**Comment by murilohns** [comment]
@guilhermeaquere o problema de card_hash foi corrigido no PR #416 

Você poderá acessar essa feature à partir da versão 3.19.3 do módulo =]

**Comment by guilhermeaquere** [comment]
Oi @murilohns! Fiz a atualização do módulo para a versão 3.19.3 na sexta-feira (31/05/2019).

Entretanto, tive novamente o mesmo erro no sábado (01/06) e no domingo (02/06)

Segue os prints:
Nesse caso, no sábado, o telefone não foi corrigido.
Primeira tentativa:
![num_tel](https://user-images.githubusercontent.com/7633099/58804186-a002fa00-85e7-11e9-9e95-6dae3a987a4d.jpg)
Segunda tentativa:
![card_hash2](https://user-images.githubusercontent.com/7633099/58804185-a002fa00-85e7-11e9-8826-74e55cdc9f89.jpg)

Depois o cliente ainda insere o CPF/CNPJ inválido e recebe o erro de card_hash em seguida.
![cpf_errado](https://user-images.githubusercontent.com/7633099/58804454-4bac4a00-85e8-11e9-9fbe-addcc3fe8b8a.jpg)

Já no domingo, o cliente tem o pagamento recusado pelo banco e em seguida recebe o erro do card_hash.

Primeira tentativa:
![pagamento_recusado](https://user-images.githubusercontent.com/7633099/58804794-18b68600-85e9-11e9-898c-eb92e883d76f.jpg)

Segunda tentativa:
![card_hash3](https://user-images.githubusercontent.com/7633099/58804816-1f44fd80-85e9-11e9-9775-f7d9c4be6188.jpg)

**Comment by murilohns** [comment]
@guilhermeaquere, obrigado por reportar.

Sobre o número de telefone, como eu disse anteriormente, ele precisa ter o DDD, e o número. Pelo que vi em seu formulário, o Firecheckout já faz essa máscara pra você, solicitando o número no formato `(11) 912345678`
Se o usuário não preencher nesse formato, o número de telefone constará como inválido mesmo.

Sobre o `card_hash`, identifiquei o problema, que é diferente do que tinha ocorrido anteriormente. Vamos corrigir isso assim que possível =]

**Comment by guilhermeaquere** [comment]
@murilohns obrigado pelo retorno!

sim, já existe a máscara, entretanto se o cliente tem os dados salvos no navegador (normalmente no mobile) e ele selecione para preencher automaticamente a máscara não funciona.

já estou em contato com o firecheckout para que eles possam me ajudar nessa questão também

**Comment by guilhermeaquere** [comment]
Essa foi a resposta do Firecheckout:

> Developer reported that problem of autofilling in magento version 1 connected with library which it uses. Consequently, magento does not support version 1, and does not update llibrary, this problem will not be solve. We suggest you to migrate your magento to the version 2

**Comment by guilhermeaquere** [comment]
Esse módulo já pode ser usado no Magento 2?

**Comment by leonampd** [comment]
@guilhermeaquere tudo bem? Esse módulo não é compatível com o Magento 2 e infelizmente ainda não temos um que tenha essa compatibilidade. =/

**Comment by guilhermeaquere** [comment]
@leonampd @murilohns vocês tem alguma previsão para uma solução e para o desenvolvimento do módulo para Magento 2 ?

**Comment by murilohns** [comment]
@guilhermeaquere, desculpe toda essa demora :(

Abri um PR para corrigir esse problema, você pode acompanhá-lo aqui: https://github.com/pagarme/pagarme-magento/pull/422

**Comment by guilhermeaquere** [comment]
Obrigado @murilohns 

Estamos torcendo por uma solução ;)

**Comment by murilohns** [comment]
Problema corrigido na versão 3.20.1

@guilhermeaquere você pode baixar a nova versão aqui: https://github.com/pagarme/pagarme-magento/releases/tag/v3.20.1

**Comment by guilhermeaquere** [comment]
Ótimo! Vou atualizar e qualquer coisa aviso vocês!
