### ISSUE TITLE
Conflito bibliotecas jQuery duplicadas

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#420]
## Contexto

Boa noite. Testei duas lojas onde o Pagar.me v3.20 está instalado, em conjunto com o Firecheckout. E as duas lojas apresentaram o mesmo problema.

Quando ativo, o console do Chrome apresenta alguns erros no JS, e o checkout fica inutilizável. Nenhuma ação funciona.

Quando o console está fechado, o checkout funciona normalmente, permitindo fechar pedidos.

Acredito que o erro pode estar relacionado a um conflito com bibliotecas externas, que o assets.pagar.me carrega.

## Ambiente

* Magento Community 1.9.3
* Módulo Pagar.me 3.20
* Servidor Linux
* PHP 7.0
* Nginx
* Mariadb

**Comment by leonampd** [comment]
Oi @rafaelpatro tudo bem! mais uma vez **muito obrigado** por toda ajuda que você tem nos dado reportando problemas e dando feedbacks. Essa demanda vai entrar na fila do nosso time e vamos atacar assim que possível. Infelizmente o time tá bem atarefado com outras demandas no momento.

**Comment by murilohns** [comment]
@rafaelpatro, consegue me dar instruções mais claras de como reproduzir isso?

Preciso configurar o firecheckout de alguma forma específica?
Acontece só quando o console do chrome está aberto?

**Comment by davirs** [comment]
Olha só, eu tenho firecheckout e não tive este problema. Tem que lembrar que é necessário remover o módulo pagarme anterior antes de instalar o novo.
Revise a instalação dos módulos e pastas que deve funcionar sem problemas
