### ISSUE TITLE
Qual é a versão de API usada?

### ISSUE THREAD

**Issue by rafaelstz** [pagarme/pagarme-magento#421]
Olá, estou usando o módulo em sua última versão aqui do Github usando a branch v2.
Eu gostaria de saber qual é a versão de API que tenho que especificar no painel da PagarMe?

**Comment by murilohns** [comment]
Olá @rafaelstz, o módulo funciona nas versões de API `2017-08-28` e `2017-07-17` =]

**Comment by rafaelpatro** [comment]
Bom dia @murilohns 
Como essa pergunta já tem quase 5 meses, gostaria de saber se há uma atualização sobre o assunto.

1. Essa extensão suporta a API v4 (2019)?
1. A partir de qual versão da API o Pagar.me aceita cartões internacionais?

**Comment by brunoconstantino** [comment]
Olá,

Também gostaria de saber sobre a versão da API suportada pelo módulo na branch master e v2.
