### ISSUE TITLE
taxvat CPF / CNPJ

### ISSUE THREAD

**Issue by thiago85** [pagarme/pagarme-magento#423]
boa tarde!

tenho uma loja magento versão 1.7.0.2

gostaria de saber o que acontece se o usuário não informar o taxvat no cadastro

o módulo de vocês pede o cpf ao finalizar a compra ?

ou simplesmente gera um erro ?

se puderem me responder obrigado!

**Comment by murilohns** [comment]
Olá @thiago85 =]

Por padrão o módulo usa o campo `TaxVat` como dado de CPF do usuário. Se esse campo não for preenchido / enviado, ocorrerá o erro `número de documento está faltando`.
