### ISSUE TITLE
Erro SDK no retorno do pedido, não vai para a tela de sucesso

### ISSUE THREAD

**Issue by rafaelstz** [pagarme/pagarme-magento#424]
## Contexto

[Faça uma descrição detalhada do problema que você está tendo e lembre-se de deixar claro se o problema é um bug, um aprimoramento ou apenas uma pergunta]

## Ambiente

* Magento Community 1.9.4.1
* Módulo Pagar.me 3.18.2
* Servidor Linux
* PHP 5.6
* Apache 2.2
* MySQL 5.6

## Passos para reproduzir

1. Tentar finalizar compra no boleto

## Resultado atual

Voltar para o carrinho e não mostra finalizado com sucesso, mas gera pedido na pagarme e no admin do Magento.

<img width="1410" alt="Screen Shot 2019-07-31 at 1 22 29 PM" src="https://user-images.githubusercontent.com/610598/62230451-33fb0300-b398-11e9-970f-db959753c69f.png">

## Resultado esperado

SDK da pagarme retornar sucesso e o Magento mostrar a tela de sucesso também.

## Possível correção

Tratar as correções.

**Comment by rafaelstz** [comment]
Esse é o POST que é feito.

<img width="782" alt="Screen Shot 2019-07-31 at 1 58 49 PM" src="https://user-images.githubusercontent.com/610598/62232699-34e26380-b39d-11e9-94f7-9e6c5842807e.png">

**Comment by rafaelstz** [comment]
O erro foi causado por causa do módulo da Skyhub, teria algo pronto para evitar isso ou eu teria que debugar e corrigir?

**Comment by murilohns** [comment]
Olá @rafaelstz, não temos nada pronto para evitar isso, essa era uma incompatibilidade desconhecida.

Pode nos enviar algum link para download do módulo da `skyhub`?

**Comment by rafaelstz** [comment]
Esse link tem as descrições sobre a instalação do módulo e os links: https://ajuda.skyhub.com.br/hc/pt-br/articles/360000724646-Instala%C3%A7%C3%A3o-do-M%C3%B3dulo-para-Integra%C3%A7%C3%A3o-entre-Magento-e-API-SkyHub

Esse é o link para download do módulo da Skyhub: https://drive.google.com/file/d/17Q1V585Jc0VX5Eou3uQF2-Y-Up_6JcSw/view?usp=sharing
