### ISSUE TITLE
Cálculo de Juros Incorreto

### ISSUE THREAD

**Issue by iurimedeiros** [pagarme/pagarme-magento#426]
Prezados, peço que vejam o valor dos juros exibidos no select e o valor informado na revisão do pedido, este não bate, está configurado para cobrar 0.49% ao mês, sendo que são 6x sem juros.

![erro-parcelamento](https://user-images.githubusercontent.com/11665895/62263448-9c76ce00-b3f2-11e9-8983-379395fe2349.JPG)

* Magento Community 1.9.2.2
* Módulo Pagar.me 3.20.1
* Infos do Server: http://machinemotors.com.br/phpinfo.php

Abraço,
Iuri Medeiros
Equipe Machine Motors

**Comment by rafaelpatro** [comment]
Cara, eu já tive esse problema.
No meu caso tive que customizar o módulo de checkout.
Para qualquer checkout OSC, é necessário registrar eventos, para recarregar o bloco de totais. E até o próprio bloco de pagamento, se houver regras de desconto por forma de pagamento. Vai precisar de um dev.

**Comment by Matheus-Maciel** [comment]
Resolvido no [PR 441](https://github.com/pagarme/pagarme-magento/pull/441)
