### ISSUE TITLE
child "type" fails because ["type" is required]

### ISSUE THREAD

**Issue by carlosjaquetto** [pagarme/pagarme-magento#428]
Olá, estou tentando fazer a integração do módulo com o magento e baixei a versão mais atualizada, porém quando tento finalizar uma compra me da a mensagem [child "type" fails because ["type" is required]], o que tenho que fazer para resolver essa questão ?

**Comment by murilohns** [comment]
Olá @carlosjaquetto, a versão de API de sua conta deve ser `2017-07-17` ou inferior.

Você pode alterar isso através da [dashboard](https://dashboard.pagar.me).

**Comment by davirs** [comment]
@murilohns obrigado, era só isto mesmo! na minha chave teste a API era a mais recente. Coloquei a 2017-07-17 e funcionou.
