### ISSUE TITLE
Erro nos pedidos após remover inovarti

### ISSUE THREAD

**Issue by davirs** [pagarme/pagarme-magento#429]
Olá tudo bem?
A loja utilizava o módulo de pagamentos da inovarti.

Como a nova versão de vcs ficou incomparavelmente melhor eu removi a inovarti e instalei a nova.
**O problema é que agora os pedidos que foram feitos com inovarti não abrem mais, e se eu deixar o inovarti ativo bagunça tudo...**

Como eu faço os pedidos criados com o inovarti abrirem com o novo módulo?

![Screenshot_13](https://user-images.githubusercontent.com/4355062/64537491-4b130600-d2f1-11e9-83ef-4a3a55d4a36d.png)

**Comment by murilohns** [comment]
@davirs, pode me dizer como foi desinstalado o módulo antigo?

ex: apaguei as pastas `x`, `y` e `z`
ou
acessei a aba `b` e desinstalei pela interface do magento

Fico no aguardo.

**Comment by davirs** [comment]
primeiramente eu desativei o módulo no painel do magento, guia avançado
depois eu removi todos os arquivos do diretório.
Após isto instalei a nova versão normalmente.

**Comment by rafaelpatro** [comment]
Também passei por isso há algum tempo.
Resolvi reconfigurando a tabela de pagamento, direto no banco.

```sql
UPDATE sales_flat_order_payment
SET method = 'cc_save'
WHERE method = 'pagarme_cc';
```

Não é a melhor das soluções, pois alguns dados ficam ocultos na tela do pedido. Mas os dados não são perdidos. Em seguida vc pode fazer um script para converter a coluna _additional_info_ para o formato mais atual do módulo. Assim vc consegue extrair todas as informações.

**Comment by murilohns** [comment]
Ok @davirs, obrigado pela explicação. Tentarei simular esse problema e vou te atualizando

**Comment by davirs** [comment]
Eu achei estranho que eu obtive em uma consulta aqui no banco de dados no Payment Method dos pedidos, eu consegui identificar todas as formas de pagamento que eu já usei, inclusive do módulo inovarti, menos os novos metodos do pagarme.
Nesta consulta eu vejo nos pedidos exatamente o que eu escrevo lá no checkout, exemplo "Cartão de Crédito Pagarme". Obtive 3 valores nulos, acredito serem do pagarme...

![Screenshot_14](https://user-images.githubusercontent.com/4355062/64541801-e491e600-d2f8-11e9-8db6-c3090d8059f6.png)

**Comment by davirs** [comment]
@rafaelpatro Obrigado! já resolve!!
vou aguardar eles darem um retorno... qualquer coisa mando bala assim mesmo

**Comment by murilohns** [comment]
@rafaelpatro, obrigado pela solução do problema. Precisamos investigar o que causa isso pra matar na raíz

@davirs, obrigado por reportar esse problema de não registrar o meio de pagamento no banco de dados.
Pode me dizer qual `query` ou tabela foi olhada pra verificar essa informação?

**Comment by rafaelpatro** [comment]
Sugestão...
Uma solução mais elegante para resolver isso no módulo v2 seria fazer uma espécie de mock para o módulo anterior.

https://github.com/pagarme/pagarme-magento/blob/a1113285d4275b3b7abdac2b7339e86492bea9d0/app/code/community/Inovarti/Pagarme/etc/config.xml#L310

Pode por exemplo sobrescrever essa configuração, copiando para o config.xml do v2.

Ex.:
```xml
<config>
    <default>
        <payment>
            <pagarme_cc>
                <active>0</active>
                <model>pagarme_creditcard/creditcardOld</model>
```

Então criar a classe CreditcardOld, e ajustar o infoBlock...
https://github.com/pagarme/pagarme-magento/blob/eaec572a8dd827abb2022af0b7fadf71369aa036/app/code/community/PagarMe/CreditCard/Model/Creditcard.php#L34

Em seguida precisa criar um bloco específico, para poder ler as informações do módulo v1.
Enfim acho q é uma boa sugestão, para poder de fato desativar a v1, e ainda assim manter a compatibilidade; poder abrir os pedidos, etc.

**Comment by davirs** [comment]
@murilohns Meu sistema puxa a coleção inteira de vendas, é difícil precisar qual é a tabela porque o magento cruza várias. A coluna payment method na imagem acima eu posso usar para alterar a forma de pagamento em lote, o que resolveria o meu problema inicial.
Ele exibe na tela o nome que eu coloco lá na configuração do módulo(imagem abaixo), mas por trás dos panos é só para facilitar na hora de escolher (pra não aparecer pagarme_cc por exemplo)... 

Alguma coisa na nova versão do módulo foge do padrão, como é nítido na imagem acima o módulo antigo mesmo desativado ainda retorna o pagamento na coleção vendas.

![Screenshot_18](https://user-images.githubusercontent.com/4355062/64557671-71986780-d318-11e9-91df-0e81cb05b998.png)

**Comment by murilohns** [comment]
@davirs, como você realizou a busca desse [comentário](
https://github.com/pagarme/pagarme-magento/issues/429#issuecomment-529516677
)? Li acima que "seu sistema puxa a coleção inteira de vendas", isso é do próprio magento ou é um sistema externo? Pode me dizer como reproduzir essa busca?

Fico no aguardo.

**Comment by davirs** [comment]
@murilohns já respondi isso dias atrás via email. Está no ticket.
Coloquei até como baixar o trial e reproduzir o erro

Att
