### ISSUE TITLE
Erro pagarme ao faturar pedido de outro gateway

### ISSUE THREAD

**Issue by davirs** [pagarme/pagarme-magento#431]
Olá. Eu estou faturando um pedido feito com a wirecard. 
Mesmo não sendo um pedido do pagarme, no backend aparare o seguinte erro na tela da fatura:

![Screenshot_20](https://user-images.githubusercontent.com/4355062/64558378-1798a180-d31a-11e9-94c1-5e011f2e488f.png)

Como resolvo isso? eu tenho que usar os dois módulos de pagamento em paralelo. Grato

* Retificando: qualquer outro método que não seja pagarme da erro. Não só wirecard.

**Comment by leonampd** [comment]
@murilohns @ahmarcia acho que dá pra fechar essa issue já que o #434 tá _merged_. 😉

**Comment by piiih** [comment]
vlw @leonampd
