### ISSUE TITLE
PAGARME_CreditCard impede merge default do magento

### ISSUE THREAD

**Issue by davirs** [pagarme/pagarme-magento#433]
Olá. Após instalação do módulo pagarme novo, é impossível fazer merge de JS defualt do magento. O layout quebra inteiro.
Basta desativar a extensão PAGARME_CreditCard que a junção funciona perfeitamente.

**Comment by rafaelpatro** [comment]
Boa tarde @davirs 
Não sei se já conseguiu resolver, mas tb passei por esse problema recentemente, mas consegui contornar.

Apesar de ser ruma péssima prática, o javascript permite omitir o ponto-e-vírgula. Mas muitos minificadores de código não conseguem lidar isso.

Enfim vários arquivos desse módulo omitem o ponto-e-vírgula. E só consegui resolver, alterando o arquivo, e colocando a pontuação no final de cada linha.

https://github.com/pagarme/pagarme-magento/blob/9f3ff93fb1addade014d40baa42e9e800f0c468c/app/design/frontend/base/default/template/pagarme/form/credit_card.phtml#L135

**Comment by davirs** [comment]
@rafaelpatro tudo certo?
Eu também contornei desta forma, mas o problema é que eles não usam corretamente os padrões, apenas 2 linhas do código são responsáveis por este problema... já informei o suporte e eles não acreditam... e digo mais,  tenho absoluta certeza que não resolveram até agora por que é o suporte mais lento que eu conheço, uma lástima na verdade...

Esta issue o de menos, tem outros problemas mais graves que eu também reportei e todos os clientes com esse módulo novo tem. Não uso mais não, dei rollback para o módulo antigo e outros casos troquei de pagamento. Infelizmente pagarme não esta nem aí...
