### ISSUE TITLE
Erro ao acessar checkout

### ISSUE THREAD

**Issue by JonathanCosta** [pagarme/pagarme-magento#437]
Estou utilizando a ultima versão do modulo [v3.21.1](https://github.com/pagarme/pagarme-magento/releases/tag/v3.21.1), porem quando chego no checkout aparece um erro de inclusão de um arquivo, segue abaixo a mensagem:
![image](https://user-images.githubusercontent.com/11377821/68298064-3778e700-0077-11ea-997d-778003f5417a.png)

` Warning: include(GuzzleHttp\Psr7\Request.php): failed to open stream: No such file or directory  in /lib/Varien/Autoload.php on line 94

 /lib/Varien/Autoload.php(94): mageCoreErrorHandler(2, 'include(GuzzleH...', '/...', 94, Array)
 /lib/Varien/Autoload.php(94): Varien_Autoload::autoload()
 [internal function]: Varien_Autoload->autoload('GuzzleHttp\\Psr7...')
 [internal function]: spl_autoload_call('GuzzleHttp\\Psr7...')
 /vendor/pagarme/pagarme-php/lib/Client.php(83): class_exists('\\GuzzleHttp\\Psr...')
 /vendor/pagarme/pagarme-php/lib/Client.php(56): PagarMe\Sdk\Client->buildRequest(Object(PagarMe\Sdk\Calculation\Request\CalculateInstallmentsRequest))
 /vendor/pagarme/pagarme-php/lib/Calculation/CalculationHandler.php(30): PagarMe\Sdk\Client->send(Object(PagarMe\Sdk\Calculation\Request\CalculateInstallmentsRequest))
 /app/code/community/PagarMe/Core/Model/CurrentOrder.php(36): PagarMe\Sdk\Calculation\CalculationHandler->calculateInstallmentsAmount(1930, 3, 3, 1)
 /app/code/community/PagarMe/CreditCard/Block/Form/Creditcard.php(38): PagarMe_Core_Model_CurrentOrder->calculateInstallments(1, 3, 3)
 /app/design/frontend/base/default/template/pagarme/form/credit_card.phtml(87): PagarMe_Creditcard_Block_Form_CreditCard->getInstallments()
 /app/code/core/Mage/Core/Block/Template.php(241): include('/...')
 /app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
 /app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
 /app/code/core/Mage/Payment/Block/Form/Cc.php(157): Mage_Core_Block_Template->_toHtml()
 /app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Payment_Block_Form_Cc->_toHtml()
 /app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
 /app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('payment.method....', true)
 /app/code/core/Mage/Checkout/Block/Onepage/Payment/Methods.php(72): Mage_Core_Block_Abstract->getChildHtml('payment.method....')
 /app/design/frontend/nitroecom/one/template/ideasa/idecheckoutvm/onepage/payment/methods.phtml(16): Mage_Checkout_Block_Onepage_Payment_Methods->getPaymentMethodFormHtml(Object(PagarMe_CreditCard_Model_Creditcard))
 /app/code/core/Mage/Core/Block/Template.php(241): include('/...')
 /app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/nitroe...')
 /app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
 /app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
 /app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
 /app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('methods', true)
 /app/design/frontend/nitroecom/one/template/ideasa/idecheckoutvm/onepage/payment.phtml(27): Mage_Core_Block_Abstract->getChildHtml('methods')
 /app/code/core/Mage/Core/Block/Template.php(241): include('/...')
 /app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/nitroe...')
 /app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
 /app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
 /app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
 /app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('payment.method', true)
 /app/design/frontend/nitroecom/one/template/ideasa/idecheckoutvm/idecheckoutvm.phtml(57): Mage_Core_Block_Abstract->getChildHtml('payment.method')
 /app/code/core/Mage/Core/Block/Template.php(241): include('/...')
 /app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/nitroe...')
 /app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
 /app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
 /app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
 /app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Text_List->_toHtml()
 /app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
 /app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('content', true)
 /app/design/frontend/nitroecom/one/template/page/1column-checkout.phtml(46): Mage_Core_Block_Abstract->getChildHtml('content')
 /app/code/core/Mage/Core/Block/Template.php(241): include('/...')
 /app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/nitroe...')
 /app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
 /app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
 /app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
 /app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
 /app/code/local/Ideasa/IdeCheckoutvm/controllers/IndexController.php(161): Mage_Core_Controller_Varien_Action->renderLayout()
 /app/code/core/Mage/Core/Controller/Varien/Action.php(418): Ideasa_IdeCheckoutvm_IndexController->indexAction()
 /app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
 /app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
 /app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
 /app/Mage.php(684): Mage_Core_Model_App->run(Array)
 /index.php(83): Mage::run('', 'store')
 {main} `

**Comment by leonampd** [comment]
Fala @JonathanCosta td bem? Verifica se você instalou o módulo junto com a pasta `vendor`. ela é necessária pro módulo funcionar. Pra garantir o ideal é fazer o download do módulo por [aqui](https://github.com/pagarme/pagarme-magento/releases).

**Comment by JonathanCosta** [comment]
opa @leonampd  , to bem e você?
Cara, fiz a instalação por composer, fiz o download pelo link que vc passou, e sempre apresenta o mesmo erro. até aonde eu consegui verificar o PagSeguro tenta carregar uma dependência que não tem.
No arquivo que baixei a ultima versão nesse link que vc passou, ele verifica se a class GuzzleHttp\Psr7\Request existe.
vendor/pagarme/pagarme-php/lib/Client.php(83)
Porem isso dispara o autoload que não encontra nada, se você vasculhar o diretorio vendor vc percebe que não existem mesmo. No [composer.json](https://github.com/pagarme/pagarme-magento/blob/v2/composer.json) tbm não faz nenhuma referencia dessa dependencia.

**Comment by JonathanCosta** [comment]
Provavelmente foi [aqui](https://github.com/pagarme/pagarme-php/pull/328/files) que está o erro foi alterado 
`  if (class_exists('\\GuzzleHttp\\Message\\Request')) {`
para
`if (class_exists('\\GuzzleHttp\\Psr7\\Request')) {`

**Comment by murilohns** [comment]
@JonathanCosta, ainda está com esse problema?

**Comment by JonathanCosta** [comment]
@murilohns Se não me engano eu tive que voltar a versão das dependências.
Agora não sei se já foi resolvido.
