### ISSUE TITLE
Problema com Pending Payment no Modal

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#438]
## Contexto

Boa tarde pessoal.
O pagamento via Cartão no Modal não está lidando corretamente com o status dos pedidos aprovados.
Por padrão o Magento identifica _pending_payment_ como uma transação ainda pendente. E só permite avançar para outro status, através da opção de Faturar (Invoice). O que pode ser feito automaticamente por uma API postback, ou manualmente, clicando em Invoice (Confirmar Pagamento).
O caso é que o Modal já está capturando e faturando o pedido. Mas deixa o status em _pending_payment_. Enfim o pedido fica trancado nesse status. Não é possível alterar o estado do pedido.

## Ambiente

* Magento Community 1.9.3.4
* Módulo Pagar.me 3.21.1
* Servidor Ubuntu 18.04
* PHP 7.0.30
* Apache 2.4
* MySQL 5.7

## Passos para reproduzir

1. Realize um pedido via Modal, e pagar com cartão de crédito
1. Acesse o pedido pelo painel administrativo, e verifique a situação _Pending Payment_
1. Verifique que o pedido já foi faturado, e capturado no Pagar.me

## Resultado atual

O estado do pedido é Pagamento Pendente (pending_payment)

## Resultado esperado

O estado do pedido deveria ser Pagamento Confirmado (processing).

Conforme o fluxo do Magento, o estado _pending_payment_ é anterior ao _processing_. A ação de faturar realiza a transição de _pending_payment_ para _processing_. E o resultado dessa ação é a criação da fatura. Enfim, o Modal gera a fatura, e volta o estado para _pending_payment_. E assim fica impossível avançar o fluxo.

**Comment by murilohns** [comment]
@rafaelpatro vou fechar essa issue pois a #452 retrata o mesmo problema, mas está mais detalhada.

Podemos acompanhar a resolução por lá.
