### ISSUE TITLE
Diferença de 1 centavo gera falha na Captura

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#439]
## Contexto

Olá pessoal
Após a reclamação de alguns clientes, verifiquei um bug no módulo. Algumas transações estavam retornando falha na captura, sem motivo aparente. E em todos os casos notei que o valor estava incorreto, com 1 centavo a mais do que o total da compra. Então verifiquei que o módulo converte o total, de ponto flutuante para inteiro.
https://github.com/pagarme/pagarme-magento/blob/3355b1a2928165bd3fb26d53a6e84750ede720b8/app/code/community/PagarMe/Core/Helper/Data.php#L78

Então fiz alguns testes com a função intval, e o bug apareceu.
![image](https://user-images.githubusercontent.com/13813964/69590963-fddd3100-0fcf-11ea-934c-5e5dfca62dfa.png)

Repare que, devido a limitações no PHP, essa função pode modificar o valor em 1 centavo. E então invalidar a captura. Como no exemplo acima, o módulo autoriza R$100,07; e, então, se o `$amount` é um float _100.07999999999999999999_, o módulo irá capturar R$100,08. E a API retornará erro.

Enfim talvez um _number_format_ seja uma saída mais segura nesse caso.

## Ambiente

* Magento Community 1.9.3.4
* Módulo Pagar.me 3.21.1
* Servidor Ubuntu 18.04
* PHP 7.0.30
* Apache 2.4
* MySQL 5.7

**Comment by rafaelpatro** [comment]
[Mais informações](https://www.php.net/manual/pt_BR/language.types.integer.php#language.types.integer.casting)
![image](https://user-images.githubusercontent.com/13813964/69593648-911a6480-0fd8-11ea-908f-c1cd961267ba.png)

**Comment by redati** [comment]
Alguém resolveu isso ? depois de anos, hoje que um cliente foi reclamar.
