### ISSUE TITLE
O Método de Pagamento solicitado não está disponível.

### ISSUE THREAD

**Issue by rafaeldittrich** [pagarme/pagarme-magento#44]
Olá Pessoal, todos os dias recebemos report de do Magento e Clientes em que recebem essa mensagem: O Método de Pagamento solicitado não está disponível.

Tanto para boleto quanto para cartão, mais alguém está com esse problema?

O que poderia fazer pra tentar corrigir isso?

Obrigado

**Comment by eneiasramos** [comment]
Olá @rafaeldittrich ! Tudo bem?

A correção para esse problema já foi implementada no módulo.

Att,
