### ISSUE TITLE
Finalização voltando para tela de Carrinho

### ISSUE THREAD

**Issue by murilosantana25** [pagarme/pagarme-magento#440]
## Contexto

Ao finalizar o pedido pelo pagarme modal, chego até a tela de confirmação. Após confirmar, ele não me manda para a tela de sucesso, e sim de volta para a tela de carrinho.

## Ambiente
* Magento Community 1.9

Alguém ja teve algo parecido ?

**Comment by murilohns** [comment]
Olá @murilosantana25, os logs de erro da sua plataforma apontam algo?

Adicionalmente, pode me dizer qual versão da API está configurada em sua [dashboard](https://dashboard.pagar.me)?

A versão ideal é a `2017-07-17`

**Comment by murilosantana25** [comment]
Boa tarde,

A API é esta mesmo.

No erro não me retorna nada.

Em seg., 9 de dez. de 2019 às 15:52, Murilo Henrique Nascimento Souza <
notifications@github.com> escreveu:

**Comment by murilosantana25** [comment]
Porém as vendas cairam no painel certinhas. Só não da o feedback para meu
cliente.

Em seg., 9 de dez. de 2019 às 16:03, Murilo Santana <
muri.lo.santana25@gmail.com> escreveu:

**Comment by murilohns** [comment]
@murilosantana25, esse problema ainda está ocorrendo?
