### ISSUE TITLE
Modulo Magento 2

### ISSUE THREAD

**Issue by awakebrasil** [pagarme/pagarme-magento#443]
Olá, 
Alguma previsão para criação do modulo para magento 2, migramos todos os nossos clientes para magento 2 e estamos com demanda para este módulo. 

Se alguém conhecer alguma versão mesmo que paga poderiam me enviar. 

Obrigado.

**Comment by murilohns** [comment]
@awakebrasil não temos previsão para um módulo de magento 2 =/

**Comment by MestreMagento** [comment]
Para quem estiver procurando por módulo **Pagar.me Magento 2**, nós temos em nossa loja com as funcionalidades de Boleto, Cartão de Cédito e Pix. Instalação gratuita, suporte profissional via Whatsapp.

https://www.modulomagento.com.br/modulo-pagar-me-magento-2-pix
