### ISSUE TITLE
Card Hash erro

### ISSUE THREAD

**Issue by vipfolheados** [pagarme/pagarme-magento#448]
Bom dia, 

o erro que acontece com muita frequência comigo é o seguinte:

cliente chega na finalização, o mesmo erra algum dado do cartão, apresenta o erro e a pagina não é atualizada, com isso o cliente arruma o dado errado que colocou e o mesmo tenta novamente clicar no botão finalizar. e ai apresenta o erro Card_Hash:

card_hash inválido. Para mais informações, consulte nossa documentação em https://pagar.me/docs.

interessante se quando o cliente errar algum dado do cartão ele atualizasse a página ou voltar para o carrinho algo do tipo?

alguém poderia me ajudar? do restante o modulo nos ajuda muito! obrigado

**Comment by murilohns** [comment]
@vipfolheados, esse problema ainda ocorre?
Ele deveria ter sido resolvido na versão [3.20.1](https://github.com/pagarme/pagarme-magento/releases/tag/v3.20.1)

Nessa versão o _card_hash_ é gerado novamente sempre que o cliente atualiza **qualquer** campo no formulário de checkout.

Isso também pode ser uma incompatibilidade com o checkout de sua loja, pode me dizer qual você utiliza?

**Comment by vipfolheados** [comment]
@murilohns ainda persiste o problema, ja instalei a versão mais recente e não vai.
usamos o checkout do magento mesmo, aquele de passo a passo. sera que pode ser o tema?

vc quer simular ai para ver de me ajudar?

tenho 2 lojas rodando a vipfolheados.com.br e a ellofolheados.com.br

as 2 da o mesmo erro, se puder me ajudar agradeço muito obrigado.
