### ISSUE TITLE
Bug na atualização de valor em "Formas de Pagamento" ao alterar "Formas de entrega".

### ISSUE THREAD

**Issue by pvcerqueira** [pagarme/pagarme-magento#450]
## Contexto

Constatei um bug no site desenvolvido em Magento https://www.fantincosmeticos.com.br/loja/ está com problemas para atualizar o valor da transação ao selecionar "Formas de Pagarmento" quando é alterado "Formas de entrega". Por não atualizar o valor em formas de pagamento, a transação é criada exatamente como o valor desatualizado.

## Ambiente

Magento/1.9.4.4 PagarMe/3.22.0 PHP/7.0.20 pagarme-php/3.8.1  

## Passos para reproduzir

1 - Seguir até uma página de checkout (Exemplo: https://www.fantincosmeticos.com.br/loja/oscheckout/);2 - Por default aparece 'Retirada na loja' - conferir o valor em "Formas de Pagamento";3 - Alterar a "Formas de Entrega";4 - Checar que o valor em "Formas de Pagarmento" não foi realizado.

## Resultado atual

Cliente não vende pelo site para não perder o valor relativo a entrega.

## Resultado esperado

Vendas coerentes ao valor da entrega caso o cliente altere a "Forma de Entrega".

![image (5)](https://user-images.githubusercontent.com/54284346/78797652-5c5ae880-798e-11ea-8228-bbc709fdd011.png)

**Comment by murilohns** [comment]
Parece ser um problema relacionado com o módulo de _checkout_ do cliente, ele é responsável por atualizar o valor do pedido, e os meios de pagamento quando esse valor for alterado.
