### ISSUE TITLE
Diferença entre o valor do pedido e o valor autorizado

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#453]
## Contexto

Não sei bem como contextualizar isso. É um problema que não ocorre em todas as transações. Mas ocorre todos os dias.
![image](https://user-images.githubusercontent.com/13813964/80926099-52e55600-8d6b-11ea-9c93-e93f7da5924c.png)

## Ambiente

* Magento Community 1.9.3.4
* Módulo Pagar.me 3.21.1
* Servidor Ubuntu 18.04
* PHP 7.0.30
* Apache 2.4
* MySQL 5.7

**Comment by murilohns** [comment]
mesmo problema reportado na #439?

podemos tratar por lá?
