### ISSUE TITLE
Boleto continua aparecendo mesmo desativado

### ISSUE THREAD

**Issue by ghost** [pagarme/pagarme-magento#455]
Uso o checkout modal, apesar de marcar  a opção pra aparecer somente o cartão de crédito, a opção de boleto continua aparecendo para o cliente

**Comment by mlimasolucoes** [comment]
já conferi no console.log e vai certo: paymentMethods: "pagarme_creditcard"
O modal ignora essa opção e continua mostrar o botão do boleto
