### ISSUE TITLE
Bug - Não finaliza compra

### ISSUE THREAD

**Issue by davirs** [pagarme/pagarme-magento#459]
Baixei o módulo novo v3.22.3 instalei seguindo todos os padrões da plataforma.
**O problema é que não finaliza a compra:** 

Checkout padrão do magento: Seleciono boleto, clico em continuar e não sai da aba, não gera erro no console nem log.
![image](https://user-images.githubusercontent.com/4355062/87231741-29126600-c390-11ea-991d-8ae53b9472ac.png)

OSC:  não carrega a opção de pagamento ou ao trocar o tipo de frete some as opções de pagamento
como deveria: 
![image](https://user-images.githubusercontent.com/4355062/87231871-0d5b8f80-c391-11ea-9b8c-43861968b07d.png)

após selecionar frete:
![image](https://user-images.githubusercontent.com/4355062/87231892-30863f00-c391-11ea-991d-7aa64a3fc544.png)

*já testei no tema/checkout default do magento, desativei todos os módulo pra evitar conflito e o problema persiste

PHP Version 7.2.31
magento 1.9.4.4

**Comment by awakebrasil** [comment]
Olá, mesmo erro teve alguma solução?

**Comment by davirs** [comment]
@awakebrasil Senta e chora, essa empresa só pensa em faturar nas nossas costas e suporte que é bom não estão nem aí! 
Estou desde 2014 esperando um módulo que preste.

**Comment by AmandaChristina** [comment]
Eu tenho o mesmo problema, é realmente uma pena não ter esse suporte

**Comment by thiagoromera** [comment]
Ola pessoal, alguem resolveu aqui?
