### ISSUE TITLE
Valor da parcela no cartão de crédito não atualiza e fica diferente do valor total

### ISSUE THREAD

**Issue by rebecapf** [pagarme/pagarme-magento#46]
Olá!

Estou com o seguinte problema:
Quando escolho a forma de cartão de crédito, onde devo escolher o parcelamento, aparece um valor diferente do valor total do pedido... por exemplo, no meu carrinho tem um total de 283,87 e no parcelamento aparece A vista 269,68, 2x de 134,84 etc... 
Além disso, se eu escolho o valor do frete, ele não é adicionado ao valor que aparece no parcelamento, continua A vista 269,68, 2x de 134,84 etc...  

Esse problema só ocorre na opção de parcelamento.. no total do pedido, o cálculo está certo e se eu finalizo o pedido, o valor cobrado é correto, inclusive o valor das parcelas... então é só na visualização mesmo... 

O problema é que meu cliente não tem a informação certa do que ele realmente vai pagar. 

Alguém pode me ajudar??

Desde já, agradeço!

**Comment by SocialGroups** [comment]
Olá Rebeca boa tarde tudo bem ?

Rebeca poderia por favor nos fornecer a url da sua loja para que possamos analisar melhor o problema.

**Comment by rebecapf** [comment]
Claro!

Minha loja é http://geekwish.com.br/

**Comment by SocialGroups** [comment]
Olá Rebeca,

Rebeca efetuamos um teste em sua loja e percebemos que o problema que esta ocorrendo já foi solucionado com a última versão do nosso módulo, poderia por favor atualizar o módulo do pagar.me novamente com a última versão disponível aqui no Github na branch master. Assim que atualizar por favor nos notifique para que possamos realizar o teste novamente e validarmos a solução do problema.

Qualquer dúvida estamos a disposição.
Atenciosamente,
Lucas Santos

**Comment by rebecapf** [comment]
SocialGroups, funcionou mais ou menos... 
Ficou o valor certo, mas se mudo o frete, esse valor não atualiza... ele só muda se atualizar a página inteira.
Alguma ideia onde pode ser?

**Comment by SocialGroups** [comment]
Olá Rebeca boa noite tudo bem ?

Tenho sim, na verdade este é um bug do onestapcheckout que foi corrido na sua última versão, poderia por favor atualizar o onestapcheckout para sua última versão, segue o link : https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro

A versão que esta no master é a ultima versão que já corrigiu este problema.

Qualquer dúvida estamos a disposição.
Atenciosamente,
Lucas Santos

**Comment by SocialGroups** [comment]
Olá Rebeca bom dia tudo bem ?

Receba poderia por favor nos confirmar se atualização do onestapcheckout checkout a resolver o seu problema ?

Ficamos no aguardo.
Atenciosamente,
Lucas Santos

**Comment by rebecapf** [comment]
Bom dia!
No momento não tenho como fazer isso, estou viajando. Segunda poderei fazer e aviso aqui! Muito obrigada!

**Comment by SocialGroups** [comment]
Olá Rebeca boa tarde tudo bem ?

Rebeca consegue nos informar se o problema foi solucionado ?

Ficamos no aguardo e qualquer dúvida estamos a disposição.
Atenciosamente,
Lucas Santos
