### ISSUE TITLE
Problemas com Firecheckout

### ISSUE THREAD

**Issue by guilhermeaquere** [pagarme/pagarme-magento#464]
Oi pessoal!

Eu estava falando com o suporte do firecheckout sobre alguns problemas que vinham ocorrendo e eles me apontaram algumas coisas que eu gostaria de compartilhar com vocês e tentar resolver.

Segue retorno do suporte:

`As regards the js issue Translator.add(...) is not a function", please find the attachment with marked the code. It is causing by pagarme_creditcard module.`

https://imgur.com/a/THAncGN

**Comment by rafaelpatro** [comment]
Boa! Apesar do JS permitir a ausência do ponto-e-vírgula, não é uma prática recomendada.
Os scripts passam por tantas compactações antes de chegar ao usuário, que simplesmente não vale a pena o risco de deixar uma linha sem ponto-e-vírgula;

**Comment by guilhermeaquere** [comment]
Obrigado pela rápida resposta e correção pessoal! @rafaelpatro @brunoconstantino
