### ISSUE TITLE
Conflito com checkouts

### ISSUE THREAD

**Issue by davirs** [pagarme/pagarme-magento#468]
Simplesmente não funciona em essa m. de módulo... Cada coisa que eu testo, cada template cada checkout... encontro propblemas diferentes. Sem dúvidas o pior módulo de pagamento que já vi. E só piora ....

![pagarmelixo3](https://user-images.githubusercontent.com/4355062/102665799-3ebc6080-4164-11eb-9eea-119b6893ec22.gif)

**Comment by brunoconstantino** [comment]
Este checkout que vc está tentando usar, é patenteado pela Wirecard Brazil. 

https://github.com/elisei/moip-transparente-magento/issues/86#issuecomment-525071658

**Comment by davirs** [comment]
@brunoconstantino eu coloquei esse checkout pra teste em base dev.
Eu testei firecheckout, testei amasty opcheckout. Nenhum funciona. Instalei o moip por que ele é padrão brasil, se nem nesse funciona não funciona em lugar nenhum.

**Comment by davirs** [comment]
versão 1.8 antiga do módulo pagarme funciona no checkout. Ou seja, "refizeram" o módulo cheio de bug, sem compatibilidade, sem funcionalidade.. pegaram algo que já estava meio caminha andado e regrediram... Sinceramente não da pra entender. Projeto zero, execução zero.

![pagarmelixo4](https://user-images.githubusercontent.com/4355062/102668302-55fe4c80-416a-11eb-979e-0dabefaf5bce.gif)
versão 1.8 (inovarti)

**Comment by LuizSantos22** [comment]
@brunoconstantino tudo bem?
Na verdade não existe isso de "patenteado" pela Wirecard. Todos os módulos para Magento são opensource. 
Ele diz isso (e tive atritos com ele por causa dessas declarações, inclusive a equipe da Magento emitiu um comunicado sobre isso) para desencorajar a "solução" elaborada por ele ser usada em conjunto com outros meios de pagamento. 

Mas é terminantemente proibido querer proibir outros meios de pagamento, já que Magento é uma plataforma sob licença Opensource, portanto, ninguém pode criar esse tipo de proibição. O que podem fazer são "adaptações" que "diicultem" o uso de outras soluções e não oferecer suporte para outras formas de pagamento. 

Mas o módulo é compatível com outros meios, mas precisam de algumas adaptações. 
Como em arquivos "form.phtml", "methods.phtml" e "billingform.phtml" (na versão antiga) 

Usando o dev console do navegador, selecione o meio de pagamento e você verá o nome do arquivo,
por exemplo "mercadopago_standard", aí você terá que declarar esse meio de pagamento no "methods.phtml"
entre os meios de pagamentos da Moip One Step Checkout. 

Pode ser que eu suba a versão modificada no meu Checkout para que saibam o que eu estou falando. 
Eu também fiz modificações nos "forms" dos meios de pagamento, usando como base, o form do meio
de pagamento da Moip. Ou seja, fiz uma adaptação dos dois. Assim eles passam a aparecer. 

Curiosamente, alguns forms de pagamento antigos, são compatíveis, e os mais novos, não. Como é o caso
do PicPay, Pagarme ou PagHiper, por exemplo. Por isso, eu adaptei para evitar esse problema. 

Por que estou abandonando o Checkout da Moip, apesar de achá-lo o mais bonito e funcional do mercado?
Com a nova LGPD o Google suspendeu a minha conta no Ads, porque o checkout do Elisei obriga a informação
de dados do cliente (CPF, CNPJ, Data de Aniversário) para fazer o cadastro do cliente e somente após isso,
finalizar a compra. 

O Google disse que isso não é permitido, mas estranhamente, não fala nada quando o mostrei o mesmo 
problema com grandes players, como Casas Bahia, B2W, etc...

Estou trabalhando numa versão modificada do IWD One Step Checkout 4.3.0 (sim, há uma versão nova, porém, piorada), já com máscaras de CPF, CNPJ (no luga do campo FAX), CEP autocompletar, etc... 

Assim que eu terminar, irei disponibilizar ambos aqui no Github, seja da IWD quanto da Moip (Wirecard) modificado


Nota Importante: 
Não são um desenvolvedor profissional, apenas um entusiasta e nem sempre as minhas soluções são as mais "adequadas" e "elegantes", sendo assim, sintam-se livres para melhorá-las ou modificá-las.

**Comment by LuizSantos22** [comment]
@davirs Olá,
Tou desenvolvendo um site em OpenMage, por um acaso vc tem a versão antiga 1.8 pra Inovarti?

**Comment by davirs** [comment]
@LuizSantos22 tenho. me deixa contato

**Comment by LuizSantos22** [comment]
@davirs Olá, tudo bem, segue o contato
deximania@onlinecmail.com

**Comment by LuizSantos22** [comment]
@davirs  
O e-mail chegou, mas o anexo não, provavelmente é um firewall 
The como mandar um link do Google Drive ou dropbox?

**Comment by LuizSantos22** [comment]
@davirs Obrigado, chegou no anexo
No entanto, está dando conflito com o checkout Moip.
Os ícones das bandeiras não aparecem corretamente, e ao preencher os dados, 
não aparece as parcelas. 
O que preencho no cpf/cnpj field? Este campo deixei vazio... 

Fiz um video pra mostar que não aparece o parcelamento: 
[https://www.loom.com/share/e7567ec015cd48d988760aeb62b3646c](url)


Att
Luiz

**Comment by dias-joao** [comment]
Olá, temos um aviso importante para você!

Viemos comunicá-lo que, a partir de 01/03/2022, iremos descontinuar o módulo de integração do Magento 1 com a API do Pagar.me. Mas não se preocupe, a descontinuidade indica apenas que iremos parar de prestar suporte ao módulo de integração do Pagar.me com o Magento 1, e seu transacional não será afetado.

Mas por que tomamos esta decisão?

A Adobe, empresa responsável pela plataforma Magento 1, lançou há um tempo a nova versão de sua plataforma de e-commerce, chamada de Magento 2. Esta nova plataforma fornece ainda mais funcionalidades, segurança e desempenho, além de permitir integrar com nosso novo módulo de integração Magento 2.

Com a criação do Magento 2, a Adobe deixou de atualizar a Magento 1 em junho de 2020, direcionando seus esforços para a nova solução que lançaram. Com isso, o módulo do Magento 1 deixou de receber atualizações importantes de segurança, melhorias e performance, o que, além de dificultar o desenvolvimento, pode representar riscos à segurança e estabilidade dos e-commerces que ainda utilizam essa solução.

Sendo assim, nós também decidimos direcionar nossos esforços para prestar suporte à nova solução: a Magento 2.

Com isso, nós recomendamos que você realize a migração de sua integração com o Pagar.me da Magento 1 para a Magento 2, a fim de garantir um ambiente de alta segurança, performance e com ainda mais qualidade para seu negócio. Você pode encontrar mais informações sobre nosso novo módulo em nossa [documentação](https://docs.pagar.me/docs/magento-2-overview).


É obrigatório realizar a transição da minha integração do Pagar.me para o Magento 2?

Não. Embora recomendamos fortemente que essa migração seja realizada pelos motivos já levantados acima, você ainda poderá manter seu e-commerce integrado no módulo da Magento 1 e utilizá-lo normalmente.

Entretanto, reforçamos que a Adobe e o Pagar.me não prestarão mais suporte a esta versão, e o plugin de integração deixará de ser oficial do Pagar.me, sendo necessário desenvolvimento próprio para que se obtenha novas features ou realize correções.


Tenho interesse em migrar para Magento 2, onde consigo ajuda com o fluxo de migração?

Como a Magento é uma plataforma de código aberto, a migração em si depende majoritariamente do seu próprio desenvolvimento. Sendo assim, recomendamos que o processo seja feito com sua equipe de desenvolvimento/TI.

Se tiver alguma dúvida relacionada à descontinuidade do módulo Magento 1, confira nossa FAQ sobre o assunto [clicando aqui](https://pagarme.zendesk.com/hc/pt-br/articles/4411718231323#h_01FNVPV53M8MNQC9ZPQPP0C42X).

Um abraço e boas vendas,
Time Pagar.me
