### ISSUE TITLE
Mensagem de retorno 'Valor Inválido'

### ISSUE THREAD

**Issue by lucassdoliveira** [pagarme/pagarme-magento#47]
Ola bom dia.

Estou com um problema que impossibilita o uso do módulo.

Ao enviar os dados do cartão de crédito, a API do pagarme me retorna a seguinte mensagem, sem padrão e tudo em minusculo 'valor inválido'.

Eu desconfio que seja devido a extensão que instalamos SCP
https://www.magentocommerce.com/magento-connect/simple-configurable-products.html

Essa extensão leva em consideração o valor do produto simples, pois meu cliente trabalha com valor diferenciado dependendo da cor do produto.

Isso também esta causando um problema nos gráficos e dados de Estatísticas, que esta ficando negativo, sem valor de venda, apenas frete.

Se puderem me dar um help agradeço.

**Comment by SocialGroups** [comment]
Olá Lucas boa tarde tudo bem ?

Lucas o erro ocorre por que em todas as transações executadas com pagar.me utilizando o nosso checkout, nós validamos se o valor do pedido enviado para nosso ambiente via javascript é o mesmo valor que esta no seu backend, este valor deve estar diferente por conta deste módulo, e isto acaba causando o erro, consegue validar por favor se desativando este módulo o problema deixa e existir?

Ficamos no aguardo e qualquer dúvida estamos a disposição.
Atenciosamente,
Lucas Santos

**Comment by lucassdoliveira** [comment]
Ola Lucas, sim.

Com uma analise mais profunda, desativamos alguns módulos customizados, e encontramos o problema.

Estamos utilizando o modulo de pontos de recompensa (Reward Points), apos desativar esse módulo funcionou normalmente. Pelo que verificamos, o mesmo esta zerando o campo $invoice->getBaseGrandTotal(), o que esta me causando uma problema também com o dashboard, que fica com valores negativos.

**Comment by SocialGroups** [comment]
Olá Lucas boa tarde tudo bem ?

Perfeito, qualquer dúvida estamos a disposição, vou esta fechado esta Issue
