### ISSUE TITLE
"body.card_hash" is not allowed to be empty

### ISSUE THREAD

**Issue by lucasfpiovesan12** [pagarme/pagarme-magento#471]
## Erro na finalização de compra do cartão de crédito - "body.card_hash" is not allowed to be empty

Algumas vezes ao tentarmos finalizar a compra no checkout da plataforma pelo cartão de crédito surge esse erro. Não é toda hora, já viram isso acontecer? Existe solução?

## Ambiente

* Magento Community 1.9.2.4
* Módulo Pagar.me 3.22.3
* Servidor Linux
* PHP 5.6
* Nginx
* MySQL 5.6
* OSC Brasil (https://onestepcheckout.com.br/)

**Comment by rafaelpatro** [comment]
Também estamos recebendo esse erro aqui.
Está muito frequente. Cerca de 20-30 vezes todo dia.

* Magento Community 1.9
* Pagar.me 3.22.5
* Ubuntu 18.01
* PHP 7.0.30
* Apache 2.4
* MySQL 5.7
* Firecheckout

**Comment by brunoguerra-dev** [comment]
@lucasfpiovesan12  / @rafaelpatro Conseguiram descobrir algo referente ao erro apresentado?
Também estamos com esse mesmo problema.

Abraço!

**Comment by lucasfpiovesan12** [comment]
@brunoguerra-dev nada... inclusive recebemos um feedback do pagar.me que esse módulo não funciona em todos os OSC disponíveis, e que é para testarmos e nós mesmos arrumarmos kkkkk é brincadeira? Nunca vi esse tipo de feedback. E aqui pelo jeito também não irão responder...

**Comment by rafaelpatro** [comment]
> @lucasfpiovesan12 / @rafaelpatro Conseguiram descobrir algo referente ao erro apresentado?
> Também estamos com esse mesmo problema.
> 
> Abraço!

Bom dia @brunoguerra-dev, consegui sim.
No meu caso haviam 2 fatores diferentes que estavam causando esse erro.

# Validade do card_hash
 - Uma vez que o cliente concluía o preenchimento dos dados do cartão, o card_hash era gerado. Ou seja o hash é gerado através do evento de preenchimento dos campos do pagamento. O problema é que se o cliente levar mais do que 300 segundos para clicar em finalizar, o card_hash expira, e dá esse erro.
 - Solução: fazer com que o card_hash seja renovado ao clicar em finalizar. É mais complicado do que parece, pois o método de gerar hash da API é assíncrono. Ou seja o botão pode submeter o pedido, antes de receber um novo card_hash. Sugestão... renovar o card_hash a cada 30s.

# Preenchimento automático do navegador
- O campo Validade/Expiração do cartão suporta somente o formato MM / YY. E muitos clientes têm optado pelo preenchimento automático do formulário, o que normalmente utiliza o formato MMYYYY. Isso gera um erro na criação do card_hash, e consequentemente _body.card_hash empty_ ao finalizar.
- Solução: ajustar o método de obtenção da data de validade, para aceitar diferentes formatos.
