### ISSUE TITLE
Cadê o PIX?

### ISSUE THREAD

**Issue by davirs** [pagarme/pagarme-magento#473]
Que a pagarme está a anos atrasada já sabemos, mas por que não implementaram ainda o pagamento via PIX?

**Comment by brunoconstantino** [comment]
O PIX está implementado na API do Pagar.me. Apenas o Módulo do Magento que não desenvolveram ainda.

**Comment by davirs** [comment]
@brunoconstantino é exatamente isso que estou cobrando rssss
Mais 10 anos será que implementam?

**Comment by davirs** [comment]
Para quem ainda usa magento um e busca um serviço PIX que preste:
https://developers.openpix.com.br/docs/ecommerce/magento1/magento1-plugin

Simples, rápido, taxa boa e tudo que vc precisar um dev resolve na hora. Empresa de verdade é outro nível!
(tem magento 1 e magento 2)
