### ISSUE TITLE
FATAL ERROR - <b>Fatal error</b>: Call to undefined method GuzzleHttp\Psr7\Request::getConfig()

### ISSUE THREAD

**Issue by rfbastos** [pagarme/pagarme-magento#476]
## Contexto

Esporadicamente para de funcionar e volta depois de um tempo quando analiasado recebemos o erro abaixo

<b>Fatal error</b>: Call to undefined method GuzzleHttp\Psr7\Request::getConfig() in <b>/home/xxxxx/xxxx.com.br/vendor/guzzlehttp/guzzle/src/Client.php</b> on line <b>160</b><br />

## Ambiente

[Caso seja um bug, descreva como é o ambiente que ele ocorre, por exemplo:]

* Magento Community 1.9.2.4
* Módulo Pagar.me 3.22.5
* Servidor Linux
* PHP 7.2
* Apache 2.2
* MySQL 5.6
* Qualquer outra característica a ser considerada

## Passos para reproduzir

[Lista organizada de processos para reproduzir a issue, por exemplo:]

1. Finalize uma compra - O erro é gerado por algum bug nas parcelas

## Resultado atual

[Descreva o que atualmente está ocorrendo com a execução do processo e explique o problema, se necessário utilize imagens]

## Resultado esperado

[Descreva o resultado esperado para a execução do processo, se necessário, utilize imagens]

## Possível correção

[Opcional, mas você pode sugerir possíveis correções para este problema]

* Exibir uma mensagem após o usuário tentar salvar informando que a API Key informada é inválida.
* Ao preencher o campo de API Key, marcá-lo com a borda em vermelho para o usuário.

**Comment by dias-joao** [comment]
Olá, temos um aviso importante para você!

Viemos comunicá-lo que, a partir de 01/03/2022, iremos descontinuar o módulo de integração do Magento 1 com a API do Pagar.me. Mas não se preocupe, a descontinuidade indica apenas que iremos parar de prestar suporte ao módulo de integração do Pagar.me com o Magento 1, e seu transacional não será afetado.

Mas por que tomamos esta decisão?

A Adobe, empresa responsável pela plataforma Magento 1, lançou há um tempo a nova versão de sua plataforma de e-commerce, chamada de Magento 2. Esta nova plataforma fornece ainda mais funcionalidades, segurança e desempenho, além de permitir integrar com nosso novo módulo de integração Magento 2.

Com a criação do Magento 2, a Adobe deixou de atualizar a Magento 1 em junho de 2020, direcionando seus esforços para a nova solução que lançaram. Com isso, o módulo do Magento 1 deixou de receber atualizações importantes de segurança, melhorias e performance, o que, além de dificultar o desenvolvimento, pode representar riscos à segurança e estabilidade dos e-commerces que ainda utilizam essa solução.

Sendo assim, nós também decidimos direcionar nossos esforços para prestar suporte à nova solução: a Magento 2.

Com isso, nós recomendamos que você realize a migração de sua integração com o Pagar.me da Magento 1 para a Magento 2, a fim de garantir um ambiente de alta segurança, performance e com ainda mais qualidade para seu negócio. Você pode encontrar mais informações sobre nosso novo módulo em nossa [documentação](https://docs.pagar.me/docs/magento-2-overview).


É obrigatório realizar a transição da minha integração do Pagar.me para o Magento 2?

Não. Embora recomendamos fortemente que essa migração seja realizada pelos motivos já levantados acima, você ainda poderá manter seu e-commerce integrado no módulo da Magento 1 e utilizá-lo normalmente.

Entretanto, reforçamos que a Adobe e o Pagar.me não prestarão mais suporte a esta versão, e o plugin de integração deixará de ser oficial do Pagar.me, sendo necessário desenvolvimento próprio para que se obtenha novas features ou realize correções.


Tenho interesse em migrar para Magento 2, onde consigo ajuda com o fluxo de migração?

Como a Magento é uma plataforma de código aberto, a migração em si depende majoritariamente do seu próprio desenvolvimento. Sendo assim, recomendamos que o processo seja feito com sua equipe de desenvolvimento/TI.

Se tiver alguma dúvida relacionada à descontinuidade do módulo Magento 1, confira nossa FAQ sobre o assunto [clicando aqui](https://pagarme.zendesk.com/hc/pt-br/articles/4411718231323#h_01FNVPV53M8MNQC9ZPQPP0C42X).

Um abraço e boas vendas,
Time Pagar.me
