### ISSUE TITLE
Atualização com problema ao requisitar arquivo

### ISSUE THREAD

**Issue by RafaelRm23** [pagarme/pagarme-magento#48]
favor corrigir 

tive problema com case sensitive no Model/Observer.php linha 164 na lib o arquivo está Pagarme.php e no require está pagarme.php

segue como está
 require_once(Mage::getBaseDir('lib') . DS . 'pagarme' . DS . 'pagarme.php');

**Comment by SocialGroups** [comment]
Olá Rafael boa tarde tudo bem ?

Efetuamos a correção o problema estava em um camelcase (pagarme.php) quando deveria estar como Pagarme.php.

Obrigado por nos avisar =D
Qualquer dúvida estamos a disposição.

Atenciosamente, 
Lucas Santos
