### ISSUE TITLE
BUG no checkout - modulo novo com pagarme checkout

### ISSUE THREAD

**Issue by davirs** [pagarme/pagarme-magento#5]
instalei o novo módulo já com o pagarme checkout e da pau na finalização da compra.
não abre o modal com o pagarme checkout, aprece um alerta dizendo que os dados não foram preenchidos...

eu testei com e sem OSC6.
segue anexo

![erro checkout2](https://cloud.githubusercontent.com/assets/4355062/9397695/c01d2fa4-4775-11e5-8dbe-74230f10ca0c.png)

![erro checkout](https://cloud.githubusercontent.com/assets/4355062/9397681/880ef606-4775-11e5-9930-a479f1c8e7a2.png)

**Comment by davirs** [comment]
...e sim, testei no magento default também....

![errocheckout3](https://cloud.githubusercontent.com/assets/4355062/9397789/8f8df91c-4776-11e5-8c10-92d60af7731e.png)

**Comment by eneiasramos** [comment]
@davirs você limpou os caches após atualizar o módulo?

**Comment by marco-domingues** [comment]
Também estou com este problema. Limpei cache umas 10x para garantir! :)
@eneiasramos quando escolhe pagamento por cartão de crédito, é possível o status do pagamento ficar como "Aguardando Pagamento" ao invés de "Pagamento Efetuado"? Por que algumas vezes a venda pode não ser aprovada.

**Comment by davirs** [comment]
claro... o cache nem está ativo, mas sempre que faço alguma instalação eu removo a /var toda pra garantir...
E digo mais.. as opções boleto e cartão do módulo nem estão ativas pra dar esse erro ai.. só o pagarme checkout está habilitado...

isso aí é BUG dos brabos....

**Comment by eneiasramos** [comment]
caros, módulo atualizado! =)

**Comment by davirs** [comment]
Atualizei. Aqui ta dando tela branca da morte.  será que o marco-domingues consegue testar também?

**Comment by eneiasramos** [comment]
@davirs atualiza desde ultimo commit https://github.com/pagarme/pagarme-magento/commit/b14f761a50a25ed3f276f7e7b59391ae71e3b7ac

**Comment by marco-domingues** [comment]
@eneiasramos está funcionando agora! :+1: 
Só achei o processo um pouco estranho, pq vc finaliza e depois precisa finalizar novamente. Se abrisse direto o checkout da pagar.me seria top! 

Enfim, muito obrigado pela ajuda. Se eu soubesse um pouco também tentaria ajudar! :/ 

Mas por enquanto acho que vou usar o cartão de crédito mesmo. Só preciso acertar a questão dos status, que fica Pagamento Confirmado, mesmo que não tenha sido confirmado ou quando estorna o status não comunica de forma automática no Magento.

**Comment by eneiasramos** [comment]
@marco-domingues dicas anotadas! =)

**Comment by davirs** [comment]
1 - Abriu o lightbox do pagarme checkout como deveria ser. 
2 - preenchi todos os dados.
3 - aparece "processando" e logo sai da tela
4 - o cliente vai ficar sem saber se deu certo ou não. tem que avisar que ele tem que continuar e finalizar ou dar algum alerta para que o cliente não fique perdido nem faça cagada...
5 - aqui ainda continua o mesmo erro

![erro](https://cloud.githubusercontent.com/assets/4355062/9419558/164f1f46-4833-11e5-97a0-27ca7ebb6b93.png)


acho que você deveria separar o pagarme checkout desse modulo ai cara... esse módulo antigo ta ferrando com nossa vida.. tem que fazer ele do zero.
será que é dificil separar o pagarmecheckout?

**Comment by eneiasramos** [comment]
@davirs qual o endereço da sua loja?

**Comment by davirs** [comment]
me add no skype brother.. eu te passo os dados..
davi.reinoldo

**Comment by lhcarvalho** [comment]
@davirs e @eneiasramos , conseguiram achar uma solução para esse problema? Estou com um BUG parecido... to procurando uma luz para tentar resolver por aqui... Valeu!

**Comment by eneiasramos** [comment]
Olá @lhcarvalho ! Tudo bem?

O seu módulo está atualizado?

Fizemos alguns ajustes para finalizar os pedidos automaticamente após o cliente preencher os dados do cartão.

Att,

**Comment by davirs** [comment]
@lhcarvalho negócio é que eu tenho medo de usar este módulo. por isso optei por não usar pagar.me ainda.
daqui alguns bons meses se eu sentir segurança em usar esse módulo talvez eu volte a testá-lo...

A critério de feedback digo que uma empresa do nível da pagar.me não tem vergonha na cara em fazer essas gambiarras em seu módulo!!! 
Não tem projeto? Não requisitos funcionais? não tem regras de negócio???

Esse checkout pagarme, por exemplo, é muito bom! Ele ajuda e muito clientes leigos porque já da de acompanhar em tempo real o que precisa arrumar no formulário etc... 

Agora aquele botão pagar ali é uma das piores gambiarras que eu já vi na vida!!!! tudo bem.. ele finaliza automático... mas e se eu não quiser que finalize? 
Motivos tem vários... um cupom, troca de frete, troca de meio de pagamento ETC....

Quero apenas lembrar que o checkout é a parte mais importante da loja. Esse tipo de gambiarra na minha loja... TO FORA!!!
MINHA OPINIÃO
.
Espero que o pessoal não leve minha crítica pelo lado negativo e possa trabalhar para melhorar os serviços... 

![screenshot_2](https://cloud.githubusercontent.com/assets/4355062/10080623/ffcfb40c-62c6-11e5-9fe5-e149e017df3a.png)

**Comment by lhcarvalho** [comment]
Ola Eneias,

Atualizei ele para a versao mais recente no meu localhost, e tambem baixei alguns dos pull requests que tem no github q pareceram relevantes. 

Eu não uso o "pagar.me checkout"

Estou tendo esse problema ao finalizar utilizando o pagar.me transparente...

Quando é uma conta nova, com um endereco novo, o checkout não finaliza de forma alguma. Aparece esse erro que todas as infos do cardhash estao faltando.

Quando é um usuario ja existente, em um endereco ja cadastrado, aparece esse erro quando o cliente clica no botao "finalizar pedido" enquanto a caixa de texto do cvv ainda esta ativa. Se ele clicar em outro lugar na tela, a tela vai atualizar o resumo do pedido. Se ele clicar no botao finalizar DEPOIS dessa atualizacao, o pedido é fechado...

Super estranho...

Enviado do meu iPhone

**Comment by davirs** [comment]
@lhcarvalho fala brother!!! aqui tenho o mesmo problema.. por isso estava tentando usar o pagarme checkout... nada feito...

**Comment by lhcarvalho** [comment]
Fala @davirs!
Não somos os únicos com esse problema... Tem outros 'issues' provavelmente com a mesma origem aqui no github...
Estranho é que isso parece funcionar em algumas lojas...
Vamos ver se o pessoal da inovarti consegue resolver...
Boa sorte por ai!

**Comment by eneiasramos** [comment]
Olá @davirs ! Até o presente momento estou aguardando o endereço da sua loja para conseguir te ajudar.

Olá @lhcarvalho! Eu respondi em outra issue https://github.com/pagarme/pagarme-magento/issues/11 sobre alguns problemas em sua loja que precisam ser corrigidos.

**Comment by davirs** [comment]
conforme dito pelo skype me dispus hoje a ficar em função disso e estou até agora esperando. 

@jgabrielfaria

**Comment by davirs** [comment]
@jgabrielfaria Até o momento vários testes foram feitos e nenhuma solução definitiva foi encontrada.
Continuo a disposição para realização de testes etc porém preciso de mais agilidade. Meus clientes estão sem usar o módulo... A cobraça está no limite...

@eneiasramos Obrigado pela força

**Comment by eneiasramos** [comment]
@davirs conforme conversamos os problemas de finalização de pedidos com o pagarme e OSC foram resolvidos.

**Comment by davirs** [comment]
@eneiasramos @jgabrielfaria Confirmo que no módulo magento (não uso a versão pagarme checkout) aparentemente os erros foram resolvidos. 

Quero deixar aqui meu agradecimento formal ao Eneias. Ele realmente se comprometeu a resolver os problemas e resolvel! Já estou lidando com pagarme a praticamente um ano.. o pessoal interno só desconversa e resolver que é bom nada.
Então, parabéns Eneias pela dedicação e bom trabalho. Pessoas boas a gente não pode medir elogios.

Sigo agora com nova briga com pagarme que são os retornos de erros issue #21 (só depende da pagarme)

**Comment by eneiasramos** [comment]
@davirs disponha! abçs!

**Comment by wederson** [comment]
Olá @eneiasramos 
estou com o mesmo problema. Existe algum fix para esse problema?

**Comment by davirs** [comment]
@wederson foi resolvido o problema.

1 - instale a nova versão do módulo do pagarme corretamente nas devidas pastas do magento
2 - instale os fixes no OSC:
https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro/commit/de0fe40439960b621e33b94ac17188a7371b7b3e

https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro/commit/4dae6f50d48f150f99fc1b828497eccb480bfe40

valeu fera!

**Comment by wederson** [comment]
Obrigado @davirs 
era exatamente isso. Obrigado

**Comment by davirs** [comment]
Esse mesmo erro ocorre no meu servidor utilizando cloudflare. Desativando o cloud funciona...

![erro](https://cloud.githubusercontent.com/assets/4355062/9419558/164f1f46-4833-11e5-97a0-27ca7ebb6b93.png)

Tenho a última versão do OSC6 e a última versão do módulo pagarme.
pela lógica, se o problema já foi resolvido.. o módulo não está conseguindo carregar algum arquivo fora algo nesse sentido...
meu cloudflare está configurado para não gerar cache do checkout.

poderia me informar se a extensão carrega algum JS de fora?
poderia me informar os IPs da pagarme para adicionar no whitelist?

@eneiasramos @lhcarvalho
