### ISSUE TITLE
Adicionar 'lib/pagarme' ao modman

### ISSUE THREAD

**Issue by raphaelsuzuki** [pagarme/pagarme-magento#50]
Na atualização que adicionou o diretório 'lib/pagarme', faltou fazer referência ao symlink no arquivo do modman, o que causa o Observer.php não encontrar o referido diretório.

**Comment by SocialGroups** [comment]
Olá Raphael boa tarde tudo bem ?

Raphael efetuamos a inclusão do 'lib/pagarme', no modman : [commit](https://github.com/pagarme/pagarme-magento/commit/c4558dd594650f4aae69c9e2730d1858b5ea49d3)

**Comment by raphaelsuzuki** [comment]
Boa tarde, @SocialGroups .

Muito obrigado!
