### ISSUE TITLE
Freeze ao trocar opção de frete

### ISSUE THREAD

**Issue by 3m0** [pagarme/pagarme-magento#51]
Ola,

Estamos com um problema na hora de trocar a opção de frete. O browser praticamente trava ao mudar entre as opcoes do frete e depois volta ao normal.

Testamos em multiplos browser e computadores. Ao desativar o plugin da pagar.me, o problema se resolve.

Estamos usando o one step checkout da amasty.

Alguma ideia do que pode ser?

**Comment by SocialGroups** [comment]
Olá bom dia tudo bem ?

Primeiramente nos desculpa a demora, infelizmente o github não nos notificou sobre a issue, poderia por favor nos informar qual é a url da loja de vocês para que possamos analisar o que pode estar ocorrendo.

Ficamos no aguardo e qualquer dúvida estamos a disposição.
Atenciosamente,

**Comment by ricardotulio** [comment]
Olá 3m0, tudo bem?

Analisamos esse problema e identificamos que esse problema ocorre ao usar o módulo OSC com temas customizados. Esse problema não ocorre necessariamente pelo módulo do Pagar.me ou o módulo OSC. Encontramos diversos casos onde as classes CSS tiveram seu nome trocado ou problemas no carregamento dos arquivos JavaScript pelo tema, portanto, estou encerrando essa issue.
