### ISSUE TITLE
Valor do frete não está incluso nas parcelas do cartão

### ISSUE THREAD

**Issue by mandelaloko** [pagarme/pagarme-magento#54]
Mestre, o valor do frete não está sendo exibido no select que fica as parcelas do cartão de crédito.

Exemplo:
![captura de tela 2016-12-14 as 15 54 25](https://cloud.githubusercontent.com/assets/13973499/21194052/a6f66d1c-c215-11e6-88d9-ec15e4d06280.png)

Consegue dar um help?

**Comment by fabaugsilv** [comment]
Caros,

Estou tendo o mesmo problema, muitas vezes não esta incluindo o valor do frete no cartão, ele só recalcula corretamente, se manualmente clicar na fase "Forma de Entrega" e avançando para " Informação de Pagamento" novamente

Existe algum bugfix?

**Comment by mandelaloko** [comment]
@fabaugsilv se não conseguirem achar o erro, terei que ir no código fonte do plugin e tentar arrumar, caso eu consiga te envio o código.

**Comment by derekstavis** [comment]
cc @devdrops @ricardotulio @xduh

**Comment by devdrops** [comment]
@mandelaloko @fabaugsilv fala pessoal!

Esse problema já estava identificado assim como outras correções, que estão sendo executadas em paralelo às nossas atividades. Pretendemos publicar as correções o quanto antes pois sabemos como isso impacta no uso deste módulo, e caso queiram contribuir com um pull request, sintam-se à vontade para colaborar.

**Comment by mandelaloko** [comment]
Opa!
blz, @devdrops

**Comment by ricardotulio** [comment]
@mandelaloko e @fabaugsilv fala pessoal, beleza?

Esse problema foi corrigido essa semana no PR #63 junto com o problema do calculo de juros para compras parceladas, portanto estou encerrando essa issue. 

Muito obrigado pelo feedback de vocês :D
