### ISSUE TITLE
Aconteceu de um cliente ter o cartão elo e o checkout selecionou cartão Aura.

### ISSUE THREAD

**Issue by thiagorock22** [pagarme/pagarme-magento#66]

**Comment by devdrops** [comment]
Olá @thiagorock22!

Muito obrigado por notificar a gente nisso! Teria mais detalhes desse cenário? Poderia validar o BIN [neste link](https://www.binlist.net/) e colocar o resultado (exceto o BIN) aqui?

**Comment by thiagorock22** [comment]
O que posso dizer é que começa com 50677..., no caso o cartão era ELO.

Resultado:

Brand	VISA
Country Code (ISO3166-1)	US
Country	United States
Bank	
Card Type	DEBIT
Latitude and Longitude	38 -97
Card Sub Brand	Visa Plus
Card Category

**Comment by devdrops** [comment]
Oi @thiagorock22, tudo certo?

Cara, a algumas semanas atrás fizemos melhorias para identificação de bandeiras. Poderia por gentileza confirmar se você mantem a versão mais atualizada deste módulo? Se sim, verificou se o problema persiste ou se foi solucionado?

**Comment by thiagorock22** [comment]
Olá, eu acabei alterando manualmente aqui, mas vou verificar essa atualização e dou um breve retorno.

**Comment by devdrops** [comment]
Ok, ficamos no seu aguardo @thiagorock22!

**Comment by vgsmith** [comment]
Olá @thiagorock22 , como vai?

Como não tivemos mais notícias suas, estou encerrando esta issue. Caso volte a ter problemas, é só reabri-la.

Grande Abraço
