### ISSUE TITLE
Problema de lentidão ao instalar módulo Pagarme

### ISSUE THREAD

**Issue by jpedro21** [pagarme/pagarme-magento#69]
Boa tarde Pessoal!

Sou desenvolvedor Magento e venho notando que todas as lojas que possuem o módulo do Pagarme estão sofrendo com problemas de lentidão e queda. Ao desativar o módulo, as lojas voltavam ao ar quase que instantaneamente. Vocês chegaram mudar algo na API, ou no módulo que possa ter comprometido a estabilidade da loja? 
OBS: Logs do servidor vem relatando diversos erros com este módulo.

**Comment by lucasPiovesan** [comment]
Também estou tento o mesmo problema. 

Para ser exato o servidor acusa erro relacionado ao procedimento feito no app/code/community/Inovarti/Pagarme/Model/Quote/Address/Total/Fee.php

Esse problema começou do nada em várias lojas que ajudo a gerenciar.

**Comment by deivisonarthur** [comment]
Opa pessoal, boa tarde. To meio sumido né rs

Nós fomos os primeiros a desenvolver o módulo do pagarme e eles possuem uma
criptografia no checkout. Isso é até um subterfúgio para uma regra
importante do PCI, projetos com a https://stripe.com também fazem uso.

Basicamente a pagarme e o moip possuem uma API para geração das parcelas,
com isso temos um "processamento" que depende de servidores fora para
carregar a parte do pagamento.

Já o pagarme juntamente com o stripe possuem mais uma conexão via API antes
de finalizar. E com isso é mais um processo no checkout.

Basicamente nessa etapa eles fazem uma criptografia de todos os dados do
formulário, ou seja, nenhum dado é trafegado do formulário, apenas o hash
criptografado.

Ou seja, esses 2 processos ai são processos que dependem de conexões fora
do servidor e no checkout qualquer 1,2,3... segundos conta muito.

Basicamente todo SAAS prejudica o desempenho, exemplo em uma conexão com
qualquer que seja um gateway se tem um tempo que vai de 3 a 10 segundos,
isso só para processar os pagamentos.

Como a Pagarme possui mais 2x integrações uma para gerar as parcelas e
outra antes do finalizar, essas conexões tb podem variar em 1,2,3....
segundos.

Sempre quando vc requisita algo fora do servidor é um longo caminho que se
percorre, Exemplo: Vamos tratar a geração das parcelas.



   1. O cliente entra no checkout;
   2. O js dispara a requisição das parcelas a pagarme;
   3. Os dados como valor total e numero de contrato saem do e-commerce em
   direção do gateway da Pagarme.
   3.1 Nesse processo os dados saem do servidor que esta hospedado o
   ecommerce;
   3.2 Passam pela rede local do IDC;
   3.3 Saem para internet;
   3.4 Passam por vários backbones até chegarem no IDC que fica a Pagarme;
   3.5 Chegam a rede interna do IDC da Pagarme;
   3.6 Processam e gera as parelas;
   3.7 Fazem todo caminho reverso até chegar ao servidor da loja;
   3.8 Fazem o caminho até a internet do cliente;
   3.9 Chegam na rede interna do cliente;
   3.10 São interpretados pelo Navegador do cliente e é mostrado para o
   cliente


Ou seja, só nessa requisição ai se algo der problema ou ficar lento, fodeo.
vai ficar lento para carregar as parcelas tb. E até fechar o pedido faltam
mais 2 saidas a mais a serem feiras, como citei acima.

No Moip vimos isso e achamos horrível! Então solicitamos a fórmula de como
se é montado o parcelamento e criamos um módulo interno para calcular o
parcelamento.

Exemplo de como ficou o nosso módulo de cálculo do parcelamento usando o
juros de amortização da moip

[image: Imagem inline 1]


Bem porque eles fazem isso?

Os gateways possuem uma negociação de taxa para cada cliente, por isso usam
a consulta por API para certificar do valor cobrado e tb para ficar mais
prático para o cliente.


Porque a pagarme e a stripe fazem mais uma requisição?

Eles fazem isso para se enquadrar no PCI (Aqui no Brasil vários falam que
são PCI, mas muitos não são ou tem apenas o servidor homologado e não todo
o processo de pagamento. PCI é tipo a ISO tem vários tipos)

Primeiramente essa regra seria para quem não tivesse certificado de
segurança, assim todos os dados os dados do formulário primeiro seria
criptografado e depois enviado somente o hash para o gateway, que possui
uma criptografia tipo RSA faria a descriptografia dos dados.

Ué... Então se eu tiver SSL posso tirar essa etapa do módulo?

Não rs, Isso porque hoje em dia vários e-commerces entenderam de forma
errada quando o Google falou que precisa ter o shop com HTTPS para ser mais
seguro.

O Google colocou que precisaria ter ao menos uma página, mas muitos
entenderam que seria o shop full em HTTPS e assim colocaram todo o shop em
HTTPS.

Como o HTTPS é pesadíssimo (isso porque eles possuem o esquema de
criptografia, por isso tem o cadeado e chave como representações do RSA) os
clientes reclamam com a infra e o sysadmin faz algo que chamamos de SSL
OFFLOADING.

O papo de SSL OFFLOAIND é bem escasso no Google. Ele seria um tipo de Proxy
Reverso, onde removeria toda a criptografia do SSL. Com isso as páginas
HTTPS ficam muito mais rápidos e podem ser cacheados (As páginas HTTPS não
poderiam antes ser cacheada, porque cada página possui uma criptografia que
só o cliente consegue descriptografar)

Ou seja, usando essa técnica tona os shop inseguros, pois estariam
enganando o navegador, entregando o Header como sendo HTTPS mas o corpo da
página como sendo HTTP. Assim se vc escutar a porta 443 em tese você
conseguiria capturar todos os dados.

Esse vídeo aqui é bem básico e explica um pouco como funcionaria o SSL (É
bem interessante, porém ele esta defasado. Isso porque antes não se existia
a técnica SSL OFFLOADING)
https://app.wistia.com/embed/medias/a5153856ce?width=640&height=360&autoplay=true&playbutton=false&controls_visible=false&end_video_behavior=default


Grandes projetos fazem uso dessa técnica de enganar o navegador, e bem
provavelmente o Google deve notar isso tb, e não vai demorar muito ele vai
penalizar esses shops. Porque o SSL nesses projetos estão enganando o
navegador e os clientes.


   - https://www.dinda.com.br/
   - https://www.tricae.com.br/
   - https://www.kanui.com.br/
   - https://www.dafiti.com.br/


Visando ficar então dentro dos padrões do PCI de segurança, a pagarme e
stripe usam essa scriptografia mesmo quando se tem SSL. Como eles não sabem
quem faz o SSL OFFLOADING eles usam essa regra para todos.


Ao ter tantos vai e vem no checkout isso acaba necessitando que o mundo
esteja em plena harmonia para não dar problema e tudo ocorrer rápido.
Quanto mais requisições você tiver em seu site ou e-commerce ha projetos
externos, mais lentos ele ficará. Porém hoje em dia é impossível de não se
ter o mínimo de integrações assim e por isso vale a pena otimizar sempre ao
máximo e ficar sempre de olho (recomendo o pingdown ou new relic). Exemplo
de requisições externas.


   - Facebook
   - Twiter
   - Site Blindado
   - Selos de certificados
   - Gateways
   - Correios
   - Gateways de frete
   - Erps,.....


Esse daqui é um dos poucos que falam sobre o SSL OFFLOADING e cita os
benefícios e pontos contra (segurança) É como eles falam no texto *Não
existe almoço de grátis!"*


*www.windowsecurity.com/articles-tutorials/web_server_security/SSL-Acceleration-Offloading-Security-Implications.html
<http://www.windowsecurity.com/articles-tutorials/web_server_security/SSL-Acceleration-Offloading-Security-Implications.html>*

o texto é longo, mas creio que seja bem importante. Tomará que consegui
ilustrar e explicar de forma ampla :D

vlw



----------

Atenciosamente


*Deivison Arthur L. Serpa*
Founder & CEO Inovarti - Soluções Avançadas em E-commerce


Cel: (21) 99203-8986
Skype: deivisonarthur

sites e blog:

   - br.linkedin.com/pub/deivison-arthur/1b/35/468/
   <http://br.linkedin.com/pub/deivison-arthur/1b/35/468/>
   - https://angel.co/inovarti-advanced-ecommerce-solutions
   - www.deivison.com.br
   - www.inovarti.com.br



"A *Inovarti* <http://www.inovarti.com.br/> é uma empresa que aspira
inovação e para nós o full acompanhamento tecnológico garante a evolução e
crescimento de nossos clientes. Alinhamos nossa exclusiva qualidade
diferenciada com as melhores parceiras tecnológica do mercado."


"É melhor esperar que um programador produtivo torne-se disponível do que
esperar que o primeiro programador disponível torne-se produtivo!"

2017-01-26 16:05 GMT-02:00 Lucas Piovesan <notifications@github.com>:

**Comment by jpedro21** [comment]
Muito obrigado pela resposta Davison. Ficou muito boa a explicação.
Em relação as parcelas que vocês tentaram realizar por calculo invés de comunicar com server, vocês já possuem essa parte desenvolvida? A versão atual que esta no Github já possui esta feacture?

**Comment by devdrops** [comment]
@jpedro21 @lucasPiovesan boa tarde! Sou desenvolvedor aqui no Pagar.me e gostaria de entender mais sobre o problema reportado.

Estamos investigando cenários semelhantes porém singulares, onde clientes possuem cerca de 10 módulos instalados (contando com o nosso). Para ajudar nessa investigação, poderiam fornecer mais detalhes como:

- Módulos instalados (nome e versão);
- Versão do Magento;
- Versão do PHP;
- Método de instalação do módulo Pagar.me.

Desde já agradeço!

**Comment by jpedro21** [comment]
Bom dia Pessoal!
-Possuímos diversos módulos, porem todos estão integrados, não possuindo conflitos com Observers ou Rewrites.
-Versão PHP: 5.5.9
-Fizemos um Merge da versão atual do Pagarme com instalado em nossa loja. Notamos que há várias alterações. Vamos atualizar a versão, e ver se o problema diminuirá.

**Comment by devdrops** [comment]
Olá @jpedro21, bom dia!

Muito obrigado pela resposta. De fato, fizemos alterações no módulo (dentre elas, sobre chamadas no Observer), por isso é importante mantê-lo atualizado. Só para entender: quando você diz `fizemos um merge da versão atual`, você quer dizer a instalação da versão atual?

Poderia também nos dizer:

- Qual a versão do Magento utilizada;
- Forma de instalação do nosso módulo.

Ficamos no seu aguardo para validação.

**Comment by jpedro21** [comment]
Quando falei que fizemos um merge, apenas comparamos as diferenças da versão atual utilizada e a do GIT.
A versão do Magento é 1.7.0.2
A forma de instalação foi apenas jogar as pastas do pagarme na pasta raiz do projeto.

**Comment by devdrops** [comment]
Oi @jpedro21!

Pode por favor confirmar se o problema persiste?

**Comment by leonampd** [comment]
@jpedro21 @lucasPiovesan fechando essa issue, ok? Se por acaso ainda estiverem com esse problema fiquem à vontade para reabrir.

abs
