### ISSUE TITLE
Opção de cancelar autorização do cartão

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#84]
Ao cancelar um pedido não capturado, percebi que o módulo não cancela a operação no Pagar.me.
Acho interessante adicionar uma opção de cancelar operações não capturadas.
Não é necessariamente um estorno, mas é importante, pois a autorização sensibiliza o cartão do cliente, mantendo o valor bloqueado.

**Comment by xduh** [comment]
@rafaelpatro Não temos uma recurso especifico para cancelar a autorização, o caminho para isso seria realizando um estorno da transação autorizada.

**Comment by rafaelpatro** [comment]
Se estornar uma transação _não capturada_, o Pagar.me libera o valor reservado no cartão do cliente?

**Comment by xduh** [comment]
Exato

**Comment by rafaelpatro** [comment]
Perfeito! Isso é muito útil.
Vou enviar uma PR para adicionar essa opção então.

**Comment by devdrops** [comment]
Oi @rafaelpatro, tudo certo?

Cara, ainda tem planos de seguir com essa issue? Vi pelos PRs que você abriu e não identifiquei nenhuma alteração relacionada com esta issue.

**Comment by leonampd** [comment]
Oi @rafaelpatro tudo bem? Estou fechando essa issue ok? Ainda assim, fique à vontade para colocá-la em discussão novamente.
