### ISSUE TITLE
Opção de Reembolso Parcial

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#94]
Adicionar opção de reembolso parcial.

**Comment by devdrops** [comment]
Favor seguir a formatação original para issues, conforme [modelo](https://github.com/pagarme/pagarme-magento/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by leonampd** [comment]
Oi @rafaelpatro vi que existe um commit no seu repo com essa implementação. Se quiser, abra um PR marcando os devs do Pagar.me para avaliar. Vou fechar essa issue mas fique à vontade de reabrí-la se julgar necessário, ok?
