### ISSUE TITLE
Opção de Captura Parcial

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#95]
Adicionar opção de captura parcial.

**Comment by devdrops** [comment]
Favor seguir a formatação original para issues, conforme [modelo](https://github.com/pagarme/pagarme-magento/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by leonampd** [comment]
@rafaelpatro pretende seguir com essa implementação? Se sim, fique à vontade de reabrir essa issue, ok?
