### ISSUE TITLE
Muitas falhas "número de telefone inválido"

### ISSUE THREAD

**Issue by rafaelpatro** [pagarme/pagarme-magento#98]
## Contexto

Na finalização da compra, o módulo está recusando pedidos, alegando número de telefone inválido.  Clientes com pouca experiência tem dificuldade para entender, preenchem sem prefixo, sem DDD, e acabam abandonando o site devido a falta de clareza.

## Ambiente

* Magento Community 1.9.3.0
* Módulo Pagar.me 0.1.6
* Servidor Linux
* PHP 7.0.8
* Apache 2.4
* MySQL 5.6

## Posssível correção

Seria interessante explicar na mensagem como digitar um número válido. Ou então colocar uma máscara no campo em questão.

**Comment by rafaelpatro** [comment]
Boa tarde

Dei uma pesquisada no módulo e não encontrei essa validação, o que me leva a crer que pode estar sendo feita no webservice Pagar.me.
Alguma possibilidade de melhorar essa mensagem?

**Comment by xduh** [comment]
@rafaelpatro por favor, indique a mensagem exata, para podermos confirmar se é retornada da API.

**Comment by rafaelpatro** [comment]
A mensagem é a mesma do título "número de telefone inválido". O cliente vê
essa mensagem ao clicar em Finalizar Pedido, após ter fornecido todos os
dados cadastrais; após ter escolhido a forma de entrega; após ter
preenchido a forma de pagamento; após revisar os totais. É claro, caso o
telefone tenha sido informado sem DDD, ou sem prefixo, ou com zero antes do
DDD.

Em 7 de mar de 2017 4:25 PM, "Eduardo Nascimento" <notifications@github.com>
escreveu:

**Comment by ricardotulio** [comment]
Fala @rafaelpatro, tudo bem?

O nosso não altera a forma como os usuários se cadastram, pois já existem módulos que faz isso muito bem, então a única coisa que nós precisamosée que o nome do campo de telefone permaneça o mesmo.

É muito comum que lojas utilizem o módulo [OSC](http://onestepcheckout.com.br/) por exemplo, e não faria sentido sobreescrevermos a validação de telefone, CPF, entre outros campos.

**Comment by rafaelpatro** [comment]
Ao enviar os dados da compra para a API Pagar.me, a API retorna "numero de
telefone invalido" para diversos clientes.

Em 13 de mar de 2017 4:20 PM, "Ricardo Ledo de Tulio" <
notifications@github.com> escreveu:

Fala @rafaelpatro <https://github.com/rafaelpatro>, tudo bem?

O nosso não altera a forma como os usuários se cadastram, pois já existem
módulos que faz isso muito bem, então a única coisa que nós precisamosée
que o nome do campo de telefone permaneça o mesmo.

É muito comum que lojas utilizem o módulo OSC
<http://onestepcheckout.com.br/> por exemplo, e não faria sentido
sobreescrevermos a validação de telefone, CPF, entre outros campos.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pagarme/pagarme-magento/issues/98#issuecomment-286214852>,
or mute the thread

**Comment by Josano** [comment]
Alguém conseguiu resolver essa questão do número do telefone no pagar.me?

Tenho um cliente que está com o mesmo problema confome mensagem abaixo:

Houve uma falha ao processar o pagamento do seu pedido. 26/06/2017 11:11:51
Razão: número de telefone inválido.

**Comment by ronanfc** [comment]
Estou com o mesmo problema a API retorna "numero de telefone invalido" para diversos clientes, pois o cadastro da loja permite colocar o telefone tanto de fixo quanto de celular, quando insiro o fixo (que tem 8 dígitos) ele aceita, mas a maioria dos clientes se cadastram usando celular (que tem 9 dígitos). Como resolvo este problema.

**Comment by leonampd** [comment]
Fala @ronanfc @Josano e @rafaelpatro tudo bem?
 
> O nosso não altera a forma como os usuários se cadastram, pois já existem módulos que faz isso muito bem, então a única coisa que nós precisamos é que o nome do campo de telefone permaneça o mesmo.

> É muito comum que lojas utilizem o módulo OSC por exemplo, e não faria sentido sobreescrevermos a validação de telefone, CPF, entre outros campos.

Diante desse cenário nosso módulo não deveria interferir nesse escopo da loja. Vou fechar essa issue, mas se julgarem necessário, podem reabrir a issue e retomar a discussão, ok?

**Comment by Josano** [comment]
Bom dia Leo, tudo bem?

Li todas as interações, gostaria apenas que o número fosse validado corretamente quando enviarmos para a API.
Ou que sejamos orientados em como proceder já que essa questão do telefone não ocorre com outros metódos de pagamento ( moip, pagseguro, etc.. )
Acredita ser possível ser feito algo neste sentido?

Abraços,
Josano

**Comment by davirs** [comment]
Vou postar aqui com intuito de ajudar quem está tendo este problema.
Alguns templates ou checkouts utilizam outros campos para obter o número de telefone , exemplo fax(billing:fax) que também é um padrão do magento.

O pagarme só vai entender se o campo for o telefone(billing:telephone) padrão do magento. 
Eu sugiro utilizar este mesmo campo para telefone ou celular, não há necessidade de 2 campos para telefone.

o formato para telefone é simples: ddd+numero (ex: 1199995555 )
se colocar máscara no frontend é só salvar neste formato.

**Não é somente o telefone, é qualquer campo obrigatório fora do padrão que a API do pagarme vai retornar erro(por isso a importância das validações):**
para CPF também são só números (ex: 26771982076)
CEP a mesma coisa, só números (ex: 88317200)

![Screenshot_11](https://user-images.githubusercontent.com/4355062/64494318-9d0c4b00-d261-11e9-8681-3817e5ab5926.png)
